### ISSUE TITLE
To Do Application using React Js

### ISSUE THREAD

**Issue by singhcodes26** [Avdhesh-Varshney/WebMasterLog#10]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : To Do Application
:red_circle: **Aim** : Create a application to keep track of day to day tasks.
:red_circle: **Tech Stack Used** : React
:red_circle: **Category** :  React-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
which react project are you talking about?
Mention it's name, description and working behaviour. @singhcodes26

**Comment by singhcodes26** [comment]
> which react project are you talking about? Mention it's name, description and working behaviour. @singhcodes26

Under React-js projects we have a file called Basic , which I thought will contain basic react project. So I was thinking if I can add a basic project under it like a To Do Application.

**Comment by Avdhesh-Varshney** [comment]
Ok, But follow the contributing guidelines and change the title of the issue with the name of the project like `To-Do-Application in ReactJS`.
Assigned to you. @singhcodes26

**Comment by singhcodes26** [comment]
> Ok, But follow the contributing guidelines and change the title of the issue with the name of the project like `To-Do-Application in ReactJS`. Assigned to you. @singhcodes26

okay

**Comment by Rishav9911** [comment]
If it's not completed yet can i work under this issue?

**Comment by Avdhesh-Varshney** [comment]
@singhcodes26 what about your work? Are you still working on it?

**Comment by singhcodes26** [comment]
> @singhcodes26 what about your work? Are you still working on it?

it will be completed by today

**Comment by Rishav9911** [comment]
hey is it still open to work?

**Comment by Avdhesh-Varshney** [comment]
@Rishav9911 Assigned to you. Follow the contributing guidelines carefully.

**Comment by singhcodes26** [comment]
> @singhcodes26 why have you closed this issue? Warn for the next time, this will debarred you from JWOC

That happened by chance I opened the link on mobile so by chance close this issue got clicked. And why are you threatning me to get debarred from JWOC? this already happened in another issue , someone created and closed it , you didn't warned him.  
Look over yourself as a maintainer , you took whole 3 days to even quote a reply. So think over yourself first.

**Comment by Avdhesh-Varshney** [comment]
@Rishav9911 what about your work? how far it has reached?

**Comment by Rishav9911** [comment]
hey actually i was working on it but am unable to complete it.  I won't be able to continue futher.

**Comment by singhcodes26** [comment]
@Avdhesh-Varshney I have completed the project, if you would agree I could complete this project.

**Comment by singhcodes26** [comment]
@Avdhesh-Varshney i have made the to do application , if you would agree I could complete this project.

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by Avdhesh-Varshney** [comment]
@kaif969 Assigned to you. Follow the contributing guidelines carefully.

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work on it under JWoC'24

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work on it under JWoC'24

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work on it under JWoC'24

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work on it under JWoC'24

**Comment by Avdhesh-Varshney** [comment]
@Bishal-35 Assigned to you. And don't spam in this way, drop the message and wait for my response for 24 hrs.
