### ISSUE TITLE
🧑‍💻: I want to add the screenshot of the different features of the website in the documentation

### ISSUE THREAD

**Issue by NumlStudentSE** [Avdhesh-Varshney/WebMasterLog#1000]
:red_circle: **Title** : Add Feature Screenshots to Documentation
:red_circle: **Enhancement Aim** : Improve the project documentation by including visual representations of key features to make it more user-friendly and informative.
:red_circle: **Changes** : 
Capture screenshots of different website features.
Annotate the images where necessary to highlight key functionalities.
Add the screenshots to relevant sections in the documentation.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? GSSoC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

Please assign this issue to me @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
Not required. Screenshots are already attached in their project's readme file.
