### ISSUE TITLE
Solar System Live Model using React JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#102]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Solar System Model
:red_circle: **Aim** : Build a website to showcase the solar system planets and stars to visualize for a children and provide data for each on click the object of the solar system.
:red_circle: **Tech Stack Used** : React JS, Bootstrap
:red_circle: **Category** :  REACT JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AryanPahuja21** [comment]
@Avdhesh-Varshney I would love to work on this issue but can I use tailwind instead of bootstrap.

Full name : Aryan Pahuja
GitHub Profile Link : https://github.com/AryanPahuja21
What is your participant role? : JWOC'24

**Comment by Avdhesh-Varshney** [comment]
@AryanPahuja21 Go ahead. No problem, but this is a React Application. OK.

**Comment by codebreaker3008** [comment]
@Avdhesh-Varshney  could you assign this to me ? I have a keen interest in working in these areas.

**Comment by Asymtode712** [comment]
Hey @Avdhesh-Varshney I can build this, can you please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 go ahead.
