### ISSUE TITLE
📃: Adding Recipe Search App to the front-end projects

### ISSUE THREAD

**Issue by shriyadindi** [Avdhesh-Varshney/WebMasterLog#1026]
:red_circle: **Title** :  Recipe Search App
:red_circle: **Aim** :  Adding a new project
:red_circle: **Tech Stack Used** : HTML, CSS, JS

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shriya D
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/Vanilla-JS-Projects/Intermediate/Recipe-Hunter
