### ISSUE TITLE
Interval Timer using Vanilla JS

### ISSUE THREAD

**Issue by AftabMankapure** [Avdhesh-Varshney/WebMasterLog#107]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Interval Timer 
:red_circle: **Aim** : User can set time for work and rest .
:red_circle: **Tech Stack Used** :  HTML, CSS, JS, 
:red_circle: **Category** :   Vanilla JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aftab Amin Mankapure
- GitHub Profile Link :  https://github.com/AftabMankapure
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)JWOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AftabMankapure Purpose of this project. can you elaborate it?

**Comment by AftabMankapure** [comment]
https://github.com/Avdhesh-Varshney/WebMasterLog/assets/125949765/f662ead1-2152-4731-96d5-3bcbfcde9b52

Assign me under JWOC

**Comment by AftabMankapure** [comment]
it is clear after video or not

**Comment by Avdhesh-Varshney** [comment]
> it is clear after video or not

It's clear. But 1 issue is assigned at a time. So, clear your assigned issue. Then it will assigned to you.

**Comment by AftabMankapure** [comment]
@Avdhesh-Varshney  assign me

**Comment by Avdhesh-Varshney** [comment]
@AftabMankapure Assigned to you. Follow the contributing guidelines carefully.
