### ISSUE TITLE
Stopwatch using Vanilla JS

### ISSUE THREAD

**Issue by SohanRC** [Avdhesh-Varshney/WebMasterLog#112]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Stopwatch
:red_circle: **Aim** : User can use this as stopwatch !
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sohan RoyChowdhury
- GitHub Profile Link : https://github.com/SohanRC
- What is your participant role? - JWOC 2024

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@SohanRC how it is different from #107 issue?

**Comment by SohanRC** [comment]
@Avdhesh-Varshney This is a different project . It is a stopwatch and functions like a stopwatch !

**Comment by SohanRC** [comment]
![Screenshot 2024-02-25 125902](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124901633/48556767-e106-4170-90de-8362a097d80e)

**Comment by SohanRC** [comment]
@Avdhesh-Varshney Please assign me this issue if you approve !

**Comment by Avdhesh-Varshney** [comment]
@SohanRC Assigned to you. But complete it within the time period of JWOC.

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Avdhesh-Varshney I would like to work on this as part of GSSOC'24. Could you please assign this to me?

**Comment by Avdhesh-Varshney** [comment]
@A-b-i-r-a-m-i-G-S Assigned to you. Provide the details also while taking the issue and follow the guidelines carefully.
