### ISSUE TITLE
Customized Scrollbar Implementation

### ISSUE THREAD

**Issue by ramith-kulal** [Avdhesh-Varshney/WebMasterLog#113]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :Customized Scrollbar Implementation
:red_circle: **Aim** : Implement a customized scrollbar for enhanced user experience on the website.
:red_circle: **Category** :  css
:red_circle: **Changes** :  Integrate custom scrollbar functionality into the existing website template.
Utilize CSS to style and customize the scrollbar to match the design aesthetics of the website.
Ensure compatibility across different browsers and screen sizes.

### Screenshots 📷

N/A

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ramith
- GitHub Profile Link : https://github.com/ramith-kulal
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
**working under JWOC**
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ramith-kulal Assigned to you. But maintain the theme of the website.
