### ISSUE TITLE
Weather app using React JS

### ISSUE THREAD

**Issue by sristy17** [Avdhesh-Varshney/WebMasterLog#117]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Weather Widget App
:red_circle: **Aim** : Create a weather application using React.js that displays different places weather conditions to the user.
:red_circle: **Tech Stack Used** : React, Material UI (APIs), CSS
:red_circle: **Category** :  React JS

***********************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sristy Paul
- GitHub Profile Link : https://github.com/sristy17
- What is your participant role? JWoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@sristy17 Assigned to you. Follow the contributing guidelines carefully.
Try to solve this issue within JWOC timeline. Also check other prs for the format of the pull requests.

**Comment by sristy17** [comment]
> @sristy17 Assigned to you. Follow the contributing guidelines carefully. Try to solve this issue within JWOC timeline. Also check other prs for the format of the pull requests.

Sure I am working on it!

A request can you please add label under medium or hard? please!

**Comment by Avdhesh-Varshney** [comment]
@sristy17 It will update automatically based on your project UI and code style. OK.

**Comment by sristy17** [comment]
> @sristy17 It will update automatically based on your project UI and code style. OK.

OK it's almost done creating a pr!
