### ISSUE TITLE
Palindrome Checker using Vanilla JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#12]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Palindrome Checker
:red_circle: **Aim** : Website to check the entered context is palindrome or not?
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by TanushreeBorase** [comment]
Full name : Tanushree Borase
GitHub Profile Link : https://github.com/TanushreeBorase
What is your participant role? (Mention the Open Source Program name : JWOC
<img width="523" alt="image" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130696335/bb6c31af-5cd6-4d69-a1c8-928b5a021bd8">
This is a basic one. I would like to work on this issue @Avdhesh-Varshney. Should we make it more attractive by adding some background image?

**Comment by Avdhesh-Varshney** [comment]
@TanushreeBorase Assigned to you. Follow the contributing guidelines carefully.
