### ISSUE TITLE
Project 📃:  JWT Authenticator with Role based Authorization

### ISSUE THREAD

**Issue by Pulkit95700** [Avdhesh-Varshney/WebMasterLog#122]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : JWT Authenticator with Role-based Authorization
:red_circle: **Aim**: It aims to provide user registration, login, access and refresh token authentication, multirole authorization with protected routes using middlewares.
:red_circle: **Tech Stack Used** : Express.js, Node.js, MongoDB
:red_circle: **Category** :  Node-JS-Projects

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Pulkit Gupta
- GitHub Profile Link : https://github.com/Pulkit95700
- What is your participant role? GSSOC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Pulkit95700** [comment]
Can you also tag it for GSSOC 24 and?

**Comment by Avdhesh-Varshney** [comment]
@Pulkit95700 Assigned to you. Follow the contributing guidelines carefully.

**Comment by Pulkit95700** [comment]
Thanks @Avdhesh-Varshney

**Comment by Pulkit95700** [comment]
Hello @Avdhesh-Varshney Completed with the issue and sent the pr. Please review the changes.
