### ISSUE TITLE
Project 📃: Email Subscription form with google sheet

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#128]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :   Email Subscription form with google sheet Using Javascript.
:red_circle: **Aim** :The aim of this project is to create an email subscription form using HTML, CSS, and JavaScript that stores the email addresses of subscribers in a Google Sheet. This allows for easy management and organization of subscriber emails, and enables the user to send targeted communications to their subscriber list.
:red_circle: **Tech Stack Used** :HTML,CSS,Javascript
:red_circle: **Category** :  Vanilla-JS-Projects

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Damini Chachane
- GitHub Profile Link : 
- What is your participant role? GSSOC24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎
Kindly assign this issue to me under GSSOC24 Level 2. I am able to make several advancement in this project.

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 Assigned to you. Follow the contributing guidelines carefully.
And keep this project under `Vanilla-JS-Projects` directory.

**Comment by Damini2004** [comment]
Ok sir kinldy assign this project under GSSOC24 that will be more beneficial.
