### ISSUE TITLE
Chat Bot using React JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#13]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Chat Bot
:red_circle: **Aim** : To build a chatbot application like `ChatGPT`
:red_circle: **Tech Stack Used** : REACT JS
:red_circle: **Category** :  React-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nandita27iitp** [comment]
@Avdhesh-Varshney Please assign this issue to me under JWOC 24

**Comment by Avdhesh-Varshney** [comment]
@nandita27iitp Assigned to you. Follow the contributing guidelines carefully.
Comment on 1 issue at a time.

**Comment by Avdhesh-Varshney** [comment]
@nandita27iitp what about your work? how far it has reached?

**Comment by nandita27iitp** [comment]
Almost complete

**Comment by Avdhesh-Varshney** [comment]
@nandita27iitp what's the update on this issue? Solve it within 2 days.

**Comment by DharshiBalasubramaniyam** [comment]
@Avdhesh-Varshney Can you please assign this issue to me?
