### ISSUE TITLE
feat: add codeql workflow for `javascript`

### ISSUE THREAD

**Issue by harmeetsingh11** [Avdhesh-Varshney/WebMasterLog#130]
### Describe your improvement idea or feature request

The repository contains code in `javascript` , it does not have workflow for code scanning. 

### How would you like to see it implemented?

I aim to implement the CodeQL workflow to automate security checks. CodeQL, GitHub's code analysis engine, will identify vulnerabilities in the code and present the findings as code scanning alerts. This workflow will be activated for every push, commit, and pull request through GitHub Actions.

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have checked the existing issues
- [X] I am a GSSoC'24 contributor

**Comment by Avdhesh-Varshney** [comment]
@harmeetsingh11 Assigned to you.
