### ISSUE TITLE
Project 📃: CRUD Operations

### ISSUE THREAD

**Issue by 1simransaini** [Avdhesh-Varshney/WebMasterLog#137]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : CRUD Operations
:red_circle: **Aim** :A full-stack web application enabling users to manage a dynamic list with features like adding, viewing, updating,
and deleting names
:red_circle: **Tech Stack Used** : HTML,CSS ,JS, Node, Express, MySQL
:red_circle: **Category** :  Node-JS-Projects

### Screenshots 📷

![Capture](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/91106038/93888691-a223-4121-bec3-18de639edc87)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Saini
- GitHub Profile Link : https://github.com/1simransaini
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@1simransaini don't close any issue until it's solved or closed by mentors or admins.

**Comment by 1simransaini** [comment]
@Avdhesh-Varshney I'm sorry actually I made 2 issues so that's way I thought to delete this up.
Will not do this in future.

**Comment by Hannan2004** [comment]
Hi myself Hannan Chougle,I am a 2nd year computer engineering student. Also a contributor at GSSOC 24 .I am a web developer have previously done some projects in mern stack,would request the project admin to please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Hannan2004 Assigned to you. Follow the contributing guidelines carefully.
For further communication, join the discord server https://discord.gg/tSqtvHUJzE

**Comment by 1simransaini** [comment]
@Avdhesh-Varshney, Please assign me this issue as I proposed it and have already created and checked the project on my local system; all I need to do is submit a pull request.
I wasn't assigned this issue initially as I was working on another issue, which has been successfully merged and closed. Thanks!
