### ISSUE TITLE
Password Generator using Vanilla JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#14]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Password Generator
:red_circle: **Aim** : Website to generate password of different lengths and patterns for the user according to the user's convenience.
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Hacxmr** [comment]
Hey! @Avdhesh-Varshney I am interested in contributing to this issue.
Name- Mitali Raj
GitHub Profile Link - https://github.com/Hacxmr
Role - JWOC

**Comment by Avdhesh-Varshney** [comment]
@Hacxmr Assigned to you. Follow the contributing guidelines carefully.

**Comment by Hacxmr** [comment]
> @Hacxmr Assigned to you. Follow the contributing guidelines carefully.

Sure @Avdhesh-Varshney

**Comment by Hacxmr** [comment]
@Avdhesh-Varshney Where do I need to create the folder?( Basic, intermediate or advanced)

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney Where do I need to create the folder?( Basic, intermediate or advanced)

Fork the repo and clone into your system. These are already created!

**Comment by Hacxmr** [comment]
<img width="491" alt="image" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/129144413/fd9a522e-c462-4310-92cd-309f15eea0c9">
where do I need to create Password Generator folder? (under vanilla-js-projects

**Comment by Avdhesh-Varshney** [comment]
@Hacxmr go according to your tag like,
- `Easy` - Basic
- `Medium` - Intermediate
- `Hard` - Advanced

So, you will create the folder under `Intermediate`
You should ask you doubts on discord so that others will also get in touch with these doubts.
