### ISSUE TITLE
Enhancement 🧑‍💻: Adding a footer to the website

### ISSUE THREAD

**Issue by YadlaMani** [Avdhesh-Varshney/WebMasterLog#142]
### WebMasterLog Repository (Proposing new issue)

:red_circle: **Enhancement Aim** :To add a footer

### Screenshots 📷
creating something similar to this 
![Screenshot 2024-05-15 174340](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/133841094/29b44707-7c8b-407e-b5e2-06f62a8077ad)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mani Yadla
- GitHub Profile Link : YadlaMani
- What is your participant role?GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by YadlaMani** [comment]
@Avdhesh-Varshney  pls assign me this issue under gssoc'24

**Comment by priti200** [comment]
Hola @Avdhesh-Varshney , I would like to work upon this issue and contribute on this project as a GSSOC'24 contributor. So, I would like to request you to assign me for this issure. I would like to use all my knowledge to add an unique footer to this website.

Name : Priti Gupta
Github link : https://github.com/priti200
role: GSSOC'24 contributor

Waiting for your response.
Thankyou!!!
regards,
Priti gupta

**Comment by Avdhesh-Varshney** [comment]
@YadlaMani Assigned to you.
Issues are assigned on the basis of FCFS.
