### ISSUE TITLE
Enhancement 🧑‍💻: Adding personalization features and recommendations

### ISSUE THREAD

**Issue by aditi-pai04** [Avdhesh-Varshney/WebMasterLog#144]
### WebMasterLog Repository (Proposing new issue)
:red_circle: WebMasterLog
:red_circle: **Enhancement Aim** : Adding more tech stack projects, personalization features based on user browsing and recommendation. 
:red_circle: **Category** :  
:red_circle: **Changes** :  A user profile, personalization for the profile (interests, proficiency in tech stack, recommendation based on previous interests, roadmaps)

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi N Pai
- GitHub Profile Link : https://github.com/aditi-pai04
- What is your participant role? GSSoC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@aditi-pai04 can you elaborate it more? How will this feature helpful for the project and why should i add it?

**Comment by Avdhesh-Varshney** [comment]
@aditi-pai04 Due to inactivity, I have closed this issue.
