### ISSUE TITLE
Project: FirstPost News website using Next.js, Tailwind.css, Sanity.io

### ISSUE THREAD

**Issue by codercake** [Avdhesh-Varshney/WebMasterLog#145]
:red_circle: Project Title : **NextJS NewsApplication**

:red_circle: Aim : A platform utilizing Next.js, a React framework for efficient server-side rendering, routing, and enhancing optimization. The page uses getServerSideProps to fetch server-side data on every page request. This allows the engine to crawl the page content and improves SEO. Integrated Sanity.io as a headless CMS, enabling efficient content creation, management, and delivery, enhancing the flexibility of the application.

:red_circle: Tech Stack Used : **Next.js, Tailwind.css, Sanity.io**

:red_circle: Category : **Next-JS-Projects**

Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/117517206/eb5283fd-ea01-412d-8d24-afecf4273145)

:white_check_mark:  Ishitha C - NextJs-newsApp

Full name : Ishitha Jain

GitHub Profile Link : https://github.com/codercake

Participant role: GSSOC'24

Open Source Program: GSSOC

**Comment by Avdhesh-Varshney** [comment]
@codercake Issue already present #50
