### ISSUE TITLE
Bug 🐛: Navigation issue

### ISSUE THREAD

**Issue by Priya-49** [Avdhesh-Varshney/WebMasterLog#150]
:red_circle: **Project Title** : Navigation issue
:red_circle: **Bug** :I noticed that we couldn't navigate back to the main/home page after viewing the project details. A 404 error is occured.
:red_circle: **Category** :  Front-end
 

### Screenshots 📷
![Screenshot (206)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118010930/777ca9ed-03a6-4bc7-91c7-d6ed18288ff4)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyanka Pragada
- GitHub Profile Link : https://github.com/Priya-49
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Priya-49 Assigned to you.

**Comment by Priya-49** [comment]
@Avdhesh-Varshney Upon further review, I've discovered that the issue I raised regarding the 404 error seems to be specific to my browser environment. I apologize for any confusion this may have caused. It appears that the problem is not with the project itself but rather with my browser configuration or extensions.

**Comment by Avdhesh-Varshney** [comment]
@Priya-49 ok np. For further communication, you can join my discord server.
