### ISSUE TITLE
Enhancement 🧑‍💻: Toggle Theme option

### ISSUE THREAD

**Issue by Rohitha-pudu** [Avdhesh-Varshney/WebMasterLog#151]
### WebMasterLog Repository (Proposing new issue)

Adding light and dark theme 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pudu Rohitha
- GitHub Profile Link : https://github.com/Rohitha-pudu
- What is your participant role? Gssoc24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by priti200** [comment]
Hola @Rohitha-pudu , I would like to work upon this issue and contribute on this project as a GSSOC'24 Contributor if you assign me for this issue. I have  previously added this project to my personal projects and I'll make sure that , I would add this toggle theme to this website as well.

Waiting and hoping for your response!!
Thankyou!!
Regards,
Priti Gupta (GSSOC'24 Contributor).

**Comment by Avdhesh-Varshney** [comment]
@Rohitha-pudu Assigned to you.
Issues are assigned on the basis of FCFS basis.

**Comment by Avdhesh-Varshney** [comment]
Not required!
