### ISSUE TITLE
Multiple Typos

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [Avdhesh-Varshney/WebMasterLog#158]
Hey @Avdhesh-Varshney,
I found some typos. ex:- style.css of sudoku game line 69 `input::-webkit-inner-spin-but
ton` should be `input::-webkit-inner-spin-button` and others.
I would like to fix this. Please add level and tag under GSSOC'24.
Best Regards,
Nikhil Verma

**Comment by Avdhesh-Varshney** [comment]
@NIKHIL0VERMA Can you provide the ss of the bug. For further communication, join discord server [link](https://discord.gg/tSqtvHUJzE)
For any kind of bug and enhancement, i have provided a proper template, so use it.

**Comment by Avdhesh-Varshney** [comment]
@NIKHIL0VERMA Due to inactivity, I have closed this issue.

**Comment by NIKHIL0VERMA** [comment]
Ooh, sorry for not responding. Actually busy with exams. Will sure start contributing after this week. Till then closing this issue will be great. 
Thankx for understanding
Nikhil Verma
