### ISSUE TITLE
Enhancement 🧑‍💻: Cards UI enhacement and fixed top navbar

### ISSUE THREAD

**Issue by Priya-49** [Avdhesh-Varshney/WebMasterLog#159]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Cards UI enchancement and fixed top navbar
:red_circle: **Enhancement Aim** :To improve the UI of the cards and to fix the top navbar so that it doesn't move upon scroll.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyanka Pragada
- GitHub Profile Link : https://github.com/Priya-49
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Priya-49 Assigned to you. For further communication, join discord server [Link](https://discord.gg/tSqtvHUJzE)

**Comment by Avdhesh-Varshney** [comment]
@Priya-49 what's the update of your work?

**Comment by Priya-49** [comment]
I am almost done...soon I'll send PR

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney  i would like to work on this can you please assign it to me
