### ISSUE TITLE
Amazon Prime Clone Website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#16]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Amazon Prime Clone
:red_circle: **Aim** : To clone the Amazon Prime Login Page of the [Website](https://www.primevideo.com/offers/nonprimehomepage/ref=atv_hom_pri_c_9zZ8D2_hm_hom) as it is.
:red_circle: **Tech Stack Used** : HTML, CSS
:red_circle: **Category** :  Front-end Projects

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Prithwi32** [comment]
@Avdhesh-Varshney l would like to work on this issue under JWOC

**Comment by Prithwi32** [comment]
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/115262737/ff121d87-f0c1-45ae-a53c-7113e6ad36b6)
Is the page your aim is to be implemented right?

**Comment by Avdhesh-Varshney** [comment]
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/3ba31725-8400-4246-90a3-86d6af0c1d1c)

@Prithwi32 This whole page is required to implement in it.
But you can raise another issue for that one ok under `Front-end-Projects` Directory.

**Comment by Prithwi32** [comment]
> ![image](https://private-user-images.githubusercontent.com/114330097/298391257-3ba31725-8400-4246-90a3-86d6af0c1d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDk3ODYsIm5iZiI6MTcwNTg0OTQ4NiwicGF0aCI6Ii8xMTQzMzAwOTcvMjk4MzkxMjU3LTNiYTMxNzI1LTg0MDAtNDI0Ni05MGEzLTg2ZDZhZjBjMWQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxNTA0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGUxMzUyY2Y2N2YyNjg5ZDM0ZjM4MGIwZjU4YmEwYzJhY2M0ZDcyZTdiZWY4YTFiN2IyZDUyOWU2OWQyYzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qb7szqTi5Jp3vpQozzYla8nWoYXmZTbFzUaW_weV4BQ)
> 
> @Prithwi32 This whole page is required to implement in it. But you can raise another issue for that one ok under `Front-end-Projects` Directory.

@Avdhesh-Varshney  Okay I will implement this as well along with page which I mentioned above...U can assign it to me under JWOC

**Comment by Avdhesh-Varshney** [comment]
@Prithwi32 Assigned to you. Follow the contributing guidelines carefully.

**Comment by Prithwi32** [comment]
> @Prithwi32 Assigned to you. Follow the contributing guidelines carefully.

Okay Thank You!
