### ISSUE TITLE
Project 📃: Dictonary App using Javascript

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#163]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Dictonary App using Javascript
:red_circle: **Aim** : It will helps to find out the word meaning as well as their way to pronounce.
:red_circle: **Tech Stack Used** :  HTML, CSS, JS.
:red_circle: **Category** : Vanila js

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- GitHub Profile Link :  https://github.com/Damini2004
- What is your participant role? GSSOC24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

Kindly assign this issue to me under GSSOC24 with the label.

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 Assigned to you. Follow the contributing guidelines carefully.
