### ISSUE TITLE
Project 📃: Hangman Game with Illustration

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#164]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Hangman Game with Illustration
:red_circle: **Aim** : It helps to increase the general knowledge by guessing answers of riddles.
:red_circle: **Tech Stack Used** : HTML, CSS, JS.
:red_circle: **Category** :  Vanilla-JS-Projects

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/62f051d5-6aaf-46e2-807c-9d244b0c42ec)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Damini Chachane
- GitHub Profile Link :  https://github.com/Damini2004
- What is your participant role? GSSOC24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

Kindly assign this issue to me under GSSOC24 with suitable level.

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 in `Issue creation guidelines` which is pinned above all the issues, it is mentioned more than 1 issue is not allowed and no games are allowed in this repository.
For further communication, join discord server https://discord.gg/tSqtvHUJzE
