### ISSUE TITLE
Enhancement 🧑‍💻: Add recently opened projects to dashboard

### ISSUE THREAD

**Issue by ritu713** [Avdhesh-Varshney/WebMasterLog#167]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : "Recently viewed Projects"
:red_circle: **Enhancement Aim** : User should be able to view all their recently viewd projects on the dashbaord
:red_circle: **Changes** :  Improve dashboard

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124053206/15670522-1215-4207-a172-7bee140d5ad0)
Here, the page is empty and this feature can be helpful!

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ritu Singh
- GitHub Profile Link : https://github.com/ritu713
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ritu713 i have already created seprate categories in sidebar to keep all the projects seprate.
Dashboard is empty because to explain about the project in an innovative manner. If you can do, explain it to me.
For further communication, join discord server https://discord.gg/tSqtvHUJzE

**Comment by ritu713** [comment]
I have texted you on discord to streamline the discussion :)
