### ISSUE TITLE
Project 📃: Train Booking Website

### ISSUE THREAD

**Issue by pulkit1417** [Avdhesh-Varshney/WebMasterLog#169]
### WebMasterLog Repository (Proposing new issue)
🔴 Project Title : Train Booking Website
🔴 Aim : Simplify and streamline the process of booking train tickets, offering users a convenient, transparent, and efficient platform to plan their rail journeys.
🔴 Tech Stack Used : HTML, CSS, Angular 17.
🔴 Category : Angular JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pulkit Gupta
- GitHub Profile Link : https://github.com/pulkit1417
- What is your participant role?  GSSOC Contributor.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by pulkit1417** [comment]
Pulkit Gupta
https://github.com/pulkit1417
What is your participant role? GSSOC Contributor.
(Please assign this to me I want to work on this, please label this as gssoc and level as you decide from my side it can be of level 2.)

**Comment by Avdhesh-Varshney** [comment]
@pulkit1417 Assigned to you. Follow the contributing guidelines carefully.
