### ISSUE TITLE
Auto commenting feature for new PR raised

### ISSUE THREAD

**Issue by suhanipaliwal** [Avdhesh-Varshney/WebMasterLog#180]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@suhanipaliwal Creating a lots of issues is considered as `spam`. So, from next time, create 1 by 1.
Assigned to you. And your other issues remains open until this is not resolved.

'''In PR comments along with a message provide the discord server link also. Link is mentioned below.'''

For further communication, join discord server https://discord.gg/tSqtvHUJzE.
