### ISSUE TITLE
Enhancement 🧑‍💻: Enhance the UI of footer

### ISSUE THREAD

**Issue by Saimanjari777** [Avdhesh-Varshney/WebMasterLog#181]
### WebMasterLog Repository (Proposing new issue)
:red_circle: Footer UI enhancement
:red_circle:  I want to make the footer look appealing and make it consistent with the website theme and style. Also, footer is covering the cards.
:red_circle: Footer change

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130165687/1c3b5e6e-2fab-4c43-9986-d457f5e0e7ac)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sai Manjari
- GitHub Profile Link : https://github.com/Saimanjari777
- What is your participant role? GSSoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Saimanjari777 Assigned to you. 
For further communication or any query, join discord server https://discord.gg/tSqtvHUJzE
