### ISSUE TITLE
Bug 🐛:  Next Js Card Style

### ISSUE THREAD

**Issue by dhruv8433** [Avdhesh-Varshney/WebMasterLog#182]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : WebMasterLog
:red_circle: **Bug** :  Card is not responsive as well design changed
:red_circle: **Category** :   Next JS
:red_circle: **Changes** :   we can change some style and apply grid for responsive

@Avdhesh-Varshney 

please check this out,
the card ui of next js card is changed 

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114583978/5608c9fa-c96a-44b6-8e00-f84f2fc6cbf0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Dhruv R Soni
- GitHub Profile Link :  https://github.com/dhruv8433
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
   GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@dhruv8433 same issue is already present. #159 
Before creating any issue, check out other issues whether it is already present or not.
You can comment on that issue, i will assign to you.
For further communication, join the discord server https://discord.gg/tSqtvHUJzE
