### ISSUE TITLE
Enhancement 🧑‍💻:  We can provide drop down list instead of static opetaions in single line

### ISSUE THREAD

**Issue by dhruv8433** [Avdhesh-Varshney/WebMasterLog#183]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : WebMasterLog
:red_circle: **Enhancement Aim** : Provide better ui
:red_circle: **Category** :   Next Js
:red_circle: **Changes** :  we can make drop down list for easy, medium and hard opetions

@Avdhesh-Varshney 

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114583978/a05a63f3-f5dc-4296-bdd5-29763cf03554)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Dhruv R Soni
- GitHub Profile Link :  https://github.com/dhruv8433
- What is your participant r ole? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
   GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@dhruv8433 Assigned to you. At one time, single issue is assigned to anybody.
For further communication, join the discord server https://discord.gg/tSqtvHUJzE

**Comment by dhruv8433** [comment]
@Avdhesh-Varshney Thank you
