### ISSUE TITLE
Bug 🐛:  "Routing Navigation Errors" For The Pages after refreshing.

### ISSUE THREAD

**Issue by MastanSayyad** [Avdhesh-Varshney/WebMasterLog#185]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : WebMasterLog
:red_circle: **Bug** :  Pages only work for a short time, when you refresh the page, it shows a 404 page.
:red_circle: **Category** :  React, Vanilla
:red_circle: **Changes** :   It only happens if you don't configure your `vercel.json` The routes don't get recognized except the "/" Home page routes. To rectify the {404 Not Found Error}, it is necessary to establish redirect and rewrite rules for the React Router application. These rules will assist the application in preventing the **"Page Not Found" error**. We have to create a `vercel.json` file

### Screenshots 📷

- After refreshing **' Angular JS/Front End/Next JS/Node JS/React JS/Vanilla JS/Vue JS"** Pages 

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/101971980/e0d0dc38-3536-4680-9c23-ce3a5e503b35)

- **it shows 404 Not Found Error (You can check that)**

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/101971980/82c579a6-c4d3-4e02-8f7c-4a26790676b5)

We can call it a **Hidden BUG** which can lead to a failed user experience and a bad impression.

I would like to take care of all these pages' Navigation errors. @Avdhesh-Varshney 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mastan Sayyad
- GitHub Profile Link : https://github.com/MastanSayyad
- What is your participant role? : GSSOC 24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@MastanSayyad Assigned to you.
