### ISSUE TITLE
Bug 🐛:  All the project cards are not properly visible

### ISSUE THREAD

**Issue by shreya-paul-17** [Avdhesh-Varshney/WebMasterLog#188]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : The projects cards are not properly visible 
:red_circle: **Bug** : The 2 icons are getting hidden in the project cards by the footer section. the footer needs to get shifted a bit bottom so that the projects which are at the bottom is properly seen.
:red_circle: **Category** :  Front-end

### Screenshots 📷
![web-master-log](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/135226069/63cc0714-8242-4e7d-a808-1b32de66e89d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shreya Paul
- GitHub Profile Link : https://github.com/shreya-paul-17
- What is your participant role? GSSoC 2024 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@shreya-paul-17 Assigned to you.
