### ISSUE TITLE
Project :  Product Landing Page

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#197]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Product Landing Page 
:red_circle: **Aim** : This is frontend of the website helps user to enhance user engagement and know the product in better manner.
:red_circle: **Tech Stack Used** : HTML, CSS
:red_circle: **Category** :  Frontend Project

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- GitHub Profile Link :  https://github.com/Damini2004
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 Assigned to you.

**Comment by Damini2004** [comment]
@Avdhesh-Varshney  I am not contributing in website enhancement. I wanted to add Product Landing Website( shoe, watch,etc product ) in your frontend project section.
