### ISSUE TITLE
Project 📃: Cryptocurrency Finder App in React

### ISSUE THREAD

**Issue by Saimanjari777** [Avdhesh-Varshney/WebMasterLog#198]
### WebMasterLog Repository (Proposing new issue)
:red_circle:  CryptoCurrency Finder App
:red_circle: It list down the different crypto coins using the API.
:red_circle:  React+Vite
:red_circle: **Category** :  React JS project

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130165687/340fe62f-49f2-4073-80fb-85963bb405c6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sai Manjari
- GitHub Profile Link :  https://github.com/Saimanjari777
- What is your participant role? GSSoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Saimanjari777 Assigned to you. Follow the contributing guidelines carefully.
