### ISSUE TITLE
Project 📃: Typing Speed Test

### ISSUE THREAD

**Issue by 1simransaini** [Avdhesh-Varshney/WebMasterLog#199]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Typing Speed Test 
:red_circle: **Aim** : The Typing Speed Test  allows users to measure their typing speed, including metrics such as Words Per Minute (WPM), Characters Per Minute (CPM), and accuracy. The test lasts for a maximum of 60 seconds. Once typing begins, the remaining time, number of mistakes, WPM, and CPM are displayed at the bottom of the interface.
:red_circle: **Tech Stack Used** :  HTML, CSS, JS
:red_circle: **Category** :   Vanilla-JS-Projects

### Screenshots 📷

![Capture5](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/91106038/d55b3921-656f-436d-981e-bc901795da5b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Saini
- GitHub Profile Link : https://github.com/1simransaini
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@1simransaini no games allowed as mentioned in guidelines.
But this project is not a game, so assigned to you. And change the name of project `Typing-Test` ok.
