### ISSUE TITLE
Project 📃: Pomodoro Timer

### ISSUE THREAD

**Issue by Achala-Nayak** [Avdhesh-Varshney/WebMasterLog#200]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :  Simple Pomodoro Timer
:red_circle: **Aim** : The aim of this project is to create a simple yet functional Pomodoro timer app using React, HTML, and CSS. This project is designed to help beginners understand the basics of React and improve their front-end development skills. By working on this project, you'll learn how to build a user interface, manage state, handle events, and apply styling to create a clean and interactive web application. This project will also serve as a practical example of how to break down a larger application into smaller, manageable components, making it an excellent starting point for anyone looking to deepen their understanding of modern web development practices.
:red_circle: **Tech Stack Used** : HTML, CSS, JS,  React
:red_circle: **Category** : React-JS-Projects

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Achala Nayak
- GitHub Profile Link :  https://github.com/Achala-Nayak
- What is your participant role?  GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Achala-Nayak This issue is already present.
