### ISSUE TITLE
Enhancement 🧑‍💻: Adding any sample image for the projects that dont have any image 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#202]
### WebMasterLog Repository 
:red_circle: Adding sample image  :
:red_circle: **Changes** : I want to add any other common image for those projects who don't have any image .

### Screenshots 📷

![Screenshot 2024-05-29 113615](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/d491f6e5-68b2-4065-918c-2b394e6c4d63)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayushmaan Agarwal
- GitHub Profile Link :  https://github.com/Ayushmaanagarwal1211
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 Assigned to you and join the discord server.
