### ISSUE TITLE
Project 📃: World Clock 

### ISSUE THREAD

**Issue by Asymtode712** [Avdhesh-Varshney/WebMasterLog#203]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : World Clock
:red_circle: **Aim** : To determine the time of various parts of the world
:red_circle: **Tech Stack Used** :HTML, CSS, JS , WorldTimeAPI
:red_circle: **Category** :  Vanilla-JS-Projects

### Screenshots 📷
![WC](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/115717746/a6bb131c-c79e-4cde-8331-4dd14d439d3e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Siddheya Kulkarni
- GitHub Profile Link :  https://github.com/Asymtode712
- What is your participant role? GSSOC participant

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 don't create too many issues. This is already mentioned in guidelines.
Assigned to you and join the discord server for communication not go to other platforms.
