### ISSUE TITLE
Project 📃:  Random Quote Generator

### ISSUE THREAD

**Issue by Asymtode712** [Avdhesh-Varshney/WebMasterLog#207]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :  Random Quote Generator
:red_circle: **Aim** : To generate various quotes with the help of an API
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla-JS-Projects

### Screenshots 📷
![RQ](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/115717746/60e87fcc-9ae7-44a5-ae3b-68bc79f4ff23)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Siddheya Kulkarni
- GitHub Profile Link :  https://github.com/Asymtode712
- What is your participant role? GSSOC Participant

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Asymtode712** [comment]
Please assign me this issue

**Comment by Asymtode712** [comment]
@Avdhesh-Varshney I am done with all my previously assigned issues, please assign me this issue

Thank you!

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 go ahead.
