### ISSUE TITLE
Travel Website using React JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#21]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : A Travel Website
:red_circle: **Aim** : A website to showcase the different places of the world to the tourist to go there for a tour.
:red_circle: **Tech Stack Used** : React
:red_circle: **Category** :  React-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vishal2005025** [comment]
Name : Vishal Malyan
Github link : https://github.com/vishal2005025
I would like to work on this issue .
please assign it to me under JWOC'2024..

**Comment by vishal2005025** [comment]
sir , I have created 1 pr .
please assign it to me under JWOC'2024..

**Comment by Avdhesh-Varshney** [comment]
@vishal2005025 Assigned to you. Follow the contributing guidelines carefully.

**Comment by Avdhesh-Varshney** [comment]
@vishal2005025 what's the update on this issue? Solve it within 2 days.

**Comment by aditya-bhaumik** [comment]
Full name : Aditya Bhaumik 
Github Link : https://github.com/aditya-bhaumik
I would like to work on this issue 
Please assign this to me under GSSOC'24

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
