### ISSUE TITLE
Design a Logo for the project WebMasterLog

### ISSUE THREAD

**Issue by MehtabAsHellic** [Avdhesh-Varshney/WebMasterLog#212]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by Avdhesh-Varshney** [comment]
@MehtabAsHellic Assigned to you and join the discord server for communication pupose.

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic Assigned to you and join the discord server for communication purpose.

Sure, Will share some logo sample here soon.

**Comment by MehtabAsHellic** [comment]
should I design the logo color according to the current theme of the site https://web-master-log.vercel.app/,
or you want it as new branding identity

**Comment by MehtabAsHellic** [comment]
![2](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/101495398/63cf4472-7c0e-4057-b6b6-f16330409f84)
![1](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/101495398/2f802be7-39bf-45a7-8d1c-8b326cfee4ff)

@Avdhesh-Varshney  Let me know your thoughts

**Comment by Avdhesh-Varshney** [comment]
@MehtabAsHellic both of them are not looks nice. so you can either make some mixture to represent the colors to represent the tech stacks are mentioned in the website like red color for angular, etc.

You have to join the discord for the discussion purpose.

**Comment by MehtabAsHellic** [comment]
> @MehtabAsHellic both of them are not looks nice. so you can either make some mixture to represent the colors to represent the tech stacks are mentioned in the website like red color for angular, etc.
> 
> You have to join the discord for the discussion purpose.

ok
