### ISSUE TITLE
Bug 🐛: Favicon.ico update

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Avdhesh-Varshney/WebMasterLog#213]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :
:red_circle: **Bug** :
:red_circle: **Category** :  
:red_circle: **Changes** :  

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/125277258/8e6840d0-d870-41cd-8b5d-23a9fc97c291)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@RamakrushnaBiswal what's the logo are you considering? 
And for further communication purpose, join the discord server.
