### ISSUE TITLE
Bug 🐛: Subscribe form mail not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Avdhesh-Varshney/WebMasterLog#214]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : WebmasterLog
:red_circle: **Bug** : Subscribe form it not working like the validation
:red_circle: **Category** :   Frontend form validation
:red_circle: **Changes** :   add form validation

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/125277258/e7ed8098-428b-49e5-8760-edfc7f7debc0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name: @RamakrushnaBiswal 
- GitHub Profile Link : https://github.com/RamakrushnaBiswal
- What is your participant role? GSSOC-24 (Contributor)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@RamakrushnaBiswal properly fill the issue template

**Comment by RamakrushnaBiswal** [comment]
@Avdhesh-Varshney check

**Comment by Avdhesh-Varshney** [comment]
@RamakrushnaBiswal Asssigned to you. Go ahead.
