### ISSUE TITLE
Project 📃: Restaurant Website

### ISSUE THREAD

**Issue by arpy8** [Avdhesh-Varshney/WebMasterLog#215]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Restaurant Website
:red_circle: **Aim** : To create a front-end for restaurant website
:red_circle: **Tech Stack Used** : HTML, CSS, JS, Bootstrap
:red_circle: **Category** : Front-end-Projects

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/74809468/b5a50d20-fb28-464c-bb13-7d7d0a3dee11)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Arpit Sengar
- GitHub Profile Link :  https://github.com/arpy8
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@arpy8 Assigned to you. Follow the contributing guidelines carefully and join the discord server for communication.
