### ISSUE TITLE
Project 📃: FoodRecipe Finder

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#217]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **FoodRecipe Finder** :
:red_circle: **My project according users query finds the recipe details ** 
:red_circle: **Tech Stack Used** : HTML, CSS, JS 
:red_circle: **Category** :  Front-end Project

### Screenshots 📷
![Screenshot 2024-05-30 124820](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/7700dc74-3bbe-4c54-990f-f059066bbe79)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Amruta Jayanti
- [AmrutaJayanti](https://github.com/AmrutaJayanti)
- GSSOC'2024 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti mention the tech stacks are you using? Also, in other pr too.

**Comment by AmrutaJayanti** [comment]
Sorry for the inconvenience . I mentioned the stack and updated the comment

**Comment by AmrutaJayanti** [comment]
Sure! @Avdhesh-Varshney
