### ISSUE TITLE
Project 📃: Markdown Previewer

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#218]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Markdown Previewer** :
:red_circle: **Provide the markdown code it renders the HTML element** 
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** : Vanilla-JS-Project

### Screenshots 📷
![Screenshot 2024-05-30 193250](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/9ad93f8d-cffa-4434-8025-63f6be036f81)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Amruta Jayanti
- [AmrutaJayanti](https://github.com/AmrutaJayanti)
- GSSOC'2024 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AmrutaJayanti** [comment]
Sorry for the inconvenience. I mentioned the tech stack and updated the comment

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti Assigned to you. But keep this project inside the `Vanilla-JS-Projects`.
