### ISSUE TITLE
URL-Shortner website using Node JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#22]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : URL Shortner website
:red_circle: **Aim** : An application which can short the long urls into small urls using Express, mongoose, etc. or any thing else as a backend and provide a small url to the user.
:red_circle: **Tech Stack Used** : Node
:red_circle: **Category** :  Node-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nandita27iitp** [comment]
@Avdhesh-Varshney Please assign this issue to me under jwoc 24

**Comment by drick-infinity** [comment]
As I learned MERN tech stacks I enthuast to develop a website Here I can develop url shortner with node.js 
Assign this to me under gssoc'24

**Comment by Avdhesh-Varshney** [comment]
@drick-infinity Assigned to you. Follow the contributing guidelines carefully.

**Comment by 1simransaini** [comment]
@Avdhesh-Varshney , Please assign me this issue, since it seems that my proposed issue #228 is already present as #22. Thank you!

**Comment by Avdhesh-Varshney** [comment]
@1simransaini go ahead.
