### ISSUE TITLE
Project 📃: QR Code generator using React JS

### ISSUE THREAD

**Issue by Saimanjari777** [Avdhesh-Varshney/WebMasterLog#222]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :QR Code Generator
:red_circle: **Aim** : QR Code generator takes input from the user and generates QR code which is fetched from the API. 
:red_circle: **Tech Stack Used** : React
:red_circle: **Category** : React Js Projects

### Screenshots 📷

![Screenshot_20240531-155134](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130165687/581674ad-3a32-48bd-ac66-4f74b11a134b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sai Manjari
- GitHub Profile Link : https://github.com/Saimanjari777
- What is your participant role? GSSoC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Diyaa0313** [comment]
Full name: Diya Sen
GitHub Profile Link: https://github.com/Diyaa0313
What is your participant role? GSSoC
I would like to work on this issue @Saimanjari777

**Comment by Avdhesh-Varshney** [comment]
@Saimanjari777 Assigned to you. Follow the contributing guidelines carefully.
