### ISSUE TITLE
Bug 🐛: Cards not visible

### ISSUE THREAD

**Issue by aryansharma220** [Avdhesh-Varshney/WebMasterLog#223]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Web Master Log
:red_circle: **Bug** : Cards not visible
:red_circle: **Category** :  
:red_circle: **Changes** :  

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/133234867/a89599d2-0cff-4870-8812-cf20c144cb0d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aryan Sharma
- GitHub Profile Link : https://github.com/aryansharma220
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSoC 24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@aryansharma220 Assigned to you. For further communication, join the discord server.
