### ISSUE TITLE
Creating an About us Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#224]
### WebMasterLog Repository (Proposing new issue)
I will create an about us page for the website /

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 properly fill the issue template. It is mandatory ok.
For further communication, join the discord server.

**Comment by Ayushmaanagarwal1211** [comment]
Ok i will raise a new issue

**Comment by Ayushmaanagarwal1211** [comment]
Actually i want to create the about us page for the actually website for not a particular project that's why i am not able to fill all the mandatory details

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 ok np. 
1. Mention your open source program.
2. Join the project discord server and explain the content for the same.
