### ISSUE TITLE
Project 📃: Apple Website clone

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#225]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Apple Website clone
:red_circle: **Aim** : Clone the website
:red_circle: **Tech Stack Used** : HTML, CSS
:red_circle: **Category** :  Front-end Projects

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini
- GitHub Profile Link : https://github.com/Damini2004
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Diyaa0313** [comment]
Full name: Diya Sen
GitHub Profile Link: https://github.com/Diyaa0313
What is your participant role? GSSoC
I would like to work on this issue @Damini2004

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 can you provide the link of the apple page which you want to clone?
@Diyaa0313 go through any other issues having tags `Up for grabs`. As issue are assigned on FCFS basis. Ok.

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 are you working on it? And join the project discord server. 
It's mandatory.

**Comment by Damini2004** [comment]
@Avdhesh-Varshney  Yes i am working on it. Once i finished my work i will share link of website and create PR too. I joined discord server earlier sir.

**Comment by Damini2004** [comment]
@Avdhesh-Varshney 
https://www.apple.com/in/iphone-15/  
I have partial clone this website and there will be requirement i will complete it soon.
Kinldy assign this issue to me with label.

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 go ahead.
