### ISSUE TITLE
Project 📃: URL Shortener

### ISSUE THREAD

**Issue by 1simransaini** [Avdhesh-Varshney/WebMasterLog#228]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :URL Shortener
:red_circle: **Aim** : The primary aim of a URL shortener is to convert long URLs into shorter, more manageable links. The shortened URL redirects users to the original, longer URL when accessed.
:red_circle: **Tech Stack Used** :  HTML, CSS, JS, Node
:red_circle: **Category** :  Node-JS-Projects

### Screenshots 📷

![Capture1](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/91106038/4e85749f-e6ea-4f42-9829-6055a7688a8d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Saini
- GitHub Profile Link : https://github.com/1simransaini
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@1simransaini issue already present. #22 
Comment there, i will assign it to you.
