### ISSUE TITLE
Project 📃: Tic Tac Toe Game (frontend)

### ISSUE THREAD

**Issue by prachita0504** [Avdhesh-Varshney/WebMasterLog#229]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Tic Tac Toe Game
:red_circle: **Aim** :
:red_circle: **Tech Stack Used** : Frontend

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Prachita Singh
- GitHub Profile Link : https://github.com/prachita0504
- GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@prachita0504 No games allowed. Properly go through the issue creation guidelines.
