### ISSUE TITLE
Project 📃: Netflix clone project

### ISSUE THREAD

**Issue by Yashgabani845** [Avdhesh-Varshney/WebMasterLog#237]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Netflix Clone** :
:red_circle: **Entertainment and practice** :
:red_circle: **Tech Stack Used** : MERN (stripe for payments,firebase for storage). -->
:red_circle: **Category** : maybe Node project

### Screenshots 📷

![Screenshot (261)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127788321/a775d4e7-48b2-462b-afc8-e80ae74d606b)
![Screenshot (257)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127788321/1a6e2ff3-e80e-4158-8802-1e10b20c5805)
![Screenshot (259)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127788321/90f5f9e9-18e6-4163-ac05-8e5776ff6351)
![Screenshot (260) - Copy](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127788321/f703fb62-a26d-4bcf-89af-800de6714da3)
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Yash gabani 
- GitHub Profile Link : https://github.com/Yashgabani845
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Yashgabani845** [comment]
@Avdhesh-Varshney  i would be too happy to contribute my favorite project

**Comment by Avdhesh-Varshney** [comment]
@Yashgabani845 already present #75
