### ISSUE TITLE
Project 📃:  RGB Color Slider

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#238]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : RGB Color Slider
:red_circle: **Aim** : According to the entered input values, bg is changed to that respective color in RGB format
:red_circle: **Tech Stack Used** :  HTML, CSS, JS
:red_circle: **Category** :   Front-end-Projects

### Screenshots 📷

 N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- GitHub Profile Link :  [AmrutaJayanti](https://github.com/AmrutaJayanti)
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti Assigned to you. Keep it in `Vanilla-JS-Projects`
