### ISSUE TITLE
Project 📃:  Expense Tracker 

### ISSUE THREAD

**Issue by Saimanjari777** [Avdhesh-Varshney/WebMasterLog#239]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Expense Tracker
:red_circle: **Aim** : We can add or delete the expenses and get the total amount spent
:red_circle: **Tech Stack Used** :  HTML, CSS, JS
:red_circle: **Category** :   Vanilla-JS-Projects

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130165687/3d79ce8f-30cb-4a3a-a930-d1efde0fafbb)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Sai Manjari
- GitHub Profile Link : https://github.com/Saimanjari777
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.) GSSoC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Saimanjari777 go ahead.
