### ISSUE TITLE
Joke Telling Website using Vanilla JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#24]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Joke Telling website
:red_circle: **Aim** : A website which can provide users jokes according to their interests.
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AftabMankapure** [comment]
assign me under JWOC

![joke](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/125949765/6df0eda9-4451-43c5-aac6-9c4214d2af07)

what kind of project you want in this repo
Create some issue related to Vanilla-JS

**Comment by Avdhesh-Varshney** [comment]
@AftabMankapure Assigned to you. Follow the contributing guidelines.
Any innovative project but neither games nor calculators. 
Even you can create same project which is present in other tech stack and contribute it another tech stack by creating it that techs.
