### ISSUE TITLE
Fix for MOBILE screen

### ISSUE THREAD

**Issue by Utsavladia** [Avdhesh-Varshney/WebMasterLog#240]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :WebMastarLog 
:red_circle: **Enhancement Aim** : Make responsive for mobile screen
:red_circle: **Category** :  CSS 
:red_circle: **Changes** : Fix card to be fit for mobile screen, fix padding and margin according to mobile screen.

It should be fixed to improve the user experience on all devices.
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124615886/c6976331-c0fb-4abc-a9bd-f409c506d3a7)

i would love to contribute to this 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Utsav Ladia
- GitHub Profile Link : https://github.com/utsavladia
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Utsavladia fill the issue template. It is mandatory and join the project discord server.

**Comment by Utsavladia** [comment]
@Avdhesh-Varshney  sure, I have filled the issue template.

**Comment by Avdhesh-Varshney** [comment]
@Utsavladia go ahead.
