### ISSUE TITLE
[Feature] : Add `Dark` & `Light` mode

### ISSUE THREAD

**Issue by sivaprasath2004** [Avdhesh-Varshney/WebMasterLog#241]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Mode Change
:red_circle: **Aim** : Change User perference color mode
:red_circle: **Tech Stack Used** :  CSS, React, Vite
:red_circle: **Category** :  Hole project Mode issue

### Screenshots 📷

- **Expected Behaviour**
![Screenshot from 2024-06-04 20-30-55](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/121082414/892422f0-f884-4bc2-8bbd-53d16d7baa83)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sivaprasath
- GitHub Profile Link : [Sivaprasath2004]( https://github.com/sivaprasath2004)
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@sivaprasath2004 go ahead.
