### ISSUE TITLE
Project 📃: Morse code generator

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#243]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Morse Code Generator
:red_circle: **Aim** : Takes the user input and generates the morsecode
:red_circle: **Tech Stack Used** :  HTML, CSS, JS
:red_circle: **Category** :   Vanilla-JS-Projects

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- GitHub Profile Link :  [AmrutaJayanti](https://github.com/AmrutaJayanti)
- What is your participant role?  GSSOC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti project already present and don't do spam of the issues. It will debarred you from the program.
Follow the guidelines carefully.

**Comment by AmrutaJayanti** [comment]
@Avdhesh-Varshney Its not any action of spam .Sorry for the inconvenience . I dint check for this project in the repo so i dint know
