### ISSUE TITLE
Bug 🐛:  The side menu gets covered by page item when a webpage opens

### ISSUE THREAD

**Issue by techy4shri** [Avdhesh-Varshney/WebMasterLog#246]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Adjusting the overlapping issue in a web page and side menu
:red_circle: **Bug** :  Front End, React and Vanilla JS page items overlaps the side menu
:red_circle: **Category** :   Category of the project: CSS, Front-end,React, JavaScript
:red_circle: **Changes** :   We need to fix/adjust the margins and paddings of the sidebar and the webpage, adjusting Z-index 
 and positioning of css.  Z-index can help with the overlapping and I can go through the css files to see which oart is causing the overlapping.

### Screenshots 📷
![Screenshot 2024-06-05 222623 edit](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/db94fa90-16c4-4329-9e47-b8072bbded45)
![Screenshot 2024-06-05 222623](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/6d029268-8da3-40f1-b899-e8882c7ea1f9)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/896f31ba-f1c3-45c2-a3c9-ed869609af0c)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/c149024c-1d1e-4228-9348-886f6a61c380)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  GARIMA
- GitHub Profile Link : https://github.com/techy4shri
- What is your participant role?, GSSOC contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@techy4shri Assigned to you.
