### ISSUE TITLE
Project 📃: Blood Alcohol Content (BAC) Calculator JS Project

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#247]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : BAC - Calculator
:red_circle: **Aim** :The calculator will estimate the BAC based on the number of drinks, weight, gender, and time since the last drink.
:red_circle: **Tech Stack Used** :  HTML, CSS, JS
:red_circle: **Category** :   Vanilla-JS-Projects

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- GitHub Profile Link : [AmrutaJayanti](https://github.com/AmrutaJayanti)
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti calculators are not allowed.
