### ISSUE TITLE
Project 📃: Spotify Clone

### ISSUE THREAD

**Issue by chaanakyaaM** [Avdhesh-Varshney/WebMasterLog#252]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Spotify Clone
:red_circle: **Aim** : To create a Spotify interface clone
:red_circle: **Tech Stack Used** : HTML, CSS
:red_circle: **Category** :  Front-End Project

### Screenshots 📷

![Screenshot (191)](https://github.com/chaanakyaaM/Spotify-UI-clone/assets/131477601/934db405-eb72-4600-8712-bcbbf86247fd)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chaanakyaa Milkuri
- GitHub Profile Link : https://github.com/chaanakyaaM
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
 GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@chaanakyaaM go ahead.
