### ISSUE TITLE
Enhancement 🧑‍💻: 

### ISSUE THREAD

**Issue by NalinDalal** [Avdhesh-Varshney/WebMasterLog#253]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Home Page renders nothing
:red_circle: **Enhancement Aim** : There is literally nothing
:red_circle: **Category** : Angular, CSS, Front-end, NextJS, NodeJS, React, Vanilla, VueJS, etc.
:red_circle: **Changes** : 

### Screenshots 📷

<img width="1440" alt="Screenshot 2024-06-06 at 12 27 08" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/116961144/bb406f88-1084-4bda-886e-c39c485ae0f2">
Bro as u can see the home page literally renders nothing but an empty page
Assign under GSSOC

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nalin Dalal
- GitHub Profile Link : https://github.com/nalindalal
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)
- GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by techy4shri** [comment]
there's already an issue for this and it's assigned.

**Comment by NalinDalal** [comment]
so i can't work that means?

**Comment by techy4shri** [comment]
No. #140 is already assigned and someone is working on it. Check it.

**Comment by Avdhesh-Varshney** [comment]
@NalinDalal go ahead.

**Comment by NalinDalal** [comment]
once check issue 344

**Comment by Avdhesh-Varshney** [comment]
I have reviewed and left the comment. But still homepage is blank. Just addition of footer is not counted as as a contribution.
