### ISSUE TITLE
Enhancement 🧑‍💻: Adding border style to the sidebar menu and project cards to differentiate betweeen them

### ISSUE THREAD

**Issue by techy4shri** [Avdhesh-Varshney/WebMasterLog#254]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Clarity in Appearance
:red_circle: **Clear appearance and separation of elements on the page** :
:red_circle: **Category** :  CSS, Front-end, React
:red_circle: **Changes** : Currently everything is in dark colour, namely black. This makes it hard to tell where one element starts and other ends. Adding borders around the card elements and the sidebar will help make them stand out and appear clearly.
As there is a feature request in #241 for light and dark mode; I believe adding borders will make them clear because even in light mode, they are all the same colour.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/f4c11664-095a-4536-b080-d2bb8e0343b5)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : GARIMA
- GitHub Profile Link : https://github.com/techy4shri
- What is your participant role? GSSOC 2024 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@techy4shri pr will merge on good look
