### ISSUE TITLE
Project 📃: CSS Art Gallery

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#256]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : CSS Art Gallery
:red_circle: **Aim** : Create a page which combines all the art created by different artists using HTML and CSS and code can also be accessed
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** : Vanilla-JS-Projects

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Amruta Jayanti 
- GitHub Profile Link : [AmrutJayanti](https://github.com/AmrutaJayanti)
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
