### ISSUE TITLE
Project 📃: Add Quiz App using react JS

### ISSUE THREAD

**Issue by Saimanjari777** [Avdhesh-Varshney/WebMasterLog#262]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Quiz App
:red_circle: **Aim** : I would like to add quiz app where questions will be displayed and score for the test.
:red_circle: **Tech Stack Used** : React
:red_circle: **Category** :  React-JS-Projects

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130165687/56c71352-8a86-41f3-8beb-766d76629301)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sai Manjari
- GitHub Profile Link : https://github.com/Saimanjari777
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Saimanjari777 go ahead.
