### ISSUE TITLE
📃: Falling star catcher

### ISSUE THREAD

**Issue by Rohitha-pudu** [Avdhesh-Varshney/WebMasterLog#265]
:red_circle: **Falling stars catcher** : 
:red_circle: **It is a browser-based game where players control a basket to catch falling stars.as stars fall at random positions, and the player must swiftly move the basket to catch as many stars as possible within the given time limit.** : 
:red_circle: **JS** : 

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/116823590/01ba53f2-6dd5-4b9c-a9e6-6401650d14fb)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pudu Rohitha
- GSSOC

**Comment by Avdhesh-Varshney** [comment]
no games allowed.
