### ISSUE TITLE
📃: Social Media Analytics

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#266]
:red_circle: **Title** :  Social Media Analytics
:red_circle: **Aim** : Similar to Digital Wellbeing, but restricted to Social Media, Users can enter their screen time based on which chart would be generated.
:red_circle: **Tech Stack Used** :  HTML, CSS, JS, Chart.js

### Screenshots 📷

![Screenshot 2024-06-08 124730](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/2c3fcdcf-99d1-4b6a-bc5c-27de686b8832)
![Screenshot 2024-06-08 124743](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/f0c7b4d3-d8b6-4572-84e9-a1cabad89bb8)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti good project. go ahead.
