### ISSUE TITLE
📃: Headline-Hub :A Dynamic News Platform build using Node.js, Express, EJS 

### ISSUE THREAD

**Issue by 1simransaini** [Avdhesh-Varshney/WebMasterLog#267]
:red_circle: **Title** : Headline-Hub
:red_circle: **Aim** : Headline-Hub a dynamic and user-friendly news website build using Node.js, Express, and EJS, integrated with NewsAPI.org to fetch and display the latest news articles. 
:red_circle: **Tech Stack Used** :  Node.js, Express, EJS 

### Screenshots 📷

![Screenshot (14272)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/91106038/4985fe2e-4d28-47d9-bc7a-4ad288ccff49)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Saini
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@1simransaini go ahead.
