### ISSUE TITLE
📃: Age Calculator Project made in ReactJs and TailwindCSS. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Avdhesh-Varshney/WebMasterLog#268]
:red_circle: **Age Calculator** 
:red_circle: **To calculate the exact age in years, months and days based on the date of birth. Error handling is also done for invalid future dates entered by the user in any case.** 
:red_circle: **ReactJs, TailwindCSS** 

### Screenshots 📷

![age-calculator](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/123104247/35946941-f986-43df-9001-562522bcf2e0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parna Roy Chowdhury
- What is your participant role? GSSOC'24.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no calculator allowed. already mention in guidelines
