### ISSUE TITLE
📃: Movie Finder

### ISSUE THREAD

**Issue by Asymtode712** [Avdhesh-Varshney/WebMasterLog#269]
:red_circle: **Title** : Movie Finder
:red_circle: **Aim** :  Movie Finder is a website through which users can easily find every possible information regarding a particular movie.
:red_circle: **Tech Stack Used** :  HTML, CSS, Javascript 

### Screenshots 📷

Sample screenshot ( will be enhacing the UI further)

![MovieFinder](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/115717746/b1671fb1-da35-4954-8417-e614bf178bd7)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Siddheya Kulkarni
- What is your participant role? GSSoC Participant

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 go ahead.
