### ISSUE TITLE
🐛: fixing css in mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [Avdhesh-Varshney/WebMasterLog#270]
:red_circle: **FIXING CSS OF WEBSITE IN MOBILE VIEW ** :
:red_circle: **Bug** :
:red_circle: **Changes** :  
fixing css to make website work properly in mobile view 

### Screenshots 📷

![Screenshot_20240608_184353.jpg](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142989448/b74314b0-0b29-427d-a1f3-e2fb274ae173)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dhairya Gothi 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
already assigned #240
