### ISSUE TITLE
📃: VIRTUAL PIANO

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#271]
:red_circle: **Title** : Virtual Piano
:red_circle: **Aim** : virtual piano with an elegant UI, adjustable volumes, and a toggle button to hide keys for a cleaner interface.
:red_circle: **Tech Stack Used** : HTML , CSS , JAVASCRIPT

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.): GSSOC24
![Screenshot (24)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/d7cc89d0-48b8-4a18-bc99-8c082e0b5992)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
