### ISSUE TITLE
🧑‍💻:  Add the glowing cursor animation feature

### ISSUE THREAD

**Issue by namandude** [Avdhesh-Varshney/WebMasterLog#276]
:red_circle: **Title** : Adding glowing cursor 
:red_circle: **Enhancement Aim** : To give beautiful glowing effcet on moving in the screen
:red_circle: **Changes** :  Where ever the user takes their cursor the beautiful 3d bubble or something will glows off which make website looks more beautiful
 
Something like this :
![Screenshot 2024-06-08 025235](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118013565/b3b2cc0e-6560-4ee0-b72a-2e12916b5312)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Naman Parashar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)   :  UNDER GSSOC 24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@namandude go ahead.
