### ISSUE TITLE
🐛: Updating the CSS of Project cart sections

### ISSUE THREAD

**Issue by asthanegi14** [Avdhesh-Varshney/WebMasterLog#277]
:red_circle: **Title** : Updating the CSS of Project cart sections
:red_circle: **Bug** : The menu bar is hiding from the project section when it is open 
:red_circle: **Changes** :  The project cart section should squeeze when the menu cart is open. I saw another issue and her PR related to this bug but I am not satisfied with her solution and PR. We don't need to change anything in the sidebar but need to update the styling of the project cart section.

### Screenshots 📷

![Screenshot (990)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/93486108/23e6ec95-06d7-4477-b814-74da6ad19679)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Astha Negi
- What is your participant role? GSSOC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@asthanegi14 go ahead.
