### ISSUE TITLE
📃: Guess Country by Flag

### ISSUE THREAD

**Issue by Rags-Mishra** [Avdhesh-Varshney/WebMasterLog#278]
:red_circle: **Title** : Country-Guesser
:red_circle: **Aim** : It is a game where user guesses the country name by the flag displayed.
:red_circle: **Tech Stack Used** : HTML, CSS, Javascript

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ragini Mishra
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Rags-Mishra** [comment]
Kindly assign me this issue!

**Comment by Avdhesh-Varshney** [comment]
no games allowed.

**Comment by Rags-Mishra** [comment]
oh! Okay
