### ISSUE TITLE
📃: Resume Builder

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#279]
:red_circle: **Title** :  Resume Builder
:red_circle: **Aim** :  It prepares a resume based on user input and allows it to download
:red_circle: **Tech Stack Used** :  HTML CSS JS

### Screenshots 📷

![Screenshot 2024-06-09 181121](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/d9246731-19a8-42eb-85e3-81140a3d5c50)
![Screenshot 2024-06-09 182152](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/5388e081-2a6f-4bb0-94cd-2a655732621b)
![Screenshot 2024-06-09 184414](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/53c2c808-ab96-4fc0-bc91-2e3553eb4fac)
![Screenshot 2024-06-09 184423](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/ac8dae6a-3f90-4e01-9860-7da25f669ffc)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Amruta Jayanti
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AmrutaJayanti** [comment]
@Avdhesh-Varshney  Can you pleas assign me this task as `level-3`

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead and work on this css improvement, i will see and you can keep this project inside `Advanced` directory.
