### ISSUE TITLE
Netflix Clone Website

### ISSUE THREAD

**Issue by Sneha123-zudo** [Avdhesh-Varshney/WebMasterLog#28]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** :Netflix Clone Website
:red_circle: **Aim** :To clone the website of the [Netflix](https://www.netflix.com/in/)
:red_circle: **Tech Stack Used** : HTML, CSS
:red_circle: **Category** : Frontened Project
:red_circle:**Screenshot**:
<img width="946" alt="image" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/145490348/9318dce6-19c0-4dcf-b894-af4d64777426">

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sneha Mishra
- GitHub Profile Link : https://github.com/Sneha123-zudo
- What is your participant role? Please assign me this issue under JWOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Sneha123-zudo Assigned to you. Follow the contributing guidelines carefully.
