### ISSUE TITLE
📃: Add Meme Generator Project. I want to contribute under GSSOC'24. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Avdhesh-Varshney/WebMasterLog#281]
:red_circle: **Title** : Meme Generator 
:red_circle: **Aim** : To add a project under the Javascript section.
:red_circle: **Tech Stack Used** : Html, CSS and Js.

### Screenshots 📷
![Screenshot_20240607-192833_Samsung Internet.jpg](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/123104247/f16458b9-34aa-4e1b-b99d-e0aa53dc9e76)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parna Roy Chowdhury 
- What is your participant role? GSSOC'24.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ParnaRoyChowdhury777 go ahead.
