### ISSUE TITLE
📃: Add an API Fetching based project 

### ISSUE THREAD

**Issue by komal-agarwal5** [Avdhesh-Varshney/WebMasterLog#283]
:red_circle: **Title** : Add a Currency Converter Project 
:red_circle: **Aim** : It converts between latest rates of different currencies using api Fetching 
:red_circle: **Tech Stack Used** : React Js, Tailwind Css

### Screenshots 📷

![Screenshot_2024_0610_165018](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/122633300/4e2b6385-4c34-4b04-a08a-07870fea9db4)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Komal Agarwal 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC 24 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@komal-agarwal5 go ahead.
