### ISSUE TITLE
🐛: Improvements: Adding Visual Elements,Improve Navigation

### ISSUE THREAD

**Issue by SadiyaTahsin29** [Avdhesh-Varshney/WebMasterLog#285]
Background Image: A background image is applied to the entire page for a visually appealing backdrop.
Logo and Branding: A placeholder for the logo with the name "WEB MASTER LOG" is added in the navigation bar.
Highlighted Active Sections: The navigation bar provides hover effects, and tooltips are added to explain each icon.
Introduction Section: A hero section with a welcome message and a call-to-action button.

**Comment by SadiyaTahsin29** [comment]
I would like to do this  , I would  really do the need  full

**Comment by Avdhesh-Varshney** [comment]
@SadiyaTahsin29 the theme of website is dark mode, so i'm not thinking for a bg image. As there is a sidebar which is still not required for a logo branding and for highlight purpose, it is already present for active sections.

For further discussion, you can join the discord server for a faster communication purpose.

**Comment by SadiyaTahsin29** [comment]
It looked very empty
