### ISSUE TITLE
Temperature Converter project addition📃: 

### ISSUE THREAD

**Issue by SriramChowdaryMogalapu** [Avdhesh-Varshney/WebMasterLog#286]
:red_circle: **Title** : Temperature Converter
:red_circle: **Aim** : It can convert the unit of temperature from celsius to farenheit and kelvin and vice-versa.
:red_circle: **Tech Stack Used** : Front End

### Screenshots 📷

<img width="959" alt="image" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/103817400/488ba1b4-b309-4442-afae-6729227ddf3b">

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mogalapu Sriram Chowdary
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@SriramChowdaryMogalapu no calculators are allowed
