### ISSUE TITLE
📃:  Add a ReactJS Project

### ISSUE THREAD

**Issue by SriramChowdaryMogalapu** [Avdhesh-Varshney/WebMasterLog#287]
:red_circle: **Title** :  Image Carousel
:red_circle: **Aim** :  Allows user to add or remove images and then shows the images also has an API integration for chatbox.
:red_circle: **Tech Stack Used** : React JS

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/103817400/486e4e63-a66b-4024-8bdd-44319349b27a)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/103817400/c4ab127c-ef49-485d-9321-be69be1daba0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Mogalapu Sriram Chowdary
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@SriramChowdaryMogalapu go ahead.
