### ISSUE TITLE
📃:  Chess game for Frontend project

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#288]
:red_circle: **Title** : Add a Chess game frontend Project
:red_circle: **Aim** :  To provide help to the user for starting their frontend journey 
:red_circle: **Tech Stack Used** :  Html , css and javascript

### Screenshots 📷
![Screenshot 2024-06-10 203829](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/8f7d0438-c9c4-4928-8633-a89bd72362d2)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SonaliKumari2** [comment]
Assign me this issue.

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 i have already assigned you 1 issue and you have already raise 3 issues. Is your previous work is completed?
No games allowed.
