### ISSUE TITLE
🐛: Automatic Copyright.

### ISSUE THREAD

**Issue by tarushi29** [Avdhesh-Varshney/WebMasterLog#291]
:red_circle: **Title** : Automatic Copyright.
:red_circle: **Bug** : Not a dynamic code
:red_circle: **Changes** :   I want to add a dynamic code in the footer so that year changes automatically every year.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/128239884/06afc106-ec7d-4721-851b-32d96db9820a)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Tarushi Farainjiya
- What is your participant role?  GSSOC

***********************************************************************

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by Avdhesh-Varshney** [comment]
@tarushi29 go ahead.
