### ISSUE TITLE
🧑‍💻: Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [Avdhesh-Varshney/WebMasterLog#298]
:red_circle: **Preloader** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : I would add a preloader that will be rendered until the page is being loaded

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Jagpreet Singh Khurana
- What is your participant role?  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Jagpreet153 it's can be a good idea. But i have already a loading bar. So, you are implementing a loader just at the starting of the website only? For further communication, you can join the discord server.
