### ISSUE TITLE
📃: News-Website 

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#304]
:red_circle: **Title** : News-Website
:red_circle: **Aim** : Give Latest News
:red_circle: **Tech Stack Used** : HTML,BOOTSTRAP.CSS,JS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/e3dd82eb-8a69-41fa-a513-c3fe90796bbf)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Zala Bhavy
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead. But it should not be a similar project to that of #267 #50

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney My project is similar only UI is changed so i close this can you assign me #305
