### ISSUE TITLE
📃: Microsoft Website Clone

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#305]
:red_circle: **Title** : Microsoft Website Clone
:red_circle: **Aim** : Clone website frontend
:red_circle: **Tech Stack Used** : HTML , Tailwind CSS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/4b594954-fb22-4d40-a094-83d26d1c6f9c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Zala Bhavy
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
