### ISSUE TITLE
Adding FAQ section

### ISSUE THREAD

**Issue by mahek0620** [Avdhesh-Varshney/WebMasterLog#310]

**Comment by Avdhesh-Varshney** [comment]
@mahek0620 fill the issue template properly and don't raise too much issues.

**Comment by PranavKeshav24** [comment]
Description:
I have noticed that our website currently lacks a FAQ (Frequently Asked Questions) section. A well-structured FAQ section is crucial as it provides visitors with quick answers to common questions, improving their overall experience and reducing the need for direct customer support. This addition will help in addressing common queries more efficiently.

Screenshots:
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127531721/7704cc07-8d00-41aa-9a71-a50d8e7002c8)

@Avdhesh-Varshney  Please assign this issue to me under GSSoC' 24. I would be very happy to work on it.

**Comment by Avdhesh-Varshney** [comment]
@mahek0620 are you willing to work on it or not?

**Comment by mahek0620** [comment]
@Avdhesh-Varshney Yes, I want to work on this

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney Yes, I want to work on this

feel your issue template properly and provide details
