### ISSUE TITLE
📃: Reddit UI Clone

### ISSUE THREAD

**Issue by chaanakyaaM** [Avdhesh-Varshney/WebMasterLog#312]
:red_circle: **Title** : Reddit UI Clone
:red_circle: **Aim** : To create a Reddit UI Clone using HTML and Vanilla CSS
:red_circle: **Tech Stack Used** : 

### Screenshots 📷

![Screenshot (1)](https://github.com/chaanakyaaM/Websites-UI-Clone/assets/131477601/2c8a2c3f-a7b5-4382-9480-d88cccea6b76)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Milkuri Chaanakyaa
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
 GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@chaanakyaaM go ahead.
