### ISSUE TITLE
📃: Phonepe landing page

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#314]
:red_circle: **Title** : Phonepe landing page
:red_circle: **Aim** : to create the replica of phonepe website
:red_circle: **Tech Stack Used** : HTMl,CSS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/f10b304a-94e3-41a1-a86f-9c2a3c56299c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Damini2004** [comment]
@Avdhesh-Varshney  assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 go ahead.
