### ISSUE TITLE
📃: Attendance Tracker Next.js Project

### ISSUE THREAD

**Issue by anisharma07** [Avdhesh-Varshney/WebMasterLog#317]
:red_circle: **Title** : Attendance Tracker
:red_circle: **Aim** : A mobile responsive website that keeps the attendence records of student for particular subjects/Class
:red_circle: **Tech Stack Used** :  Next.js, tailwind.css, mongoDb, google auth...

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anirudh Sharma
- What is your participant role? : GSSOC.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@anisharma07 go ahead.
