### ISSUE TITLE
🧑‍💻: Implementing Greeting on Issue Close

### ISSUE THREAD

**Issue by thevijayshankersharma** [Avdhesh-Varshney/WebMasterLog#318]
:red_circle: **Title**: Implementing Greeting on Issue Close

:red_circle: **Enhancement Aim**: 
The aim is to enhance user experience and foster a positive atmosphere within the project community by automatically greeting contributors when an issue is closed.

:red_circle: **Changes**:
- Implement a system to generate a predefined greeting message when an issue is closed.
- Customize the greeting message to include expressions of appreciation for the reporter's contribution, acknowledgment of the issue resolution, and encouragement for continued participation.

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name: Vijay Shanker Sharma
- What is your participant role? GSSOC and SSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open-source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
