### ISSUE TITLE
📃:  Text Translator

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#319]
:red_circle: **Title** :  Text Translator
:red_circle: **Aim** :  Translates the entered text into desired language. 
:red_circle: **Tech Stack Used** :  HTML CSS Bootstrap JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role?  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
