### ISSUE TITLE
Weather website using Next JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#32]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Weather website
:red_circle: **Aim** : Build a weather application using Next.js that fetches weather data from an API and displays it to the user.
:red_circle: **Tech Stack Used** : Next.js, React, API Integration
:red_circle: **Category** :  Next-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work on it under JWoC'24

**Comment by pulkit1417** [comment]
Pulkit Gupta
https://github.com/pulkit1417
Please assign me this issue I want to work on it under GSSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@pulkit1417 Assigned to you. Follow the contributing guidelines carefully.
