### ISSUE TITLE
📃: Text-to-Image Generator

### ISSUE THREAD

**Issue by Asymtode712** [Avdhesh-Varshney/WebMasterLog#323]
:red_circle: **Title** : Text-to-Image Generator
:red_circle: **Aim** :  To create an image generator which would generate image from input text with the use of API
:red_circle: **Tech Stack Used** :  HTML, CSS, Javascript

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Siddheya Kulkarni
- What is your participant role? GSSoC'24 contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Asymtode712 go ahead.
