### ISSUE TITLE
📃: Notes app - React.js + Firebase

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#324]
:red_circle: **Title** : Notes app
:red_circle: **Aim** : A user-friendly notes app enabling seamless note management functionalities by authentication, folder management, nested folders, text formatting, search functionality and responsive design.
Users can login and create account using either email/password or Google account.
:red_circle: **Tech Stack Used** : React .js for frontend and Firebase for backend

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/dda21ca0-23c8-4c60-861a-feddbcca4b34)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/52726fe8-9920-4a68-964a-0d96c46a3f2d)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/845473e9-36ce-43fb-b898-c74ac4792e04)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi Balasubramaniyam
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.): GSSOC'

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam go ahead.
