### ISSUE TITLE
📃: React.js form validation

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#325]
:red_circle: **Title** : Form validation
:red_circle: **Aim** : This is a registration form in react js without using external package or library. Fields are validated using React Hooks.
:red_circle: **Tech Stack Used** : React.js

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/d802ada9-3b2a-4491-8677-4c2ca75215b7)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi Balasubramaniyam
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.): GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by MicahBala** [comment]
> Thank you for creating this issue! We'll look into it as soon as possible. Your contributions are highly appreciated! 😊

Can I work on this issue? Create a React project in the Basics folder under the React project folder, and create the form with Validation using React Hook Forms.

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam go ahead. and 1 issue at a time
