### ISSUE TITLE
📃: React Code Editor

### ISSUE THREAD

**Issue by maradadivyasree020** [Avdhesh-Varshney/WebMasterLog#329]
:red_circle: **Code Editor** 
:red_circle: **To create a clone of code pen** 
:red_circle: **React , HTML, CSS** 

### Screenshots 📷

![Screenshot 2024-06-15 182133](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/132190190/0128e321-d3e8-437e-9096-954cb5372b83)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Marada Divya Sree
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@maradadivyasree020 go ahead.

**Comment by maradadivyasree020** [comment]
The data i'm adding is not getting updated in the database. Once see the screenshot. Please tell me how to resolve this.
![react json](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/132190190/3ba3e21e-87f7-41d9-a64f-dfa4b8ad608a)

**Comment by Avdhesh-Varshney** [comment]
> The data i'm adding is not getting updated in the react.json file. Once see the screenshot. Please tell me how to resolve this. ![react json](https://private-user-images.githubusercontent.com/132190190/340116804-3ba3e21e-87f7-41d9-a64f-dfa4b8ad608a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTg2OTcsIm5iZiI6MTcxODU1ODM5NywicGF0aCI6Ii8xMzIxOTAxOTAvMzQwMTE2ODA0LTNiYTNlMjFlLTg3ZjctNDFkOS1hNjRmLWRmYTRiOGFkNjA4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNzE5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzBkY2Q3ZTU3NTMxZThmOTExODMwODIxYWFlMTRlNDIwYmNhY2YxNTFjNGEzZDMzYjYyOTQ5N2FmMWVkMGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R-IXupJgpVh1RfwsShUKIQENvl06LufVmb63EkTg_-U) ![org react json](https://private-user-images.githubusercontent.com/132190190/340116888-fbb674c0-298b-4a39-8aae-c05dc5079e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NTg2OTcsIm5iZiI6MTcxODU1ODM5NywicGF0aCI6Ii8xMzIxOTAxOTAvMzQwMTE2ODg4LWZiYjY3NGMwLTI5OGItNGEzOS04YWFlLWMwNWRjNTA3OWU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxNzE5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGJlZGZjMjhkMDc2Nzk1ZDc0MjgyMDBkODRlNjRhM2UxYjhkNmUwNWEwZWY3OTUwNTI5MWRiMDllNTYyYzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oWBVfVrp0Vpj0TlnzZ3-YYZiRmF8lE89Z3LpVpBS-vM)

You have updated there, what's the problem?

**Comment by maradadivyasree020** [comment]
Did you see the first photo it's not present right only in the json file it's there
![react json](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/132190190/5db87941-da6a-4d92-8b04-2f4c4823386a)
once see my "code editor" is not getting updated. Hence it's not showing me in the main website also.

**Comment by Avdhesh-Varshney** [comment]
@maradadivyasree020 when i will merge your pr, it will see in this raw file. So, feel free to raise the pr. Afterwards, i will correct you.

**Comment by maradadivyasree020** [comment]
ok thanks i will raise the pr
