### ISSUE TITLE
📃: Recipe finding website

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#330]
:red_circle: **Title** : Recipe finding website 
:red_circle: **Aim** : Make a basic website for finding recipe for different dishes using the edaman api
:red_circle: **Tech Stack Used** :  Html, Css, Javascript, edamam api 

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/1f31b405-8dd3-4011-9212-0318b5c536eb)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/211b3245-fc2b-4a2f-b2a7-1b1d0f10c55b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Bhaumik 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik already present in the repository [link](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Advanced/Recipe-Finder)
