### ISSUE TITLE
🧑‍💻: Add Scroll to up button

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#334]
:red_circle: **Title** : Add Scroll to up button ( using react)
:red_circle: **Enhancement Aim** : Implement a "Back to Top" button that allows users to smoothly scroll back to the top of the page when clicked.
:red_circle: **Changes** : 
- Add a "Back to Top" button component.
- Implement smooth scrolling functionality.
- Conditionally render the button based on the scroll position.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mankala Vaishnavi
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)gssoc24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshika14528** [comment]
Can I work on this issue
Full Name: Anshika

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
