### ISSUE TITLE
📃: Days between two Dates:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#338]
:red_circle: **Title** : Days between two Dates:
:red_circle: **Aim** : To find no. of days between two different dates 
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC Contibutor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
