### ISSUE TITLE
📃: Add react-movies-app

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#343]
:red_circle: **Title** : Movie-Land
:red_circle: **Aim** : I want to add a projects that fetches movies from omdapi
:red_circle: **Tech Stack Used** : REACTJS

### Screenshots 📷

![Screenshot (35)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/6c86872c-8887-45b2-8a90-9871192af941)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)gssoc24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
