### ISSUE TITLE
📃: Interactive Periodic Table

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#346]
:red_circle: **Title** :  Interactive Periodic Table
:red_circle: **Aim** :  Remember 11th class Chemistry, Periodic Table . Interative Periodic table helps you to get details of the elements with a click. 
:red_circle: **Tech Stack Used** : HTML CSS JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
