### ISSUE TITLE
📃: Password Strength Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#347]
:red_circle: **Title** : Password Strength Checker
:red_circle: **Aim** : To check if strength of password is good or not
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vansh-sardana** [comment]
Hi @Anshika14528 , I would like to work on this issue. (GSSOC'24: Contributor)

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir , i have completed my previous issue can you please assign me this issue?

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
