### ISSUE TITLE
📃: Facebook Login Clone with full responsiveness.

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#352]
:red_circle: **Title** : Facebook Login Clone
:red_circle: **Aim** : Add Facebook Login Clone 
:red_circle: **Tech Stack Used** : HTML , TAILWIND CSS.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/04e5931e-b90d-487c-a60c-ab834dbec58c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead.
