### ISSUE TITLE
📃: Add Drag and Drop Project Using Vanilla Js

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#353]
:red_circle: **Title** : Drag and Drop 
:red_circle: **Aim** : Make Drag and Drop Project use in many website.
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/6e4fea2c-7599-46e5-a265-299276db2d0a)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this issue !

**Comment by zalabhavy** [comment]
@Aashi19234 Can you please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy can you elaborate the idea of the project?

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney 
Any website which have to take file as input that gives up option of drag and drop this is use of that how you can drag and drop items from left box to right box and right box to left box.
It's look simple but it is written in hard java-script which is hard to understand for beginers.

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy go ahead
