### ISSUE TITLE
📃: Blogging platform API - Node.js

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#354]
:red_circle: **Title** : Blogging platform
:red_circle: **Aim** : 
- The backend infrastructure for  blogging platform, using Node.js, Express.js, and MongoDB, facilitating seamless management of user and admin roles with role-based authentication.

- Robust user authentication functionalities with JWT, including sign-in and sign-up features, ensuring secure access for both users and administrators.

- Blogs management features, enabling users to create, edit, and delete blog posts.

- Likes and comments management capabilities, enhancing user engagement and interaction within the platform.

- Integrated tag-based search functionality, allowing users to easily discover relevant blogs by tags.

- Tag management, user management functionalities for administrators, enabling CRUD operations for tags, ensuring flexible and dynamic content categorization.

:red_circle: **Tech Stack Used** : Node.js, Express.js, MongoDB JWT

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi Balasubramaniyam
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam if this is similar to #15 , mention there by closing it and before raising any issue check whether it's already present or not?

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam if this is similar to #15 , mention there by closing it and before raising any issue check whether it's already present or not?

Yeah, in that issue, no one was assigned. That's why I created a new issue.

**Comment by Avdhesh-Varshney** [comment]
> > @DharshiBalasubramaniyam if this is similar to #15 , mention there by closing it and before raising any issue check whether it's already present or not?
> 
> Yeah, in that issue, no one was assigned. That's why I created a new issue.

@DharshiBalasubramaniyam mention me on that issue. And any issue with `Up-for-Grabs ✋` is available to all contributors. I've not assigned to them as they are already having other tasks in repo at that time.

**Comment by DharshiBalasubramaniyam** [comment]
> > > @DharshiBalasubramaniyam if this is similar to #15 , mention there by closing it and before raising any issue check whether it's already present or not?
> > 
> > 
> > Yeah, in that issue, no one was assigned. That's why I created a new issue.
> 
> @DharshiBalasubramaniyam mention me on that issue. And any issue with `Up-for-Grabs ✋` is available to all contributors. I've not assigned to them as they are already having other tasks in repo at that time.

Okay, Got it.
