### ISSUE TITLE
📃: Anagram Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#358]
:red_circle: **Title** : Anagram Checker
:red_circle: **Aim** : used to check for 2 strings whether one string can be rearranged to get another string and vice versa
for example:
string 1:silent
string 2:listen
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role?GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by adisuyash** [comment]
Hey, @Anshika14528 assigned the issue to you. Go ahead :fire:
