### ISSUE TITLE
📃: E commerce platform API - node.js

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#360]
:red_circle: **Title** : E commerce platform 
:red_circle: **Aim** : 
1. secure authentication and authorization functionalities using  JWT. Integrated email verification during sign-up.
2. users can search and browse products, manage wishlists, shopping carts and orders.
3. admin functionalities for operations on users, categories, products and orders. 

:red_circle: **Tech Stack Used** : Node.js, Express.js, MongoDB, JWT

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi Balasubramaniyam
- What is your participant role? GSSOC 24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by DharshiBalasubramaniyam** [comment]
@Avdhesh-Varshney, I would like to work on this issue, can you please assign this issue to me?

**Comment by DharshiBalasubramaniyam** [comment]
@Avdhesh-Varshney, Kindly assign this issue to me.

**Comment by DharshiBalasubramaniyam** [comment]
@Avdhesh-Varshney Kindly assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam go ahead.
