### ISSUE TITLE
🧑‍💻: Add Google translate feature

### ISSUE THREAD

**Issue by MuraliDharan7** [Avdhesh-Varshney/WebMasterLog#362]
:red_circle: **Title** : Google Translator
:red_circle: **Enhancement Aim** : It will translate the whole page.
:red_circle: **Changes** : Changes the language

### Screenshots 📷

![GoogleTranslate](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130668745/a65fc9d7-1d87-49de-8135-02fc24933493)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MuraliDharan N G
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSoC'24 Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@MuraliDharan7 go ahead.
