### ISSUE TITLE
📃: Add KFC Clone project

### ISSUE THREAD

**Issue by MuraliDharan7** [Avdhesh-Varshney/WebMasterLog#363]
:red_circle: **Title** : KFC Clone frontend
:red_circle: **Aim** : website for ordering food
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MuraliDharan N G
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@MuraliDharan7 1 issue at a time and mention the link of website page which you want to clone?

**Comment by MuraliDharan7** [comment]
> @MuraliDharan7 1 issue at a time and mention the link of website page which you want to clone?

https://github.com/divyam751/KFC-Clone

**Comment by Avdhesh-Varshney** [comment]
@MuraliDharan7 not required. Work on your own project not copy from others.
