### ISSUE TITLE
🧑‍💻: Adding more social media icons

### ISSUE THREAD

**Issue by jayanththalla** [Avdhesh-Varshney/WebMasterLog#364]
:red_circle: Social media
:red_circle: Add more social media icons
:red_circle: **Changes** : there are 2 icons only i want to add the discord icons and other

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  T Jayanth
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@jayanththalla go ahead.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Avdhesh-Varshney
