### ISSUE TITLE
📃: Rock paper Scissors Game

### ISSUE THREAD

**Issue by GAVINESHWAR** [Avdhesh-Varshney/WebMasterLog#367]
:red_circle: **Title** : Rock Paper Scissors Game
:red_circle: **Aim** : To understand JavaScript fundamentals
:red_circle: **Tech Stack Used** : Html, CSS and JavaScript

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/345ee20d-39e0-49ac-a4be-3433e320b9bc)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : G AVINESHWAR
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no games allowed
