### ISSUE TITLE
🧑‍💻: Enhance the E-Mail section with borders using css.

### ISSUE THREAD

**Issue by agrwal697** [Avdhesh-Varshney/WebMasterLog#368]
:red_circle: Enhance the E-Mail section with borders using css.
:red_circle: I think if the E-Mail section had border-bottom in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC'24 

### Screenshots 📷
Before:
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/128716726/dc14ea81-4f03-48f8-83c4-c5550339be29)

After:
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/128716726/9a3c7ef5-3a30-430e-8271-a27492239739)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nandini Agrawal
- What is your participant role?  GSSOC'24.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
i don't think, addition of 1 line makes the ui looks good 🙂

**Comment by agrwal697** [comment]
Sir, but I think little little changes can make more and more difference in UI of website.
Please Assign me this issue with the level and label of GSSOC'24

**Comment by Avdhesh-Varshney** [comment]
@agrwal697 ok go ahead.
