### ISSUE TITLE
📃:  Pangram Checker Game

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#370]
:red_circle: **Title** :  Pangram Checker Game
:red_circle: **Aim** :  Check whether it is pangram or not
:red_circle: **Tech Stack Used** :  HTML , CSS

### Screenshots 📷
![Screenshot 2024-06-20 114723](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/d9049050-caca-437f-9f87-d46c360be4c6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no games allowed
