### ISSUE TITLE
📃: Leap Year Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#372]
:red_circle: **Title** : Leap Year Checker:
:red_circle: **Aim** : It check if a year is leap year or not.
:red_circle: **Tech Stack Used** : HTML , CSS, Js

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
