### ISSUE TITLE
📃:  Google Drive Clone

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#373]
:red_circle: **Title** :  Google Drive Clone
:red_circle: **Aim** :  clone
:red_circle: **Tech Stack Used** :  html css js

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 go ahead.
