### ISSUE TITLE
📃: Search-from-here project using html,css,js

### ISSUE THREAD

**Issue by srinidhifd** [Avdhesh-Varshney/WebMasterLog#374]
:red_circle: **Title** : Search-From-Here
:red_circle: **Aim** : This website allows users to search for products from a variety of popular websites,
including Amazon, Flipkart, Google, and YouTube, all in one place.
:red_circle: **Tech Stack Used** : Html,CSS,JS

### Screenshots 📷

![search-from-here](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/93462562/8f6744a1-9289-4f10-b31d-4f52f7b59fe7)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Srinidhi Kulkarni
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@srinidhifd go ahead.

**Comment by Avdhesh-Varshney** [comment]
What's the update? 
Please fill this survey form: https://forms.gle/Wvsp9N8TDF1WPStq9

**Comment by JomanaMahmoud** [comment]
please assign me this issue i can do it, i cam contributing for hacktoberfest and gssoc-ext
