### ISSUE TITLE
🐛:  Sidebar does not expand on search icon click

### ISSUE THREAD

**Issue by PranavKeshav24** [Avdhesh-Varshney/WebMasterLog#376]
:red_circle: **Title** : Sidebar does not expand on search icon click
:red_circle: **Bug** : When the search icon is clicked, the sidebar does not expand as expected. This issue prevents users from accessing the search functionality and hampers user experience.
:red_circle: **Changes** :  The sidebar component needs to be altered so that the sidebar is expanded when the search icon is clicked. 

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127531721/17c3905c-37d5-49f9-ba17-a01fc72ed18d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranav Keshav
- What is your participant role? I am a contributor at GSSoC' 24.

Please assign this issue to me. I would be very happy to work on it.
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@PranavKeshav24 go ahead.
