### ISSUE TITLE
🐛: Sidebar not sticky in light theme.

### ISSUE THREAD

**Issue by PranavKeshav24** [Avdhesh-Varshney/WebMasterLog#377]
:red_circle: **Title** : Sidebar not sticky in light theme.
:red_circle: **Bug** : The sidebar fails to remain sticky when the light theme is enabled. This issue causes the sidebar to scroll with the page content instead of remaining fixed in position, which affects the user experience by making the sidebar inaccessible when the user scrolls down.
:red_circle: **Changes** :  The sidebar component styles need to be updated so that the sidebar remains sticky in the light theme as well.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/127531721/acee39bf-629c-4394-b8f9-571424aa47d0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pranav Keshav
- What is your participant role?  I am a contributor at GSSoC' 24.

Please assign this issue to me. I would be very happy to work on it.
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
now it works fine
