### ISSUE TITLE
📃: Sanke game using Vanilla JS

### ISSUE THREAD

**Issue by PankajR007** [Avdhesh-Varshney/WebMasterLog#378]
:red_circle: **Title** : Snake Game 
:red_circle: **Aim** : Snake Game which is similar to the game played on the keypad phone, please refer the image.
:red_circle: **Tech Stack Used** :  HTML CSS Vanilla JS

### Screenshots 📷

![Screenshot (55)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130495518/ffff1acf-b586-41c4-a958-58e4b384c61f)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Pankaj Rastapur
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
 GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no games allowed.
