### ISSUE TITLE
📃:  add Flipkart Clone

### ISSUE THREAD

**Issue by anagha-chaudhari** [Avdhesh-Varshney/WebMasterLog#380]
:red_circle: **Title** : a Flipkart Clone
:red_circle: **Aim** : 
:red_circle: **Tech Stack Used** : Html, CSS and Js

### Screenshots 📷
Ref. flipkart: 
![flipkart](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143149376/58fc66ee-4259-470f-b2bc-8481434847ad)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anagha Chaudhari
- What is your participant role? : GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@anagha-chaudhari go ahead.
