### ISSUE TITLE
📃: Add CodeEditor(HTML,CSS,JS)

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#385]
:red_circle: **Title** : CodeEditor
:red_circle: **Aim** : I want to add code editor 
:red_circle: **Tech Stack Used** : HTML,CSS,JS

### Screenshots 📷

![Screenshot (9)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/bee70341-dbf7-4cd7-9a2a-897fcd34e490)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
