### ISSUE TITLE
🧑‍💻: Want to add glowing cursor into the project

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#386]
:red_circle: **Title** :Glowing Cursor
:red_circle: **Enhancement Aim** :To add glowing cursor
:red_circle: **Changes** : 

### Screenshots 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/7c06139f-082e-4fb6-af8e-4c8c9464874d

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Mhmd-Ashif** [comment]
does second criteria is **compulsory**

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
