### ISSUE TITLE
📃: Addition of Recipe Finder App

### ISSUE THREAD

**Issue by shreyash3087** [Avdhesh-Varshney/WebMasterLog#387]
:red_circle: **Title** : Add Recipe Finder App
:red_circle: **Aim** : User can find the recipe for any dish within seconds
:red_circle: **Tech Stack Used** : ReactJs,Edmam API

### Video 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/72603662/afd8c028-fb65-430e-a115-0e81cdcbc257

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shreyash Srivastava
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@shreyash3087 already present in the repository [link](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Advanced/Recipe-Finder).
