### ISSUE TITLE
🐛: Search Functionality not working

### ISSUE THREAD

**Issue by Vaishali-ajmera** [Avdhesh-Varshney/WebMasterLog#388]
:red_circle: **Title** :  Fix Search Functionality
:red_circle: **Bug** :  The search functionality is not working. When a user tries to search for items, the system does not return any results or displays incorrect results.
:red_circle: **Changes** :   Capturing search input and applying logic using JavaScript.

### Screenshots 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/83902558/c469e49d-a58d-4593-9312-e3b7463b776b

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Vaishali Ajmera
- GitHub Profile Link : https://github.com/Vaishali-ajmera
- What is your participant role?  GSSOC contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Vaishali-ajmera** [comment]
Thank you for the opportunity. Please add gssoc and label tag to this issue

**Comment by Avdhesh-Varshney** [comment]
@Vaishali-ajmera without assigning the issue, never raise the pr.
