### ISSUE TITLE
QuickNotes Website using Angular JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#39]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : QuickNotes
:red_circle: **Aim** : Build a minimalist note-taking application.
:red_circle: **Tech Stack Used** : AngularJS, HTML, CSS, LocalStorage
:red_circle: **Category** :  Angular-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by itsmeabhishek03** [comment]
Full Name - Abhishek Mishra
Github Link - https://github.com/itsmeabhishek03
Participant Role - JWOC

**Comment by osmoosiis** [comment]
• Full name : Ishavdeep Kaur 

• GitHub Profile Link : 

https://github.com/osmoosiis

Kindly assign me this under GSSOC'24

**Comment by osmoosiis** [comment]
Full name : Ishavdeep Kaur

GitHub Profile Link : https://github.com/osmoosiis

kindly assign me this for  GSOC'24
p.s I have sem finals rn and to top it of i am kinda begineer so it may take me a bit to complete .
Looking forward to contributing .

**Comment by Avdhesh-Varshney** [comment]
@osmoosiis No problem. Program goes upto August. But it will be GSSOC'24? Right.

**Comment by osmoosiis** [comment]
> @osmoosiis No problem. Program goes upto August. But it will be GSSOC'24? Right.

Yeah

**Comment by Avdhesh-Varshney** [comment]
@osmoosiis Assigned to you. Follow the contributing guidelines carefully.

**Comment by osmoosiis** [comment]
> @osmoosiis Assigned to you. Follow the contributing guidelines carefully.

Will keep that in mind ty
