### ISSUE TITLE
📃: Prime Number Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#397]
:red_circle: **Title** : Prime Number Checker:
:red_circle: **Aim** : It will help us to check if given number is prime or not.
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
