### ISSUE TITLE
📃: Fitness website

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#400]
:red_circle: **Title** : Fitness Website
:red_circle: **Aim** : A fitness website that allows users to log their workouts, set fitness goals, and track their progress .
:red_circle: **Tech Stack Used** :  Html css and javascript 

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
