### ISSUE TITLE
📃: Add Pangram Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#406]
:red_circle: **Title** : Add Pangram Checker:
:red_circle: **Aim** : A pangram is a sentence where every letter of the English alphabet appears at least once.Pangram Checker will help us to check if given sentence is pangram or not.
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir , please assign me this issue I have completed the previous one.

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir , i want to add workflow for autocomment on pr merge can I raise issue for that?

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney sir , i want to add workflow for autocomment on pr merge can I raise issue for that?

No, not required.

**Comment by Anshika14528** [comment]
Ok
