### ISSUE TITLE
📃:  SpaceX Clone

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#407]
:red_circle: **Title** : SpaceX
:red_circle: **Aim** :  I would like create a clone of website SpaceX
:red_circle: **Tech Stack Used** :  HTML CSS 

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
