### ISSUE TITLE
🧑‍💻: UI improvement for Home page

### ISSUE THREAD

**Issue by sanskritisahu21** [Avdhesh-Varshney/WebMasterLog#409]
We are not getting anything while clicking on home page.

![Screenshot 2024-06-26 223103](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/134837879/4a42c664-5cb7-4eff-9526-8893c83b246c)

**Comment by Avdhesh-Varshney** [comment]
@sanskritisahu21 go ahead

**Comment by sanskritisahu21** [comment]
ok! Thankyou I will join.
