### ISSUE TITLE
📃: ANALOG CLOCK

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#411]
:red_circle: **Title** : ANALOG CLOCK
:red_circle: **Aim** : To add Analog clock
:red_circle: **Tech Stack Used** : HTML,CSS,JS

### Screenshots 📷

![Screenshot (18)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/77c80685-7bde-463d-a8dd-d32bb4daf1a5)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 go ahead.
