### ISSUE TITLE
🧑‍💻:  Adding proper comments 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#417]
:red_circle: **Title** : Adding proper comments
:red_circle: **Enhancement Aim** :  To make website mode understandable and readable 
:red_circle: **Changes** : I want to add the proper comments to every line so that user can understand the current use of the code and will do their work accordingly .

### Screenshots 📷
![Screenshot 2024-06-27 221434](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/98b31387-100b-423e-a3b7-a355a05e9e4c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
