### ISSUE TITLE
🧑‍💻:  Adding BEM Naming convention to all classes 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#418]
:red_circle: **Title** : Adding BEM Naming convention 
:red_circle: **Enhancement Aim** : It will help new users to understand the use of the css and their block elements in html 
:red_circle: **Changes** : I just want to change the classes names in both css and html or js file .

### Screenshots 📷
![Screenshot 2024-06-27 220731](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/52c5a305-3c8d-45b8-a4f4-8865425e8e59)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 can you show me, any such changes in the repository?

**Comment by Ayushmaanagarwal1211** [comment]
yes like you can see that in your mainpage.jsx
![Screenshot 2024-06-29 132453](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/6a10a64f-2dee-43e3-a627-309b56b4f934)

the classes name has been written but i will change these classes name to like 
<div className="page-main-container">
  <h1 className='page-main-container__header text-end my-2 mx-2'>{`${getName(category)} Projects`}</h1>
  <div className="page-main-container__button-group button-group justify-content-end my-2 mx-3">
    <button
      type="button"
      className={`button-group__button btn btn${tag !== 'Basic' ? '-outline' : ''}-success mx-1`}
      onClick={() => handleTagClick('Basic')}
    >
      Easy
    </button>
    <button
      type="button"
      className={`button-group__button btn btn${tag !== 'Intermediate' ? '-outline' : ''}-warning mx-1`}
      onClick={() => handleTagClick('Intermediate')}
    >
      Medium
    </button>
    <button
      type="button"
      className={`button-group__button btn btn${tag !== 'Advanced' ? '-outline' : ''}-danger mx-1`}
      onClick={() => handleTagClick('Advanced')}
    >
      Hard
    </button>
    <button
      type="button"
      className={`button-group__button btn btn${tag !== 'All' ? '-outline' : ''}-info mx-1`}
      onClick={() => handleTagClick('All')}
    >
      All
    </button>
  </div>

  <div className="page-main-container__dropdown dropdown">
    
You can see that you can easily understand the elements used for by directly seeing the classes and i also change its corresponsding css so that designing doesn't changes .

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 no leave it for the beginner to contribute in the enhancement of this project.
Not required.
