### ISSUE TITLE
📃:  Want to add the Aqua sort and Alient invaders project

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#420]
:red_circle: **Title** :  Adding Aqua sort and Alient invaders project
:red_circle: **Aim** :  To give resource to the new users so that they can take help of it 
:red_circle: **Tech Stack Used** :  HTML, CSS and Javascript

### Screenshots 📷
![Screenshot 2024-06-28 092321](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/da3be90b-ca8f-4c4d-8368-7aa460d930ab)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no game additions.
