### ISSUE TITLE
🐛: Light mode bug

### ISSUE THREAD

**Issue by MuraliDharan7** [Avdhesh-Varshney/WebMasterLog#425]
:red_circle: **Title** : Scroll to top button is not visible in light mode
:red_circle: **Bug** : The scroll to top button is not visible in light mode, in front end section the scroll to top feature is not moving along with the move of the website.
:red_circle: **Changes** : The color for the light mode should be changed here.

### Screenshots 📷
1. Light mode issue:
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130668745/be1a9014-a886-443e-bc00-6656a4918880)

2. Front end section issue:
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130668745/29b62baf-e42c-47b6-8243-56286211752e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MuraliDharan
- What is your participant role? (Mention the Open Source Program name. :GSSOC

**Comment by Avdhesh-Varshney** [comment]
@MuraliDharan7 go ahead.

**Comment by Avdhesh-Varshney** [comment]
@MuraliDharan7 what's the update on this issue?

**Comment by Avdhesh-Varshney** [comment]
@gurramkarthiknetha At current, this is not a bug. This is a task to create a light mode for the website.

**Comment by gurramkarthiknetha** [comment]
*Subject:* Request for Deployment Authorization for Open-Source
Contribution on Vercel

Hello [Team Member’s Name / Avdhesh],

I hope this message finds you well. I’ve recently submitted a commit for
deployment as part of my open-source contributions to [Project Name]. Upon
attempting to deploy on Vercel, I encountered a prompt indicating that
authorization from a team member is required to proceed.

Could you please review and authorize this deployment at your convenience?
I believe the update will enhance [mention any key improvements, e.g.,
functionality, performance, or bug fixes].

Thank you for your time and support.

Best regards,
Karthik Netha
