### ISSUE TITLE
🧑‍💻:  Adding a fade up animation to the projects

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Avdhesh-Varshney/WebMasterLog#428]
:red_circle: **Title** : Adding up of fade up animation
:red_circle: **Enhancement Aim** : To make it more attractive 
:red_circle: **Changes** :  When user scrolls down or the when the card comes in user view port then it only pop ups with an animation 

### Screenshots 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/118350936/d71ad926-d10d-4aac-911b-f7693df4a33d

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ayushmaan Agarwal
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Ayushmaanagarwal1211 go ahead.
