### ISSUE TITLE
🐛:  The Dark Mode is Not Working After Refreshing 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Avdhesh-Varshney/WebMasterLog#429]
:red_circle: **Title** :  The Dark Mode is Not Working After Refreshing 
:red_circle: **Bug** :  The Dark Mode is Not Working After Refreshing When the dark mode is enabled on our website, it reverts back to light mode upon refreshing the page. This issue affects user experience as the preference for dark mode is not retained.
:red_circle: **Changes** :   
- The dark mode toggle is implemented using JavaScript and CSS.
- Ensure that the user's preference for dark mode is stored (e.g., using localStorage or cookies).
- Verify that the preference is correctly read and applied when the page is loaded.

### Screenshots 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/163530398/2f52a553-04db-401c-8134-30160d03b0fe

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Radhika Malpani
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.):  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@RadhikaMalpani1702 go ahead.
