### ISSUE TITLE
📃: Language Learning Website

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#431]
:red_circle: **Title** : Language Learning Website
:red_circle: **Aim** : Build a website that helps users learn a new language through interactive lessons, quizzes, and flashcards. Include features like progress tracking, daily goals, and a community forum.
:red_circle: **Tech Stack Used** : Html css javascript and vanilla js

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Bhaumik
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
