### ISSUE TITLE
📃: Add new Frontend Project iPhone 14 pro clone website

### ISSUE THREAD

**Issue by vansh-codes** [Avdhesh-Varshney/WebMasterLog#433]
:red_circle: **Title** : iPhoen 14 Pro Website Clone
:red_circle: **Aim** : To implement HTML CSS effectively to create clone of IPhone 14 pro clone
:red_circle: **Tech Stack Used** : HTML, CSS

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/c14caed2-2d79-47a6-882b-7b63712b45a5)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/a9459fa3-7d53-4d6b-9b91-f69cdf8046f9)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/6105925e-4cc2-48e3-893f-fa6263c1730e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vansh Chaurasiya
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSoC'24 Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@vansh-codes go ahead.
