### ISSUE TITLE
📃: 3D Solar System

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#435]
:red_circle: **Title** : 3D Solar System
:red_circle: **Aim** : Replicate the solar system
:red_circle: **Tech Stack Used** : HTML,CSS,JS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/ec17110f-dd1a-4527-9d4e-05cd4f7e3b89)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Damini2004 Don't raise more issues at a time. I've already warned you related to Issue guidelines.

**Comment by Damini2004** [comment]
@Avdhesh-Varshney sorry 
Its frontend project
