### ISSUE TITLE
📃: Add exciting OTP input React project

### ISSUE THREAD

**Issue by Utsavladia** [Avdhesh-Varshney/WebMasterLog#440]
:red_circle: **Title** :  OTP input React project
:red_circle: **Aim** : 
:red_circle: **Tech Stack Used** :  React

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124615886/47f8701b-f584-4c19-995a-2696bcbb6ee8)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Utsav Ladia
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Utsavladia go ahead. And do spam of issues.
