### ISSUE TITLE
📃:  Next.js Chess game

### ISSUE THREAD

**Issue by Utsavladia** [Avdhesh-Varshney/WebMasterLog#441]
:red_circle: **Title** :  Chess game
:red_circle: **Aim** : 
:red_circle: **Tech Stack Used** :  Next.js

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124615886/f32126e9-ca18-4f7b-a1f3-47b0ff649cea)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Utsav Ladia
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no games allowed.
