### ISSUE TITLE
🐛: Light mode: Sidebar menu & headings don't pin on scroll (dark mode only).

### ISSUE THREAD

**Issue by techy4shri** [Avdhesh-Varshney/WebMasterLog#445]
:red_circle: **Title** :  Functionality issue  in theme change on webapp related to heading and sidebar menu
:red_circle: **Bug** : In light mode, the sidebar menu and headings do not stay fixed at the top of the screen when you scroll down. This pinning functionality is only active when dark mode is enabled.
:red_circle: **Changes** :  Possible Cause: Light mode theme might lack pinning functionality due to CSS/JS specific to dark mode or a visual cue issue creating the illusion of unpinned menus.

Suggested Fix: Implement pinning behavior for the sidebar menu and headings in light mode to match dark mode functionality.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/0da9128d-dfa5-416e-94d2-ebc02e113ed2)

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/141991095/bed8a7ec-0a91-4428-9246-196b989fdf94

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Garima
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Priyanshudotdev** [comment]
Could you please let me know where I can find this code repository?

**Comment by techy4shri** [comment]
> Could you please let me know where I can find this code repository?

Just click on Avdhesh-Varshney/WebMasterLog at top left! This is the issues section.

**Comment by Priyanshudotdev** [comment]
I know but I want to solve the above issue, so where I can find the repo for this issue

**Comment by techy4shri** [comment]
> I know but I want to solve the above issue, so where I can find the repo for this issue

You've to raise an issue yourself to be assigned to it. I have raised this issue.

**Comment by Avdhesh-Varshney** [comment]
@techy4shri I've change the structure of the source code. Now, you should work on light mode of the website at now.
