### ISSUE TITLE
📃: To-Do Genie

### ISSUE THREAD

**Issue by EpicNesh26** [Avdhesh-Varshney/WebMasterLog#447]
:red_circle: **Title** : To-Do Genie
:red_circle: **Aim** : Designed with an intuitive interface, To-Do Genie ensures that your tasks are organized and accessible, all while maintaining a sleek and stylish appearance.
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷

![Screenshot 2024-06-29 053433](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130682376/bb628dfc-d1d0-4317-b921-fc78cac64d85)
![WhatsApp Image 2024-06-29 at 05 36 18_80309e8d](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130682376/9df551b9-d1e3-45d6-b6f2-b28175842d5b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nesh Soni
- What is your participant role? Independent Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@EpicNesh26 go ahead.
