### ISSUE TITLE
📃: Password Generator 

### ISSUE THREAD

**Issue by prachita0504** [Avdhesh-Varshney/WebMasterLog#449]
:red_circle: **Title** : Password Generator
:red_circle: **Aim** : 
:red_circle: **Tech Stack Used** : ReactJS

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@prachita0504 It's already present in react-js. If you would like to do enhancement in the project, mention me again.
