### ISSUE TITLE
📃:  Animated Tea Cup (CSS Art)

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#450]
:red_circle: **Title** :  Tea Cup
:red_circle: **Aim** :  Project is for beginners who are interested in CSS art to get started with it.
:red_circle: **Tech Stack Used** :  HTML CSS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
