### ISSUE TITLE
📃: Add Number to Binary Converter:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#451]
:red_circle: **Title** : Number to Binary Converter
:red_circle: **Aim** : It converts number to binary number.
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no calculator or convetor
