### ISSUE TITLE
📃: Add synonyms searcher

### ISSUE THREAD

**Issue by AnshikaAg03** [Avdhesh-Varshney/WebMasterLog#452]
:red_circle: **Synonyms Searcher** 
:red_circle: **To find the synonyms of a given word** 
:red_circle: **HTML,CSS and JAVASCRIPT** 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika Agarwal
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@AnshikaAg03 go ahead.
