### ISSUE TITLE
📃: Add the famous UNO game within Vanilla JS project following all the rules

### ISSUE THREAD

**Issue by debangi29** [Avdhesh-Varshney/WebMasterLog#454]
:red_circle: **UNO** : 
:red_circle: **Players can play UNO with the computer following the rules** : 
:red_circle: **HTML, CSS, Javascript for the customised rules** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Debangi Ghosh
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@debangi29 no games allowed.
