### ISSUE TITLE
🐛: Text not visible

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#462]
:red_circle: **Title** : Text not visible
:red_circle: **Bug** : Visibility
:red_circle: **Changes** :  Add black color to text

### Screenshots 📷

I think this mobile menu icon and text before that WebLogMaster color should be black so it is visible easily.

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/aab49d35-0326-47db-ab39-c33da41dc1b7)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

**Comment by Avdhesh-Varshney** [comment]
share the whole ss of mobile view and mark it using highlighter

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney 
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/126322584/02373a22-851c-4458-8f3f-e594f1a07a5b)

Red box part WebMasterLog text and mobile menu icons not visible.

**Comment by Avdhesh-Varshney** [comment]
no it's the problem of light mode is not working properly
