### ISSUE TITLE
📃:  GasGuys Home page clone 

### ISSUE THREAD

**Issue by GAVINESHWAR** [Avdhesh-Varshney/WebMasterLog#463]
:red_circle: **Title** : Gas Guys Home Page clone 
:red_circle: **Aim** : Home page User Interface
:red_circle: **Tech Stack Used** : HTML,CSS and JavaScript

It is an home page clone of GasGuys startup company, It has the features of fully responsive , navbar , scrollable gallery , hovering effects and more. 

### Screenshots 📷

![Screenshot 2024-07-04 193747](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/844ae1bb-b902-4b26-a8e8-8ca9bb2c0688)
![Screenshot 2024-07-04 193818](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/2fd30e41-67a1-4050-9f58-d6df0201eb19)
![Screenshot 2024-07-04 193828](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/054ab241-f3ed-42a1-805b-e29720ff0cb6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : G AVINESHWAR
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@Avdhesh-Varshney assign me this issue to make contribution to the project.

Thank you

**Comment by Avdhesh-Varshney** [comment]
@GAVINESHWAR go ahead.
