### ISSUE TITLE
📃: Age Calculator Project

### ISSUE THREAD

**Issue by GAVINESHWAR** [Avdhesh-Varshney/WebMasterLog#464]
:red_circle: **Title** : Age Calculator
:red_circle: **Aim** : Maths conecepts using in JS
:red_circle: **Tech Stack Used** : HTML,CSS and javaScript

The age calculator website accurately computes and displays your current age, providing a comprehensive breakdown in years, months, days, hours, minutes, and seconds. All you need to do is enter your date of birth, and the application will swiftly present the detailed age information. Stay informed and empowered with this intuitive age-tracking tool.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/cf961f64-24ad-4a4a-ba34-40682ba8ffef)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  G Avineshwar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@Avdhesh-Varshney , assign me this issue make contribution to the project.

Thank you

**Comment by Avdhesh-Varshney** [comment]
@GAVINESHWAR follow the guildeines properly before raising the issue.

No calculators accepted.
