### ISSUE TITLE
📃: Add Isogram Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#465]
:red_circle: **Title** : Isogram Checker
:red_circle: **Aim** : It checks if given string is isogram or not. An isogram is a word in which the letters occur an equal number of times.
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
