### ISSUE TITLE
📃:  Apna college clone webpage in frontend project

### ISSUE THREAD

**Issue by heli0707** [Avdhesh-Varshney/WebMasterLog#466]
:red_circle: **Title** : Apna college clone page 
:red_circle: **Aim** : 
- Break down the page into reusable components for better maintainability and scalability.
- Ensure consistency with colors, fonts, and spacing.
- manage routes for pages like "Home", "New Courses", "Log In", and "Sign Up".
- Implement forms for "Log In" and "Sign Up" with basic validation.

:red_circle: **Tech Stack Used** : HTML CSS JS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/f7b4baab-6503-4607-95d0-d80e0d64c2fc)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Heli Detroja
- What is your participant role? : GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@heli0707 go ahead.
