### ISSUE TITLE
🐛: Menu Section BUG

### ISSUE THREAD

**Issue by MuraliDharan7** [Avdhesh-Varshney/WebMasterLog#467]
:red_circle: **Title** : Menu section seems not visible in Light Mode
:red_circle: **Bug** : The "WebMasterLog" and "Dark Mode" Text is not visible in Light Mode
:red_circle: **Changes** :  Color of the text should be changed or background can also be.

### Screenshots 📷
![LightMode](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/130668745/683b03c6-da07-45d8-add7-4b4ec539f9cf)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MuraliDharan
- What is your participant role? (Mention the Open Source Program name. GSSoC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
No it's the problem of light mode is not working properly
