### ISSUE TITLE
📃: Interactive drawing website 

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#471]
:red_circle: **Title** : Drawing website
:red_circle: **Aim** :  create a responsive and feature-rich interactive drawing website. incorporating tools for drawing, erasing, saving, loading, undoing, redoing, and customizations like brush size and color, along with animations and a modern UI.
:red_circle: **Tech Stack Used** : html css javascript and vanilla js 

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/ba61b1e8-c728-4c0b-a195-b8fb0b2d144a)
i will improve this website but right now this is what it will look like 

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Bhaumik
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aditya-bhaumik** [comment]
@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
