### ISSUE TITLE
📃: FlexFLow (Fitness Website ) in Frontend project

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Avdhesh-Varshney/WebMasterLog#473]
:red_circle: **Title** : FLEXFLOW (FITNESS WEBSITE)
:red_circle: **Aim** : revolves around providing resources, information, and tools to help individuals improve their health and fitness levels. 
:red_circle: **Tech Stack Used** : HTML,CSS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142687709/3c37f311-be5a-47a8-852f-edeec079a60d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Pushkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar go ahead.
