### ISSUE TITLE
📃: Add World Population Stats (dummy) Project

### ISSUE THREAD

**Issue by vansh-codes** [Avdhesh-Varshney/WebMasterLog#480]
:red_circle: **Title** : World Population
:red_circle: **Aim** : An dummy world population website with population predictor
:red_circle: **Tech Stack Used** : HTML, CSS, javascript

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/dec570a2-1354-458b-832f-6601b4fc027d)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/b1a26c5f-15b1-4f71-b059-847cf3ff306c)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/a10b9237-63a4-46cc-887e-13e64f37aa85)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/4867773c-8339-4a0c-8c28-c187a3c59941)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/93fcf292-e650-4bf6-b3b1-6b0271d2792a)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/afa4670c-fce2-4575-b900-a96f5b31642e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vansh Chaurasiya
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24 Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@vansh-codes go ahead.
