### ISSUE TITLE
📃: Adding Quote Generato in Vue Js projects section

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#482]
:red_circle: **Title** : Quote Generator
:red_circle: **Aim** : To randomly generate Quotes
:red_circle: **Tech stack** : Html, Css and Vue js

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi Jain
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Aditijainnn go ahead. And raise 1 issue at a time.
