### ISSUE TITLE
📃: Add Guess The Number Game 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Avdhesh-Varshney/WebMasterLog#483]
:red_circle: **Title** : Guess The Number Game 
:red_circle: **Aim** : Project addition under Vanilla Js Projects
:red_circle: **Tech Stack Used** : HTML, CSS, Vanilla Js

### Screenshots 📷

![Screenshot_20240706-225722_Samsung Internet.jpg](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/123104247/adea0f76-806f-4aa9-b13c-595c194e1a2e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parna Roy Chowdhury 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24 

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no calculators allowed.
