### ISSUE TITLE
📃:Pomodoro Clock in Vue js

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#484]
:red_circle: **Title** : Pomodoro Clock
:red_circle: **Aim** : User can start timer, can stop timer, can choose timer, short break, or long break, can see progress bar, can see seconds count down, can set number of minutes for each type of timer and add tasks at the bottom it also had dark theme and light toggle theme.

:red_circle: **Tech Stack Used** : Vue.js, Vue CLI and Vuetify

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/144632601/aaa86a60-c9a9-44bb-b3f2-69dce5c7419e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi Jain
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
- Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Aditijainnn** [comment]
@Avdhesh-Varshney please assign me this

**Comment by Avdhesh-Varshney** [comment]
@Aditijainnn go ahead.
