### ISSUE TITLE
📃: Add Task Reminder

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/WebMasterLog#489]
:red_circle: **Title** : Task Reminder
:red_circle: **Aim** : The aim of a Task Reminder application is to help users efficiently manage tasks and deadlines through notifications and scheduling.
:red_circle: **Tech Stack Used** :  html css js

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) - GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vaibhavvatsbhartiya** [comment]
Hello, @Utsavladia
My name is Vaibhav Vats,
I would like to work on this issue and my main motive is to learn about open-source contributions.
can you assign me this task.
I'll make sure to provide you a ready to use project .
Thank you.

**Comment by vaibhavvatsbhartiya** [comment]
Hello,
My name is Vaibhav Vats,
I would like to work on this issue and my main motive is to learn about open-source contributions.
can you assign me this task.
I'll make sure to provide you a ready to use project .
Thank you.

**Comment by Avdhesh-Varshney** [comment]
@ananyag309 go ahead.
