### ISSUE TITLE
📃: Search Countries over the world 

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/WebMasterLog#490]
:red_circle: **Title** : Countries of the world 
:red_circle: **Aim** : A single page application that displays information about all countries by integrating rest api
:red_circle: **Tech Stack Used** :  html css js
under frontend projects

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ananya Gupta
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vaibhavvatsbhartiya** [comment]
Hello,
My name is Vaibhav Vats,
I would like to work on this issue and my main motive is to learn about open-source contributions.
can you assign me this task.
I'll make sure to provide you a ready to use project .
Thank you.

**Comment by Avdhesh-Varshney** [comment]
@ananyag309 go ahead.
