### ISSUE TITLE
📃: Adding Nodemailer Project

### ISSUE THREAD

**Issue by dhairyagothi** [Avdhesh-Varshney/WebMasterLog#494]
:red_circle: **Title** :  Nodemailer
:red_circle: **Aim** : adding a node JS project that will send mail directly 
:red_circle: **Tech Stack Used** :  NodeJS Express

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142989448/a12cc0c4-7988-4c61-b982-ad92bdd09d6c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Dhairya Gothi
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@dhairyagothi go ahead.
