### ISSUE TITLE
📃: Add Currency converter

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#496]
:red_circle: **Title** : Currency converter
:red_circle: **Aim** : Make Currency convert easy
:red_circle: **Tech Stack Used** : HTML , CSS , JS

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Please assign me this task !

Thank You !

**Comment by Avdhesh-Varshney** [comment]
issue already present.
