### ISSUE TITLE
📃: Daily Journal Website

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#497]
:red_circle: **Title** : Daily Journal Website
:red_circle: **Aim** : The "Daily Journal" website is a platform where users can record their personal reflections and thoughts, organized by date and mood, providing a private space for emotional expression.
:red_circle: **Tech Stack Used** : Html Css and javascript vanilla js 

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/3b957765-1347-46df-9968-156c5d58f656)
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Bhaumik
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aditya-bhaumik** [comment]
@Avdhesh-Varshney hi i have added the pull request for my previous issue can you please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
