### ISSUE TITLE
📃: Add IP Address Tracker

### ISSUE THREAD

**Issue by Maheshwari-Love** [Avdhesh-Varshney/WebMasterLog#498]
:red_circle: **Title** : IP Address Tracker
:red_circle: **Aim** : To track the IP Address
:red_circle: **Tech Stack Used** : Reactjs 

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maheshwari Love
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Maheshwari-Love go ahead.
