### ISSUE TITLE
🐛: Search Bar Not Working

### ISSUE THREAD

**Issue by SCR01** [Avdhesh-Varshney/WebMasterLog#502]
:red_circle: **Title** :  Search Bar Not Working
:red_circle: **Bug** : The search bar on the "WEB MASTER LOG" page is currently non-functional. Users are unable to perform any searches, and no results are being returned when search queries are entered.
:red_circle: **Changes** :  

Diagnose the Issue:
Check for front-end errors and inspect network requests.

Fix the Issue:
Resolve errors, ensure proper request handling, and debug the back-end search functionality.

Test the Fix:
Conduct thorough testing with various queries and validate across different browsers and devices.

### Video 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/97039791/16c7a35d-3763-471f-b205-37951248f7c2

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sharad Chandra Reddy
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no, i'll remove this search bar from the sidebar. Working on a chatbot to search, filter functionality

**Comment by SCR01** [comment]
Ok, Sir.
