### ISSUE TITLE
📃: Add Isomorphic Strings Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#505]
:red_circle: **Title** : Isomorphic Strings Checker
:red_circle: **Aim** : It will help us to check if two strings are isomorphic or not. Two strings a and b are isomorphic if the characters in a can be replaced to get b.All occurrences of a character must be replaced with another character while preserving the order of characters. No two characters may map to the same character, but a character may map to itself.

:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role?  GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
