### ISSUE TITLE
📃: StopWatch

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Avdhesh-Varshney/WebMasterLog#507]
:red_circle: **Title** : StopWatch
:red_circle: **Aim** : To help athletes and trainers track performance improvements over time.
:red_circle: **Tech Stack Used** :  HTML,CSS , JAVASCRIPT 

### Screenshots 📷

N/A
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : KHUSHI PUSHKAR
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GGSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar go ahead.
