### ISSUE TITLE
📃: Fully functional Kanban board also include drag and drop task from one column to another 

### ISSUE THREAD

**Issue by heli0707** [Avdhesh-Varshney/WebMasterLog#509]
:red_circle: **Title** : Kanban-board
:red_circle: **Aim**: This project aims to create a visual tool called a Kanban board that helps users manage tasks more efficiently. A Kanban board is divided into columns that represent different stages of a process, such as "To Do," "In Progress," and "Done." Users can move task cards between these columns to track the progress of their work.
:red_circle: **Tech Stack Used** :  HTML CSS JS 

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/4d9dd15f-4252-4d59-8ee6-7dc6f39262be)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue:**
- Full name : Heli Dhanrajbhai Detroja
- What is your participant role: GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@heli0707 go ahead.
