### ISSUE TITLE
📃: Amazon Prime Clone 

### ISSUE THREAD

**Issue by codewithganeshhh** [Avdhesh-Varshney/WebMasterLog#511]
:red_circle: **Title** : Amazon Prime Clone 
:red_circle: **Aim** : The goal of this project is to develop a clone of Amazon Prime, focusing on the key features and functionalities that make the service popular. The aim is to create a comprehensive streaming platform that allows user.
:red_circle: **Tech Stack Used** : HTML , CSS

### Screenshots 📷

![Screenshot 2024-07-07 131329](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139307139/16edb5ba-8f84-454f-b373-fed8a42f4e09)
![Screenshot 2024-07-07 131307](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139307139/46b432a9-7bdc-41b2-8538-b8959e750f5b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ganesh Kumar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) 
- GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@codewithganeshhh it's already present.
