### ISSUE TITLE
📃: myntra clone in frontend

### ISSUE THREAD

**Issue by sanayamahajan-23** [Avdhesh-Varshney/WebMasterLog#512]
:red_circle: **Title** : myntra clone
:red_circle: **Aim** : make a clone of myntra webite of its frontend homepage
:red_circle: **Tech Stack Used** : react ,javascript,css ,bootstrap and html

### Screenshots 📷

N/A
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : sanaya mahajan 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@sanayamahajan-23 go ahead.
