### ISSUE TITLE
📃: Click Per Minute game

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#513]
:red_circle: **Title** :  Click Per Minute
:red_circle: **Aim** :  Game with Vanilla JS
:red_circle: **Tech Stack Used** : HTML , BOOTSTRAP , Java-Script

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney Can You please assign me !

Thank you !

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy no games allowed
