### ISSUE TITLE
📃: Add Substrings Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#514]
:red_circle: **Title** : Substrings Checker
:red_circle: **Aim** : It help us to check if one string is a substring of another string.A substring is defined as a contiguous part of a string, i.e., a string inside another string.
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir, please assign me this issue I have completed the previous issues.

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
