### ISSUE TITLE
📃: Garden planning website

### ISSUE THREAD

**Issue by aditya-bhaumik** [Avdhesh-Varshney/WebMasterLog#515]
:red_circle: **Title** : Garden planning website
:red_circle: **Aim** :  This garden planner website allows users to drag and drop various plants onto a grid, dynamically calculating the total cost as they design their garden layout. It's beneficial for gardening enthusiasts by providing an interactive and cost-effective way to plan and visualize their garden designs in a user-friendly manner.
:red_circle: **Tech Stack Used** :  Html Css and vanilla js

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/5806c544-df25-4642-a027-13adac7c6476)
something like this i will add more features to this and improve the ui but i will make something like this

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditya Bhaumik
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@aditya-bhaumik go ahead.
