### ISSUE TITLE
📃: Add e-commerce website

### ISSUE THREAD

**Issue by chaanakyaaM** [Avdhesh-Varshney/WebMasterLog#517]
:red_circle: **Title** : Add e-commerce website
:red_circle: **Aim** : To add e-commerce website
:red_circle: **Tech Stack Used** : HTML, CSS, JS, React JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : chaanakyaa Milkuri
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@chaanakyaaM tell me brief about the e-commerce website

**Comment by chaanakyaaM** [comment]
A e-commerece website interface using reactjs (frontend)

**Comment by Avdhesh-Varshney** [comment]
I'm asking for which e-commerce website are you want to contribute? Not the tech stacks.
