### ISSUE TITLE
📃: Add myntra-clone

### ISSUE THREAD

**Issue by chaanakyaaM** [Avdhesh-Varshney/WebMasterLog#518]
:red_circle: **Title** : Add Myntra-clone
:red_circle: **Aim** : To add myntra-clone
:red_circle: **Tech Stack Used** : HTML, CSS, ReactJS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
issue already present
