### ISSUE TITLE
📃: Add Number Guessing

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Avdhesh-Varshney/WebMasterLog#519]
:red_circle: **Title** :  Add Number Guessing
:red_circle: **Aim** :  To add number guessing
:red_circle: **Tech Stack Used** :  HTML, CSS, Javascript

### Screenshots 📷

https://github.com/Avdhesh-Varshney/WebMasterLog/assets/138589633/8b9e4cc2-d2db-4bc8-95b8-23faca0b059c

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ishita Mukherjee
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.): GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by meetarora10** [comment]
Full Name : Meet Arora
GSSOC

**Comment by Avdhesh-Varshney** [comment]
@Ishitamukherjee2004 not required.
