### ISSUE TITLE
📃: Add a Random Advice Generator

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#520]
:red_circle: **Title** : Random Advice Generator
:red_circle: **Aim** : Generates a new and random advice each time on click of the button . 
:red_circle: HTML,CSS and JavaScript

### Screenshots 📷

![Screenshot (522)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143121854/7d00605f-d7b1-4984-be75-c3d8dd3d0133)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 go ahead.
