### ISSUE TITLE
📃: Add Zomato Clone frontend 

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#521]
:red_circle: **Title** : Zomato Clone
:red_circle: **Aim** : Add completely responsive frontend layout of Zomato website.
:red_circle: **Tech Stack Used** : HTML,CSS,JavaScript

### Screenshots 📷

N/A
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by meetarora10** [comment]
@Avdhesh-Varshney consider this issue also

**Comment by meetarora10** [comment]
@Avdhesh-Varshney 
In this responsive frontend layout there will be a navbar , homepage , about section , contact us section and a footer with different images and attractive design .
I have also added smooth scroll on click of links on the navbar .

**Comment by meetarora10** [comment]
![Screenshot (695)](https://github.com/user-attachments/assets/17fc8eea-0d16-4b7d-a974-5a9161bc6497)
![Screenshot (696)](https://github.com/user-attachments/assets/9d1b4f56-b190-4a1a-94fb-3c53ffab2f61)

**Comment by meetarora10** [comment]
@Avdhesh-Varshney assign me this issue.

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 go ahead.
