### ISSUE TITLE
📃: Random Picker item from list

### ISSUE THREAD

**Issue by heli0707** [Avdhesh-Varshney/WebMasterLog#522]
:red_circle: **Title** : Random generator wheel 
:red_circle: **Aim**: This project aims to create an interactive web application that allows users to input a list of items and randomly select one item from that list. This project demonstrates the integration of HTML, CSS, and JavaScript to build a functional and user-friendly tool for decision-making or entertainment purposes.
:red_circle: **Tech Stack Used** : HTML CSS JS

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/ac63152a-a12d-45db-9fab-dc2b4d1147f6)

concept something like this
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Heli Dhanrajbhai Detroja
- What is your participant role: GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@heli0707 don't raise more than 1 issue
