### ISSUE TITLE
📃: netflix Clone in Front end Projects

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Avdhesh-Varshney/WebMasterLog#525]
:red_circle: **Title** : netflix Clone
:red_circle: **Aim** : To Know How to develop a Netfix website
:red_circle: **Tech Stack Used** : HTMl CSS JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ch.Saipradyumna
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Saipradyumnagoud** [comment]
@Avdhesh-Varshney Please assign me the issue

**Comment by Avdhesh-Varshney** [comment]
@Saipradyumnagoud already present.
