### ISSUE TITLE
📃: BMI Calculator

### ISSUE THREAD

**Issue by heli0707** [Avdhesh-Varshney/WebMasterLog#528]
:red_circle: **Title** : BMI-Calculator
:red_circle: **Aim** : To develop a responsive BMI (Body Mass Index) calculator using HTML, CSS, and JavaScript that allows users to input their weight and height and get an accurate BMI reading along with a health status message.
:red_circle: **Tech Stack Used** : HTML CSS JS

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Heli Dhanrajbhai Detroja
- What is your participant role : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@heli0707 no calculators allowed.
