### ISSUE TITLE
📃: Expense Splitter Website 

### ISSUE THREAD

**Issue by vivekvardhan2810** [Avdhesh-Varshney/WebMasterLog#530]
:red_circle: **Title** : Expense Splitter Website 
:red_circle: **Aim** : Create an expense splitting website for helping users manage and divide shared expenses efficiently.
:red_circle: **Tech Stack Used** : HTML, CSS, and vanilla JavaScript

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vivek Vardhan
- What is your participant role? (Mention the Open Source Program name. GSSOC 24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@vivekvardhan2810 go ahead.
