### ISSUE TITLE
📃: JS Intermediate Project Addition: Makeover Game

### ISSUE THREAD

**Issue by abckhush** [Avdhesh-Varshney/WebMasterLog#534]
:red_circle: **Title** : Makeover Game
:red_circle: **Aim** :  To dress the character as per your wish. 
:red_circle: **Tech Stack Used** :  JS

### Screenshots 📷

![Makeover_Game](https://github.com/kunjgit/GameZone/assets/127378920/92071480-1b1e-4313-9c80-63c6cb63d4da)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Khushi Kalra
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@abckhush no games project and don't raise more than 1 issue
