### ISSUE TITLE
📃: Intermediate JS Project: Auddle

### ISSUE THREAD

**Issue by abckhush** [Avdhesh-Varshney/WebMasterLog#535]
:red_circle: **Title** :  Auddle
:red_circle: **Aim** :  Guess the singer using the song.
:red_circle: **Tech Stack Used** :  JS

### Screenshots 📷

![image](https://github.com/kunjgit/GameZone/assets/127378920/41f90149-b5e4-4c92-a993-108e01f7b9c5)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Khushi Kalra
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@abckhush no games allowed
