### ISSUE TITLE
📃:  ReactJS Project: Chat Application

### ISSUE THREAD

**Issue by abckhush** [Avdhesh-Varshney/WebMasterLog#537]
:red_circle: **Title** : Chat Application
:red_circle: **Aim** :  To create a chat application that allows users to interact with each other.
:red_circle: **Tech Stack Used** :  ReactJS

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Kalra
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@abckhush go ahead.
