### ISSUE TITLE
📃: Add a digital clock which displays time , date as well as day .

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#539]
:red_circle: **Title** : Digital Clock
:red_circle: **Aim** : This digital clock displays current time , proper date as well as day with an attractive UI .
:red_circle: **Tech Stack Used** : HTML,CSS , JavaScript

### Screenshots 📷
![Screenshot (697)](https://github.com/user-attachments/assets/6bb0baea-7ac9-4edd-b00f-0c59993adc9d)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 don't raise more than 1 issue and this project is not required.

**Comment by meetarora10** [comment]
> @meetarora10 don't raise more than 1 issue and this project is not required.

@Avdhesh-Varshney okay 👍👍
