### ISSUE TITLE
📃:  Login/Sign up form

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Avdhesh-Varshney/WebMasterLog#540]
:red_circle: **Title** : Login/Sign up form
:red_circle: **Aim** : is to facilitate user authentication and account creation on various platforms.
:red_circle: **Tech Stack Used** : HTML,CSS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Pushkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar go ahead.
