### ISSUE TITLE
📃:  Tesla Website Clone Project

### ISSUE THREAD

**Issue by AmrutaJayanti** [Avdhesh-Varshney/WebMasterLog#546]
:red_circle: **Title** : Tesla Website Clone
:red_circle: **Aim** : Project is a clone of the Tesla website
:red_circle: **Tech Stack Used** :  HTML CSS JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Amruta Jayanti
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
show me which page you want to clone

**Comment by AmrutaJayanti** [comment]
![Screenshot 2024-07-14 162839](https://github.com/user-attachments/assets/d7d003b7-dd5b-48c5-bbf6-1a7a002da4b9)

**Comment by Avdhesh-Varshney** [comment]
@AmrutaJayanti go ahead.
