### ISSUE TITLE
📃: Add Subsequence Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#547]
:red_circle: **Title** : Subsequence Checker
:red_circle: **Aim** : It helps us to check if one string is the subsequence of another string or not.A subsequence of a string is a new string that is formed from the original string by deleting some (can be none) of the characters without disturbing the relative positions of the remaining characters. (i.e., "ace" is a subsequence of "abcde" while "aec" is not).
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir , please assign me this issue.

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
