### ISSUE TITLE
📃: WhosThat(Pokemon)

### ISSUE THREAD

**Issue by Maheshwari-Love** [Avdhesh-Varshney/WebMasterLog#549]
🔴 Title : WhosThat
🔴 Aim : Who's That is a simple react js game where you have choose which pokemon match from shadow!
🔴 Tech Stack Used : Reactjs

### Screenshots 📷

![image](https://github.com/user-attachments/assets/e0549018-f4e8-4dc4-b4b7-89506ad26574)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maheshwari Love
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Maheshwari-Love** [comment]
@Avdhesh-Varshney please assign me this task

**Comment by Avdhesh-Varshney** [comment]
@Maheshwari-Love no games allowed
