### ISSUE TITLE
🐛:  Theme change does not work properly, light mode is only applied to the sidebar.

### ISSUE THREAD

**Issue by techy4shri** [Avdhesh-Varshney/WebMasterLog#551]
:red_circle: **Title** : Improve theme change, i.e. switching between light mode and dark mode
:red_circle: **Bug** : Currently, the theme change only happens in the sidebar, the rest of the website remains black (in dark mode).
:red_circle: **Changes** :  Implement theme change throughout the webapp.
Ensure the switch between the two themes is applied evenly across the webapp. 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/d1d91bc0-bfe7-4cc9-9787-d319f4cbd433)
![image](https://github.com/user-attachments/assets/b34dd534-137d-4968-ad4d-270c2ed50288)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  GARIMA
- What is your participant role?: GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@techy4shri go ahead.

**Comment by Avdhesh-Varshney** [comment]
@techy4shri What's the update?

**Comment by techy4shri** [comment]
> @techy4shri What's the update?

Testing themes for proper visibility. Some parts were excluded in the previous code so trying to implement golbal control properly.

**Comment by Avdhesh-Varshney** [comment]
Use this [context api](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/src/contexts/Context.jsx). I've already created these 2 ` isDarkMode, setDarkMode,` parameters. It will help to declare it globally.

Do it fast within 2 days.
