### ISSUE TITLE
📃: Add Pokemon Search

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#554]
:red_circle: **Title** : Pokemon Search
:red_circle: **Aim** : This app uses the PokeAPI Proxy and displays the details of the pokemon as well as the image of the respective pokemon  entered by the user .
:red_circle: **Tech Stack Used** : HTML,CSS,JavaScript

### Screenshots 📷

https://github.com/user-attachments/assets/1d3c75c2-692f-4238-9c83-bfe6798d112a

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required
