### ISSUE TITLE
🐛: Not appearing menu symbol in the light mode

### ISSUE THREAD

**Issue by jayanththalla** [Avdhesh-Varshney/WebMasterLog#555]
:red_circle: **Title** :
:red_circle: **Bug** :
:red_circle: **Changes** :  
On the main page, the menu symbol does not appear when light mode 

### Screenshots 📷

![Uploading image.png…]()

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Thalla Jayanth
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Light mode is under processing #551
