### ISSUE TITLE
Sudoku Solver using Vanilla JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#56]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Sudoku Solver
:red_circle: **Aim** : Build a website which can solve a Sudoku by entering a numbers of the problem of the sudoku.
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vishal2005025** [comment]
I Would like to Work on this issue.
Please assign it to me under JWOC'2024.

**Comment by vishal2005025** [comment]
sir , please assign it to me.

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024.

Name = Sohan RoyChowdhury.
Github = https://github.com/SohanRC
Role = Under JWOC 2024.

**Comment by AftabMankapure** [comment]
### Assign me under JWOC


Name : Aftab Mankapure
Github: https://github.com/AftabMankapure
Role: Under JWOC

**Comment by SohanRC** [comment]
> Please assign me under JWOC 2024.
> 
> Name = Sohan RoyChowdhury. Github = https://github.com/SohanRC Role = Under JWOC 2024.

Please assign me this issue under JWOC 2024.

**Comment by Avdhesh-Varshney** [comment]
@SohanRC Assigned to you. Follow the contributing guidelines carefully.
