### ISSUE TITLE
📃: Add a Star Rating Component

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#560]
:red_circle: **Title** : Star Rating Component
:red_circle: **Aim** : User can dynamically rate and give stars out of 5. After selecting , when the submit button is clicked then a thank you message is displayed in which the corresponding rating given by user is shown.
:red_circle: **Tech Stack Used** : HTML,CSS,JavaScript

### Screenshots 📷
![Screenshot (616)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143121854/a6f5ff26-7ef5-48e2-9f4b-ddb373441349)
![Screenshot (617)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/143121854/95eb101f-fabe-4873-a14a-d85732b12444)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 go ahead
