### ISSUE TITLE
📃: Password Manager

### ISSUE THREAD

**Issue by thevijayshankersharma** [Avdhesh-Varshney/WebMasterLog#562]
:red_circle: **Title** :  Password Manager
:red_circle: **Aim** :  Develop a cutting-edge password manager to securely store and manage user credentials, ensuring ease of access and enhanced security.
:red_circle: **Tech Stack Used** :  HTML, CSS, and vanilla JavaScript

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Vijay Shanker Sharma
- What is your participant role? (Mention the Open Source Program name. GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@thevijayshankersharma go ahead.
