### ISSUE TITLE
📃: New Swiggy Clone for frontend projects

### ISSUE THREAD

**Issue by Madhavan112** [Avdhesh-Varshney/WebMasterLog#564]
:red_circle: **Title** : Swiggy Clone
:red_circle: **Aim** :  To build swiggy clone for learning
:red_circle: **Tech Stack Used** : React ,Tailwind CSS

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Madhavan V
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
Contributor - GSSOC24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Madhavan112 go ahead.
