### ISSUE TITLE
🧑‍💻: Performance enhancement request

### ISSUE THREAD

**Issue by Tanishashrivas** [Avdhesh-Varshney/WebMasterLog#565]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :
:red_circle: **Changes** : 
i would like to implement lazy loading in order to improve the performance of the application and make it handle the load efficiently

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Tanisha Shrivas
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC'24 Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Tanishashrivas go ahead.
