### ISSUE TITLE
🧑‍💻: Add Search Bar Functionality

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Avdhesh-Varshney/WebMasterLog#566]
:red_circle: **Title** :Search Bar
:red_circle: **Enhancement Aim** :I want to add search bar in every projects section 
:red_circle: **Changes** : adding search bar

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : MANKALA VAISHNAVI
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@VaishnaviMankala19 Not required. I'm focusing on creating a chatbot which can provide all the details of the project. It'll able to filter, explain, redirect, and guide the user. If you're able to do, raise the issue and mention to me on discord server.
