### ISSUE TITLE
📃: adding Interview-Report application 

### ISSUE THREAD

**Issue by Maheshwari-Love** [Avdhesh-Varshney/WebMasterLog#567]
:red_circle: **Title** : Interview Report
:red_circle: **Aim** : To generate report for Interview
:red_circle: **Tech Stack Used** : REACT JS

### Screenshots 📷

![Screenshot 2024-07-17 215443](https://github.com/user-attachments/assets/93cb6f90-b158-45ed-8b83-343999dd4ea5)

![image](https://github.com/user-attachments/assets/dfd5c659-963c-4b4d-8754-37498bd4212d)
![image](https://github.com/user-attachments/assets/42bbde89-a839-40bc-9c7f-24b988751c81)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Maheshwari Love
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Maheshwari-Love** [comment]
@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Maheshwari-Love go ahead. Can you elaborate what is the input feed of this project?

**Comment by Maheshwari-Love** [comment]
@Avdhesh-Varshney if it is not a valid project then please assign me this issue to work upon #572 Or #570
