### ISSUE TITLE
🧑‍💻: Enhancing the Preloader with an Animated Preloader

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Avdhesh-Varshney/WebMasterLog#573]
:red_circle: **Title** :  Enhancing the Preloader
:red_circle: **Enhancement Aim** :  Enhance the preloader with an engaging animation to improve user experience and reduce perceived loading times.
:red_circle: **Changes** : i want to Enhance the Preloader with an Animated Preloader

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Pushkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar create it under shared component and don't create any external css file. Just use only boostrap css and inline css only.
