### ISSUE TITLE
🧑‍💻: Improve UI of button

### ISSUE THREAD

**Issue by Priyal208** [Avdhesh-Varshney/WebMasterLog#574]
:red_circle: **Title** :
The button looks very plain and simple with green static color
:red_circle: **Enhancement Aim** :
I can make it more attractive and appealing by adding glow effect 
:red_circle: **Changes** : 
I can make it glowing and attractive on hover add glow effect and beautiful border, kindly assign this issue to me, i can gurantee you wont be desappointed

### Screenshots 📷
![Screenshot 2024-07-18 231902](https://github.com/user-attachments/assets/5dff2efe-ae3a-4105-8fb2-25bedcb43086)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyal Rawal
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Priyal208** [comment]
@Avdhesh-Varshney kindly assign this to me

**Comment by Avdhesh-Varshney** [comment]
solve it under #575
