### ISSUE TITLE
🧑‍💻:Add Border to cards

### ISSUE THREAD

**Issue by Priyal208** [Avdhesh-Varshney/WebMasterLog#575]
:red_circle: **Title** : 
The cards are looking very plain simple and static 
:red_circle: **Enhancement Aim** :
I can add beautiful border to it.
:red_circle: **Changes** : 
I love working with UI and can make your cards higly attractive by adding glowing borders with gradient that are also moving, UI is my favorite thing and I can gurnatee you will love the changes

### Screenshots 📷
![Screenshot 2024-07-18 231909](https://github.com/user-attachments/assets/1f3367d4-fb2e-46de-8f68-e0fe034acf32)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyal Rawal
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Priyal208** [comment]
@Avdhesh-Varshney kindly assign this to me

**Comment by Avdhesh-Varshney** [comment]
@Priyal208 enhance the full card component. And I'm looking to create a glassmorphism effect on cards or you show your creativity.

**Comment by Priyal208** [comment]
sure

**Comment by Priyal208** [comment]
@Avdhesh-Varshney could you help me with the local setup , i did npm i and npm run dev, my screen remains blank white, i tried lots of thing but it doesnt start, i am stuck at it since 1 hour

**Comment by Avdhesh-Varshney** [comment]
Share the ss and discuss on discord server for quick communication.
