### ISSUE TITLE
🧑‍💻: Add hover effect to cards

### ISSUE THREAD

**Issue by Priyal208** [Avdhesh-Varshney/WebMasterLog#576]
:red_circle: **Title** :
The cards are currently plain and static
:red_circle: **Enhancement Aim** :
I can add hover effect to cards
:red_circle: **Changes** : 
On hovering the colors of cards will change and will higlight that card for user also will add bit of scalling so that the card pops up, I love working with UI and you can trust me on this one, kindly assign this to me

### Screenshots 📷
![Screenshot 2024-07-18 232434](https://github.com/user-attachments/assets/71ba23c0-4f7f-4887-8adc-dbc7552a7266)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priyal Rawal
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) 
GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Priyal208** [comment]
@Avdhesh-Varshney kindly assign this to me

**Comment by Avdhesh-Varshney** [comment]
solve it under #575 And don't raise more than 1 issue at a time.
