### ISSUE TITLE
📃: Quiz app - Next js

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#577]
:red_circle: **Title** : Quiz app
:red_circle: **Aim** : Develop a quiz application with multiple-choice questions.
:red_circle: **Tech Stack Used** : Next js, Tailwind CSS, Local JSON file for quiz questions

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi Balasubramaniyam
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) : GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam go ahead.
