### ISSUE TITLE
📃:  Water Puzzle Game

### ISSUE THREAD

**Issue by thevijayshankersharma** [Avdhesh-Varshney/WebMasterLog#581]
:red_circle: **Title** :  Water Puzzle Game
:red_circle: **Aim** :  Develop a web-based water puzzle game where players solve challenges by sorting colored liquids into test tubes based on specific rules.
:red_circle: **Tech Stack Used** :  HTML, CSS, and vanilla JavaScript

### Screenshots 📷

![image](https://github.com/user-attachments/assets/1ca6e746-7ae1-4c7d-a1d8-e1647e476ad4)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Vijay Shanker Sharma
- What is your participant role? (Mention the Open Source Program name.  GSSOC)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
no games allowed.
