### ISSUE TITLE
📃: Shopping cart - React redux

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#583]
:red_circle: **Title** : Shopping cart
:red_circle: **Aim** : Product Listing, Product Details, Add to Cart, View Cart, Update Cart (quantity adjustments), Remove from Cart
:red_circle: **Tech Stack Used** : React.js, React redux, tailwind css, fakestoreapi

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Dharshi
- What is your participant role? GSSOC, SSOC, JWOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam go ahead.
