### ISSUE TITLE
🧑‍💻: Add Some Hover effects on home page's cards.

### ISSUE THREAD

**Issue by zalabhavy** [Avdhesh-Varshney/WebMasterLog#584]
:red_circle: **Title** : Add Hover effects
:red_circle: **Enhancement Aim** : User experience and feel
:red_circle: **Changes** : add css.

### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhavy Zala
- What is your participant role? Gssoc'24e

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@zalabhavy It's under working in #575

**Comment by zalabhavy** [comment]
@Avdhesh-Varshney I am talking about this cards i will add attractive scale and tap effects also make it attractive.

![image](https://github.com/user-attachments/assets/6466c029-8faa-4b36-950a-1d084c331e96)
![image](https://github.com/user-attachments/assets/e6224716-2d99-4f47-99d6-0a60912194c9)
![image](https://github.com/user-attachments/assets/cb221784-e437-45c7-b492-96b4d3c2c93f)

**Comment by Avdhesh-Varshney** [comment]
No, these are not required.
