### ISSUE TITLE
📃: Add MakeMyTrip Clone (frontend)

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#585]
:red_circle: **Title** : MakeMyTrip Clone
:red_circle: **Aim** :  This frontend clone of MakeMyTrip Website includes homepage with different animations and transitions , blogs page to show popular destinations .
:red_circle: **Tech Stack Used** : HTML,CSS

### Screenshots 📷

![Screenshot (768)](https://github.com/user-attachments/assets/fbd6f7ff-2dd6-47c8-a2f3-082481b45ad5)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 It's already present
