### ISSUE TITLE
📃: Add Vocabulary Builder (VanillaJS)

### ISSUE THREAD

**Issue by kosuri-indu** [Avdhesh-Varshney/WebMasterLog#587]
:red_circle: **Title** :  Vocabulary Builder
:red_circle: **Aim** :  An application to help users learn new words, with flashcards and quizzes
:red_circle: **Tech Stack Used** : HTML, CSS, Javascript 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/effb3262-0bf4-48b4-945d-9e248b745d11)

![image](https://github.com/user-attachments/assets/b86596c9-5f19-4d10-887b-5b620bb3ba23)

![image](https://github.com/user-attachments/assets/2d085187-79b5-40e2-aeae-3664563ca53c)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Kosuri Indu
- What is your participant role? GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by kosuri-indu** [comment]
@Avdhesh-Varshney 
Please assign this issue to me :)
Thank you

**Comment by Avdhesh-Varshney** [comment]
@kosuri-indu go ahead.
