### ISSUE TITLE
📃: Cooking Blog website

### ISSUE THREAD

**Issue by 1simransaini** [Avdhesh-Varshney/WebMasterLog#588]
:red_circle: **Title** : Cooking-Blog
:red_circle: **Aim** :  Tasty Tales is a cooking blog designed to inspire and engage food enthusiasts by providing a platform where users can view recipes categorized by different cuisines, such as Indian, Chinese, and more. Key features of Tasty Tales include:

- **Recipe Viewing:** Users can browse and view detailed recipes.
- **Categorized Recipes:** Recipes are organized into categories for easy access.
- **Search Recipes:** Users can search for recipes using keywords.
- **Submit Recipes:** Users can submit their own recipes and contribute to the blog's content.
- **Latest Recipes:** Users can explore the newest additions to the recipe collection.
- **Random Recipes:** Users can discover random recipes for inspiration.

:red_circle: **Tech Stack Used** :  NodeJS, Express, MongoDB, EJS, Bootstrap

### Screenshots 📷

![2](https://github.com/user-attachments/assets/3d79db04-f039-4f65-880c-728bc516941a)
![3](https://github.com/user-attachments/assets/4274946a-cd18-4116-8e3a-762634d70cb8)
![1](https://github.com/user-attachments/assets/dddf7959-eee8-406f-8df4-d64089edb13f)
![5](https://github.com/user-attachments/assets/be7b0bd7-f029-49d5-a813-a5aa461bef8d)
![6](https://github.com/user-attachments/assets/5b591fb5-560f-48f9-86ed-2c00fbadf18b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Simran Saini
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@1simransaini go ahead.
