### ISSUE TITLE
🧑‍💻: Add a Beginner-Friendly E-Commerce Front-End Project.

### ISSUE THREAD

**Issue by SCR01** [Avdhesh-Varshney/WebMasterLog#590]
:red_circle: **Title** : Add a Beginner-Friendly E-Commerce Front-End Project.

:red_circle: **Enhancement Aim** : Add a front-end e-commerce project using HTML, CSS, and JavaScript to provide a beginner-friendly learning experience.

:red_circle: **Changes** : 

- Create a new project directory for the e-commerce site.
- Design and implement a home page, product listings page, and product details page.
- Add shopping cart functionality.
- Ensure responsive design.

### Screenshots 📷

![Screenshot 2024-07-20 131801](https://github.com/user-attachments/assets/a8b160ab-057b-4197-a3de-ae47dd0bbb9f)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Sharad Chandra Reddy
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open-source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@SCR01 go ahead.

**Comment by SCR01** [comment]
@Avdhesh-Varshney Thanks, I will start working on this!
