### ISSUE TITLE
📃: YouTube clone in frontend

### ISSUE THREAD

**Issue by yamini777** [Avdhesh-Varshney/WebMasterLog#591]
:red_circle: **Title** : YouTube clone in frontend
:red_circle: **Aim** : I want to add new clone in your folder.
:red_circle: **Tech Stack Used** : HTML CSS JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Yamini Uppal
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@yamini777 go ahead.
