### ISSUE TITLE
📃: Tesla website Clone

### ISSUE THREAD

**Issue by sanayamahajan-23** [Avdhesh-Varshney/WebMasterLog#593]
:red_circle: **Title** : Tesla clone 
:red_circle: **Aim** : to build clone 
:red_circle: **Tech Stack Used** : 
React and redux

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sanaya Mahajan 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@sanayamahajan-23 go ahead.
