### ISSUE TITLE
🧑‍💻: Changing the UI to view projects

### ISSUE THREAD

**Issue by Kiran-pande-30** [Avdhesh-Varshney/WebMasterLog#596]
:red_circle: **UI to View Projects ( Github and Deployed Link )** :
:red_circle: **UI Enhancement** :
:red_circle: **Changes** : 1. We should Directly Display the projects instead of dividing them into basic, intermediate and advanced cards. we can write it on the project card itself about the category. By this user will be able to see all projects at once and can select through that.
### Screenshots 📷
NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Kiran Pande
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Kiran-pande-30 not required. Try to work on chatbot, As I'm currently focusing to integrate a chatbot which will able to discuss about the present project the readme files of each project and able to filtered out.

**Comment by Kiran-pande-30** [comment]
@Avdhesh-Varshney this will be a great feature. As a user it's not so good to navigate between these categories. Users want to see all the projects at a place.
