### ISSUE TITLE
🧑‍💻:  Adding background color while hovering on the 8 cards on home page.

### ISSUE THREAD

**Issue by Kiran-pande-30** [Avdhesh-Varshney/WebMasterLog#597]
:red_circle: **Adding Hovering Effect on the Home Page** :
:red_circle: **Adding Hovering effect to build a better UI* :
:red_circle: **Changes** :  Will color the cards on hovering

### Screenshots 📷
![image](https://github.com/user-attachments/assets/2e85c7ba-29f9-484d-b930-2eff5492540e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Kiran Pande
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Kiran-pande-30 leave this part. Keep the website professional. Too much effects will reduce the ux.

**Comment by Kiran-pande-30** [comment]
@Avdhesh-Varshney Yeah, I know about too many effects ruin the webpage. It will be just a color addition on hovering. It will look good 👍
