### ISSUE TITLE
📃: Add Recipe book

### ISSUE THREAD

**Issue by pavitraag** [Avdhesh-Varshney/WebMasterLog#598]
:red_circle: **Title** : Recipe Book
:red_circle: **Aim** : To create a static web-based recipe book with animations, where users can view a collection of recipes, including ingredients and instructions. The design will feature a clean, user-friendly interface with animations to enhance user experience.
:red_circle: **Tech Stack Used** : HTML, CSS

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Pavitraa G
- What is your participant role? contributor in gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@pavitraag go ahead.
