### ISSUE TITLE
📃: Password Validator

### ISSUE THREAD

**Issue by thevijayshankersharma** [Avdhesh-Varshney/WebMasterLog#599]
:red_circle: **Title** : Password Validator
:red_circle: **Aim** :  To create a password validator tool that checks various criteria such as length, presence of numerical characters, special characters, and spaces in real-time.
:red_circle: **Tech Stack Used** :  HTML, CSS, JavaScript (vanilla)

### Screenshots 📷
![image](https://github.com/user-attachments/assets/ddfc2c64-5f23-4edb-bd7a-ca914a177823)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Vijay Shanker Sharma
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@thevijayshankersharma Not required. Don't raise too much issue at a time.

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma Not required. Don't raise too much issue at a time.

OK.
