### ISSUE TITLE
📃: Add a prime number checker

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#602]
:red_circle: **Title** : Prime Number Checker 
:red_circle: **Aim** : Checks whether the number entered in the input fields is prime or not , provided with an attractive UI.
:red_circle: **Tech Stack Used** : HTML,CSS, JavaScript 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora 
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 Project already present. If you want to do enhancement, comment on this issue.

**Comment by meetarora10** [comment]
@Avdhesh-Varshney can you tell where this project is present, I have checked this project but couldn't find it
