### ISSUE TITLE
📃:  Drawing Pad

### ISSUE THREAD

**Issue by Damini2004** [Avdhesh-Varshney/WebMasterLog#606]
:red_circle: **Title** :  Drawing Pad
:red_circle: **Aim** :  Drawing Pad
:red_circle: **Tech Stack Used** :  HTML,CSS,JS

### Screenshots 📷
![image](https://github.com/user-attachments/assets/9389739d-ecd9-4166-b3b6-8cf4c1493d8f)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Damini Chachane
- What is your participant role?  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
issue already present #600
