### ISSUE TITLE
📃: Add Vowel Counter

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#612]
:red_circle: **Title** : Vowel Counter
:red_circle: **Aim** : Counts the number of vowels in the entered input string by the user .
:red_circle: **Tech Stack Used** : HTML,CSS,JavaScript

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 go ahead.
