### ISSUE TITLE
📃: Add Temperature Convertor

### ISSUE THREAD

**Issue by ImmidiSivani** [Avdhesh-Varshney/WebMasterLog#615]
:red_circle: **Title** : Temperature Convertor
:red_circle: **Aim** : Converts Temperature from Celsius to Farenheit and viceversa
:red_circle: **Tech Stack Used** : HTML,CSS,Javascript

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Immidi Sivani
- What is your participant role?  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ImmidiSivani convertors, calculators & games are not allowed.
