### ISSUE TITLE
GitHub Profile Viewer with Repositories Filter using React JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#62]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : GitHub Profile Viewer with Repositories Filter
:red_circle: **Aim** : Create a web application that allows users to view a GitHub user's profile information along with their repositories.
:red_circle: **Tech Stack Used** : HTML, CSS, React, Bootstrap
:red_circle: **Category** :  React-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anushkabh** [comment]
kindly assign me this issue under JWOC'24 @Avdhesh-Varshney 
anushka 
github.com/Anushkabh
JWOC contributor

**Comment by codebreaker3008** [comment]
@Avdhesh-Varshney could you assign this to me ?

**Comment by VanshikaSabharwal** [comment]
@Avdhesh-Varshney  Can you please assign this to me. 

Name:-Vanshika Sabharwal
Github:- https://github.com/VanshikaSabharwal
I am a GSSOC contributor

**Comment by DharshiBalasubramaniyam** [comment]
@Avdhesh-Varshney Can you please assign this issue to me? 

Would it be alright if I use Tailwind CSS for styling instead of Bootstrap for this issue? Otherwise, I can use plain CSS.

**Comment by Avdhesh-Varshney** [comment]
@DharshiBalasubramaniyam No prob. U can use Tailwind CSS
