### ISSUE TITLE
📃: Add Tic-Tac-Toe game using JS

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Avdhesh-Varshney/WebMasterLog#635]
:red_circle: **Title** :  Tic-Tac-Toe
:red_circle: **Aim** : To add the game
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
No games allowed.
