### ISSUE TITLE
📃: Add moon phase visibility (LunarCycle) Vanilla JS Project

### ISSUE THREAD

**Issue by vansh-codes** [Avdhesh-Varshney/WebMasterLog#659]
:red_circle: **Title** : Moon Phase Finder
:red_circle: **Aim** : Tells the current phase of the moon
:red_circle: **Tech Stack Used** : HTML, CSS, JavaScript

### Screenshots 📷

![image](https://github.com/user-attachments/assets/a6b6d404-2146-4030-aead-5235ee1620d0)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vansh Chaurasiya
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSoC'24
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@vansh-codes can you explain more about this project?

**Comment by vansh-codes** [comment]
> @vansh-codes can you explain more about this project?

Hello @Avdhesh-Varshney 
Everyday we see different area of moon enlightened, we have name of each phase of moon, example: full moon, new moon, wanning gibbous, etc..
This project tells about the phase of the moon on that day. It can be seen on the screenshot attached above
**We have date mentioned along with the phase of moon on that day:**
**Yesterday 26 July, there was wanning gibbous phase of moon, you can see the photo of the moon and verify with the actual moon on the sky**
**Also it says the date when next new moon will be visible**
I hope you understood what I want to say

**Comment by Avdhesh-Varshney** [comment]
So, this app is able to calculate future dates moon condition?
Project name: `Moon-Phase-Check` or `Moon-Visibility-Check`. Don't include `calculator` term

**Comment by vansh-codes** [comment]
> So, this app is able to calculate future dates moon condition? Project name: `Moon-Phase-Check` or `Moon-Visibility-Check`. Don't include `calculator` term

Sure!
