### ISSUE TITLE
Emoji Maker Project using Vanilla JS

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/WebMasterLog#66]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : Emoji Maker Project
:red_circle: **Aim** : Build a project which can provide user to choose different parts of the emoji like eyes, ears, mouth, etc. and create your own emoji and save and copy that emoji picture in your system.
:red_circle: **Tech Stack Used** : HTML, CSS, JS
:red_circle: **Category** :  Vanilla-JS

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSOC, GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Bishal-35** [comment]
Bishal Karmakar
https://github.com/Bishal-35
I want to work under it under JWoC'24

**Comment by SohanRC** [comment]
Please assign me under JWOC 2024.

Name = Sohan RoyChowdhury.
Github = https://github.com/SohanRC
Role = Under JWOC 2024.

**Comment by Avdhesh-Varshney** [comment]
@SohanRC Assigned to you. Follow the Contributing guidelines carefully.

**Comment by SohanRC** [comment]
@Avdhesh-Varshney Can you please explain the project with more details ?

**Comment by SohanRC** [comment]
> @Avdhesh-Varshney Can you please explain the project with more details ?

Like , what is the main function of this website ? It is not clear from the description

**Comment by Avdhesh-Varshney** [comment]
Build a website which can provide user the choice of different parts of emoji like eyes, nose, etc. and by picking and combining those and after aligning, website will able to create a emoji of thier choices.

For example, blinked eye, mouth may be smiling, nose either have or not present or different type of options for user to choose, etc.

Also website will show the option to download the final image of emoji in their system.

**Comment by Avdhesh-Varshney** [comment]
Completed 🎉
