### ISSUE TITLE
📃: Add Perfect Square Number Checker:

### ISSUE THREAD

**Issue by Anshika14528** [Avdhesh-Varshney/WebMasterLog#663]
:red_circle: **Title** : Perfect Square Number Checker
:red_circle: **Aim** : It helps us to check if given number is perfect square or not.The Perfect squares Number are the squares of the whole numbers  such as 16 , 25.
:red_circle: **Tech Stack Used** : HTML,CSS JS

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anshika
- What is your participant role? GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 Now, these projects are not acceptable.

Please fill the feedback form: https://forms.gle/Wvsp9N8TDF1WPStq9
