### ISSUE TITLE
🐛: Wrong description of the Isogram Checker project .

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#667]
:red_circle: **Title** : Isogram Checker
:red_circle: **Bug** : An isogram string is a string in which no letter occurs more than once. But in this project wrong description for the isogram string is provided and so result is also wrong .
:red_circle: **Changes** :  I can make changes to work this according to an actual isogram checker .

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@meetarora10 go ahead.

Please fill the feedback form: https://forms.gle/Wvsp9N8TDF1WPStq9
