### ISSUE TITLE
🧑‍💻: Add hover effects on all the project's card of the website.

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#677]
:red_circle: **Title** : Add hover effects
:red_circle: **Enhancement Aim** : Improve the UI of the website .
:red_circle: **Changes** : I want to add a feature in which on hover on the cards there is an hover effect .

### Screenshots 📷
![Screenshot (871)](https://github.com/user-attachments/assets/c558556d-7570-40d0-ae53-ed1801aaf9a6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Don't use external css. Use only bootstrap css or inline css.
