### ISSUE TITLE
📃: Add  meal calorie calculator

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/WebMasterLog#680]
:red_circle: **Title** :  meal calorie calculator
:red_circle: **Aim** : to plan respective meal - Input: Selection of foods or dishes with their portion sizes.
Output: Total calorie count for the entire meal. 
:red_circle: **Tech Stack Used** : html, css , js

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Ananya Gupta
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required.
