### ISSUE TITLE
📃: Quiz App using Typescript

### ISSUE THREAD

**Issue by Madhavan112** [Avdhesh-Varshney/WebMasterLog#682]
:red_circle: **Title** :Quiz App using Typescript 
:red_circle: **Aim** :To build a  quiz application  with help of typescript 
:red_circle: **Tech Stack Used** : Typescript,React and Tailwind

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Madhavan V
- What is your participant role? GSSOC24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Madhavan112 go ahead.
