### ISSUE TITLE
📃: Add Armstrong Number Checker using React .

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#696]
:red_circle: **Title** : Armstrong Number Checker
:red_circle: **Aim** : This project checks whether the input number is armstrong or not and displays the corresponding message .
:red_circle: **Tech Stack Used** : React

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
not required.
