### ISSUE TITLE
📃: Temperature converter (Vanila js)

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Avdhesh-Varshney/WebMasterLog#699]
:red_circle: **Title** : Temperature converter 
:red_circle: **Aim** : Convert teperature between Celsius, Fahrenheit, Kelvin
:red_circle: **Tech Stack Used** : html, css, js

### Screenshots 📷

![image](https://github.com/user-attachments/assets/f06cffb0-edc0-4a9d-a2ac-2a905497a4df)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : dharshi
- What is your participant role? gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not allowed.

**Comment by DharshiBalasubramaniyam** [comment]
> Not allowed.

May i know why?

**Comment by Avdhesh-Varshney** [comment]
I would not like to keep `convertors`, `games`, `calculators`, etc. These are already mention in `Issue Creation Guidelines`.

Please fill this survey form, https://forms.gle/Wvsp9N8TDF1WPStq9

**Comment by DharshiBalasubramaniyam** [comment]
> I would not like to keep `convertors`, `games`, `calculators`, etc. These are already mention in `Issue Creation Guidelines`.
> 
> Please fill this survey form, https://forms.gle/Wvsp9N8TDF1WPStq9

Okay. No issues.
