### ISSUE TITLE
📃: Amazon Clone frontend

### ISSUE THREAD

**Issue by shellygarg10** [Avdhesh-Varshney/WebMasterLog#714]
:red_circle: **Title** :  Amazon clone frontend
:red_circle: **Aim** :  To showcase first project one can make using html css only 
:red_circle: **Tech Stack Used** : HTML CSS 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shelly Garg
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC 24 
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shellygarg10** [comment]
@Avdhesh-Varshney please assign this issue to me.

**Comment by kavya410004** [comment]
@Avdhesh-Varshney I believe this issue requires me to clone the amazon home page by using HTML and CSS. I can work on this and make the web page responsive as well. 
Can I use JavaScript as well?
Can you assign this issue to me? I am willing to work on this. Thank you.
