### ISSUE TITLE
📃:  Youtube clone in Typescript with React

### ISSUE THREAD

**Issue by Utsavladia** [Avdhesh-Varshney/WebMasterLog#716]
:red_circle: **Title** : 
:red_circle: **Aim** : 
:red_circle: **Tech Stack Used** : 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/f2ac69d4-812c-407e-9e9f-b4d37dba652b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Utsav Ladia
- What is your participant role? Gssoc

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Please fill this survey form: https://forms.gle/Wvsp9N8TDF1WPStq9
