### ISSUE TITLE
NOT Visible Sidebar properly

### ISSUE THREAD

**Issue by Utsavladia** [Avdhesh-Varshney/WebMasterLog#718]
:red_circle: **Title** :
:red_circle: **Bug** :
:red_circle: **Changes** :  

### Screenshots 📷
![image](https://github.com/user-attachments/assets/7cd19d1b-d37c-499e-9d3d-ef1da07763d9)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Utsav Ladia
- What is your participant role?GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
It's a problem of `light mode`. If you want to work on it, I've assigned to you.

**Comment by Avdhesh-Varshney** [comment]
Use this [context api](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/src/contexts/Context.jsx). I've already created these 2 `isDarkMode, setDarkMode,` parameters. It will help to declare it globally.

Do it fast within 2 days.

**Comment by Utsavladia** [comment]
@Avdhesh-Varshney 
it is coming as black on screen 
![image](https://github.com/user-attachments/assets/5fbb1fad-b592-448b-a4bd-8bd0ac2f675d)

on npm i 
npm run dev
if there any setup other than this is required

**Comment by Avdhesh-Varshney** [comment]
VITE_GITHUB_REPO_URL=https://api.github.com/repos/Avdhesh-Varshney/WebMasterLog
VITE_MAIN_BRANCH_URL=https://github.com/Avdhesh-Varshney/WebMasterLog/raw/main
