### ISSUE TITLE
📃: Blood Donation Form

### ISSUE THREAD

**Issue by Khushi-Pushkar** [Avdhesh-Varshney/WebMasterLog#720]
:red_circle: **Title** : Blood Donation Form
:red_circle: **Aim** : The aim of a blood donation form is to gather essential information from potential blood donors to ensure the safety and suitability of both the donor and the recipient.
:red_circle: **Tech Stack Used** : HTML CSS 

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Khushi Pushkar
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Please fill this survey form: https://forms.gle/Wvsp9N8TDF1WPStq9
