### ISSUE TITLE
📃: want to create an Personal Portfolio Website project

### ISSUE THREAD

**Issue by pallasivasai** [Avdhesh-Varshney/WebMasterLog#726]
:red_circle: **Personal Portfolio Website** : 
:red_circle: **this will help the most of freshers when they want's to creat thier own website!** : 
:red_circle: **HTML, CSS, JS** : 

### Screenshots 📷

will share in the PR section

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Psivasai
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
am a GSSOC Contributor Please assign me this issue under GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by JomanaMahmoud** [comment]
can you assign this to me i am contributing in gssoc-ext and hacktoberfest
