### ISSUE TITLE
📃:  want to add Weather App

### ISSUE THREAD

**Issue by pallasivasai** [Avdhesh-Varshney/WebMasterLog#727]
:red_circle: **Weather App** : 
:red_circle: **want to add Weather App** : 
:red_circle: **HTML, CSS, JS** : 

### Screenshots 📷

will share in the PR!
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Psivasai
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
am a GSSOC contributor please assign me this issue under GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by pallasivasai** [comment]
@Avdhesh-Varshney please assign me this issue!

**Comment by Avdhesh-Varshney** [comment]
https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Intermediate/Weather-App
