### ISSUE TITLE
🧑‍💻: Display the average reading time also in word-counter project. 

### ISSUE THREAD

**Issue by meetarora10** [Avdhesh-Varshney/WebMasterLog#731]
:red_circle: **Title** :Display the average reading time also in word-counter project. 
:red_circle: **Enhancement Aim** : Displays the reading time for the entered sentence .
:red_circle: **Changes** : Display the average reading time also in word-counter project. 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Meet Arora
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Mention your approach before raising your pr.

**Comment by meetarora10** [comment]
@Avdhesh-Varshney  I want to display the average reading time taken to read the text entered by the user .
If we assume a reading speed of 200 words per minute, you can calculate the estimated reading time in minutes by dividing the word count by the reading speed.
