### ISSUE TITLE
🧑‍💻: Improve Navbar Color Contrast for Better Font Visibility

### ISSUE THREAD

**Issue by lovelymahor** [Avdhesh-Varshney/WebMasterLog#735]
:red_circle: **Title** :
:red_circle: **Enhancement Aim** :

The current color contrast of the navbar does not provide clear visibility of the font, making it difficult for users to read the text. This issue affects the overall user experience and accessibility of the website.

:red_circle: **Changes** : 

Update the CSS file to change the navbar background color.
Update the CSS file to change the navbar font color.
Test the changes using the color contrast checker to ensure compliance with accessibility standards.
Review and test across different devices and screen resolutions to ensure consistency.

### Screenshots 📷

![Screenshot (335)](https://github.com/user-attachments/assets/afd322dc-7f3e-4d68-98f5-38e1957f8134)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
It's related to light/dark mode. I've already created `isDarkMode` variable. You've to customize it using inline css or tailwind css only. No external css allowed.

**Comment by lovelymahor** [comment]
@Avdhesh-Varshney, can you please tell me the commands for running this repository on localhost?

**Comment by Avdhesh-Varshney** [comment]
It's just a react project. 
- npm i
- create a `.env` file and keep the below urls in it.
- npm run dev

VITE_GITHUB_REPO_URL=https://api.github.com/repos/Avdhesh-Varshney/WebMasterLog
VITE_MAIN_BRANCH_URL=https://github.com/Avdhesh-Varshney/WebMasterLog/raw/main
