### ISSUE TITLE
📃: Adding a new projecr under React "Recruit-O-hub"

### ISSUE THREAD

**Issue by Sourabh782** [Avdhesh-Varshney/WebMasterLog#748]
:red_circle: **Title** :  Recruit-O-hub
:red_circle: **Aim** :  A site developed to narrow down the bridge between recruiters and employees
:red_circle: **Tech Stack Used** :  React, Css

### Screenshots 📷

Na

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Sourabh Singh Rawat
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sourabh782** [comment]
My idea was to develop frontend of a recruitment website, which will include :
1. Landing page
2. Login and signup page
3. New jobs section
 
So basically my idea is to build a frontend project, which in future I can also integrate backend and show as a full stack project

**Comment by Avdhesh-Varshney** [comment]
https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/React-JS-Projects/Advanced/Job-Portal

It's already present in repo

**Comment by Sourabh782** [comment]
Oh sorry I didn't saw it

**Comment by Sourabh782** [comment]
Can I opt for clones? Will they be valid?

**Comment by Sourabh782** [comment]
I have gone through projects, can I do Netflix clone ?
Like js Netflix clone?

**Comment by Avdhesh-Varshney** [comment]
Means projects of other repository
