### ISSUE TITLE
📃:memory Game with Typescript 

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#779]
:red_circle: **Title** : Memory Game with Typescript 
:red_circle: **Aim** : to make Memory Game with Typescript 
:red_circle: **Tech Stack Used** : Typescript

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi
- What is your participant role?  Hacktoberfest and gssoc ext 24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
No games allowed. #108
