### ISSUE TITLE
📃: Add Meme Creator

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/WebMasterLog#780]
:red_circle: **Title** :  Meme Creator
:red_circle: **Aim** : Add meme creator that take various field input and generate meme
:red_circle: **Tech Stack Used** : vanilla js html css

### Screenshots 📷

![sss](https://github.com/user-attachments/assets/36dfcd03-4ac9-4bbe-a6db-09759c40b8c9)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- What is your participant role? hacktober fest and gssoc ext

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Mohith1490** [comment]
Hey can you assign this issue to me
#hacktoberfest
