### ISSUE TITLE
Update: Implement Custom Cursor Follower Effect with Redux State Management

### ISSUE THREAD

**Issue by tejasbenibagde** [Avdhesh-Varshney/WebMasterLog#784]
### Issue Title
Implement Custom Cursor Follower Effect with Redux State Management

### Issue Description

:red_circle: **Enhancement Aim** :
To enhance the user experience by implementing a visually engaging custom cursor follower effect that dynamically responds to user interactions.

:red_circle: **Changes** :
- Implement a custom cursor effect that follows the mouse movement.
- Change the cursor appearance based on hover states over specific elements (e.g., buttons, links).
- Store the cursor state (open/close) in Redux for consistent behavior across components.
- Include smooth animations for cursor transitions.
- Reference a demo for inspiration: [Minimalistic Cursor Effect](https://tympanus.net/Sketches/018-custom-cursor-filter-6/).

***********************************************************************
- Full name: Tejas Benibagde
- What is your participant role? GSSOC - ext , hactoberfest

**Comment by itznayan** [comment]
hey @tejasbenibagde  ,please assign me this issue under GSSOC'24 Extd and hackerfest.

**Comment by Avdhesh-Varshney** [comment]
This type of cursor is not required.
