### ISSUE TITLE
📃: Add hotstar clone

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#793]
:red_circle: **Title** :  Hotstar clone
:red_circle: **Tech Stack Used** : Frontend (html, css, js)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aditi Jain
- What is your participant role?  Gssoc ext and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@Aditijainnn Open source is not to get the highest rank on leaderboard. It's a learning period with the like minded people and gain knowledge of different fields from others.
This is your last chance.
