### ISSUE TITLE
📃: Add Tic-Tac-Toe Project in React

### ISSUE THREAD

**Issue by iAmDiksha** [Avdhesh-Varshney/WebMasterLog#794]
:red_circle: **Tic Tac Toe Game** : 
:red_circle: **Aim** : 
:red_circle: **React JS** : 

### Screenshots 📷
<img width="561" alt="image" src="https://github.com/user-attachments/assets/61daa008-2a7f-4407-ab66-7458e0043e0f">

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Diksha Jain
- What is your participant role? 
GSSOC-EXT, HACKTOBERFEST
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by rishikaa1** [comment]
@iAmDiksha i would like to work on issue.

**Comment by Avdhesh-Varshney** [comment]
No games allowed.
