### ISSUE TITLE
📃: we add the project of github profile search engine using api

### ISSUE THREAD

**Issue by adityalaxkar123** [Avdhesh-Varshney/WebMasterLog#795]
# a github profile search engine in which people can search the profile and see the following,followers and repos.

**Comment by adityalaxkar123** [comment]
me a gssoc'24 extended member can you assign it to me

**Comment by Avdhesh-Varshney** [comment]
Fill all the issue templates requirements

**Comment by adityalaxkar123** [comment]
Title: a frontend project of GitHub profile search engine 
Tech stack: frontend technology 


### Screenshots 📷
Work in progress. I will give after assign the issue.


***********************************************************************
- What is your participant role? Me a GSSOC'24 extended member 

***********************************************************************
Happy Contributing 🚀

**Comment by adityalaxkar123** [comment]
review this @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
Can you mention those technologies?

**Comment by adityalaxkar123** [comment]
Tech stack: html,css, JavaScript

**Comment by Avdhesh-Varshney** [comment]
Already present [here](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Intermediate/Github-Profile-Viewer)
