### ISSUE TITLE
📃: Rock-Paper-Scissors

### ISSUE THREAD

**Issue by Amankr200** [Avdhesh-Varshney/WebMasterLog#812]
🔴 Title :Rock-Paper-Scissors
🔴 Tech stack : html, css
🔴 Objective : to tech basics

https://github.com/user-attachments/assets/0da1a70e-6e79-4e4c-b0a3-8bfeb9306589

 

✅ Details to Include When Taking the Issue:
Name : Aman Kumar
GSSOC ext, Hacktoberfest,

**Comment by Avdhesh-Varshney** [comment]
No games allowed. #108
