### ISSUE TITLE
📃: Add QR generator

### ISSUE THREAD

**Issue by ananyag309** [Avdhesh-Varshney/WebMasterLog#813]
:red_circle: **Title** : QR generator
:red_circle: **Aim** :  paster the url and generate the qr
:red_circle: **Tech Stack Used** : js css html

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- What is your participant role?  gssoc hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by RaiDevX8** [comment]
i would like to work on it

**Comment by vikas83pal** [comment]
@Avdhesh-Varshney i would like to work on this issue
