### ISSUE TITLE
📃: Advanced Weather App

### ISSUE THREAD

**Issue by shalini-bhandari** [Avdhesh-Varshney/WebMasterLog#818]
:red_circle: **Title** : Weather App
:red_circle: **Aim** : To make interactive weather application that fetches and displays weather information based on user location or searched city
:red_circle: **Tech Stack Used** : HTML, CSS, JavaScript and OpenWeather API

### Screenshots 📷
N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shalini Bhandari
- What is your participant role? gssoc-ext, hacktoberfest-accepted

***********************************************************************
@Avdhesh-Varshney kindly assign me this issue

**Comment by Avdhesh-Varshney** [comment]
Already present [here](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Intermediate/Weather-App)
