### ISSUE TITLE
📃: adding an advanced AUTH page.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Avdhesh-Varshney/WebMasterLog#824]
:red_circle: **Title** :  advanced auth page
:red_circle: **Aim** : this has jwt , bycrypt and proper tokenization approch to ensure proper safety.this comes with a mailing system aswell.
:red_circle: **Tech Stack Used** : 

<img width="736" alt="Screenshot 2024-10-08 at 8 53 56 PM" src="https://github.com/user-attachments/assets/9226bc95-5238-4093-be72-827223d9e24a">
<img width="938" alt="Screenshot 2024-10-08 at 8 54 01 PM" src="https://github.com/user-attachments/assets/93c48c24-4cd1-4e5d-a7d6-da22c3d34a8e">

@Avdhesh-Varshney can you please assign me this task.
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : T rahul prabhu
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
What will be the tech stack of this project?

**Comment by T-Rahul-prabhu-38** [comment]
mern , JWTs mailtrap and cookies

**Comment by Avdhesh-Varshney** [comment]
Already present [here](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Node-JS-Projects/Intermediate/JWT-Authenticator-With-Roles)
