### ISSUE TITLE
📃: Addition of DocXtract Project

### ISSUE THREAD

**Issue by Shariq2003** [Avdhesh-Varshney/WebMasterLog#827]
:red_circle: **Title** : Addition of DocXtract Project
:red_circle: **Aim** : Addition of DocXtract Project
:red_circle: **Tech Stack Used** : ReactJS

This is the implementation of a real life problem that I faced in my 2nd year during my DSA prep.
I have to manage manually marking of DSA questions that I have completed in the XLSX file.
But by this, I was get rid of all that stuff by making the online platform that provides me a Progress marker and generates an XLSX. and also show that on UI.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/2e9ad725-b1d7-4bb6-84ef-2dabe7f946b2)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shariq
- What is your participant role? 
GSSOC Ext
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Never create a lots of issues at 1 time.
