### ISSUE TITLE
📃: [Add project] Netflix Clone 

### ISSUE THREAD

**Issue by hamzathul** [Avdhesh-Varshney/WebMasterLog#833]
:red_circle: **Netflix Clone** : 
:red_circle: **To add netflix clone project to React js section. it is an intermediate project** : 
:red_circle: **React.js** : 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Hamzathul Favas E
- My participant role: gssoc-ext and hacktoberfest 

***********************************************************************

**Comment by AsifQamar** [comment]
@Avdhesh-Varshney assign me this issue
