### ISSUE TITLE
📃: Youtube clone

### ISSUE THREAD

**Issue by harshgupta2125** [Avdhesh-Varshney/WebMasterLog#838]
:red_circle: **Title** : Youtube Clone
:red_circle: **Aim** :  for beginners to understand how the clone was made
:red_circle: **Tech Stack Used** : front end tech :- html, css, js

### Screenshots 📷

N/A
***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Avdhesh Varshney
- What is your participant role? 
GSSOC ext 
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Already present [here](https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Vanilla-JS-Projects/Basic/Youtube-Clone)
