### ISSUE TITLE
📃: SkillBridge - AI-Driven Competitive P2P Learning and Career Pathway Platform

### ISSUE THREAD

**Issue by J-B-Mugundh** [Avdhesh-Varshney/WebMasterLog#844]
:red_circle: **Title** : SkillBridge - AI-Driven Competitive P2P Learning and Career Pathway Platform
:red_circle: **Aim** : 

- To empower students in excelling at competitive exams while bridging the gap between their career goals and required skills by utilizing AI-driven personalized learning, mock tests, and peer-to-peer collaboration.
- To create AI-powered mock tests using fine-tuned Gemini API for personalized exam preparation.
- To foster a dynamic learning environment where peers can engage in collaborative learning through a feature-rich platform enabling video calls, screen sharing, file sharing, session recording, chatting, whiteboarding, etc.
- To provide real-time assistance and guidance powered by fine-tuned LLMs for users through query analysis of text or image data.
- To develop an AI model to predict the likelihood of admission and career success based on user skills and data analysis.
- To utilize Gemini API to analyze skill gaps and recommend tailored courses.
- To create a secure and robust user interactive platform with engaging learning content and pathways.

:red_circle: **Tech Stack Used** : 

- Frontend: HTML, CSS, ReactJS
- Backend: Python Flask
- Database: SQLite
- AI Model Training: Gradient Boosting Regressor, Support Vector Regressor, Lasso Regressor, Ridge Regressor
- APIs: Gemini API, LinkedIn API, Mirocart API 

### Screenshots 📷
.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : J B Mugundh
- What is your participant role? GSSOC-EXTD

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Never raise more than 2 issues.

**Comment by J-B-Mugundh** [comment]
@Avdhesh-Varshney Could u please let me know why it was removed?

**Comment by Avdhesh-Varshney** [comment]
This issue is assigned you yesterday and you have ready this very large project within 1 day.
OS programs helps you to learn new stacks and contribution process
