### ISSUE TITLE
📃: Unit converter

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#856]
:red_circle: **Title** :  Unit converter
:red_circle: **Aim** : Unit Converter where it just changes meter to kilometer to centimeter -- & Vice-versa.
:red_circle: **Tech Stack Used** : html css js

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi Jain
- What is your participant role?  gssoc ext and ahcktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
