### ISSUE TITLE
📃: Want to add Netflix clone.

### ISSUE THREAD

**Issue by AnanyaSinha16** [Avdhesh-Varshney/WebMasterLog#859]
🔴 Title : Netflix clone
🔴 Aim : To create a Netflix clone with a similar front end and back end to some extent.
🔴 Tech Stack Used : HTML/CSS, React, Node.js, MySQL

 Screenshots 📷
 N/A 
***********************************************************************
✅  *To be Mentioned while taking the issue:
- Full name : Ananya Sinha
- What is your participant role?  GSSoC ext and Hacktoberfest contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AsifQamar** [comment]
@Avdhesh-Varshney please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
Issue already present #833
