### ISSUE TITLE
Auto-Label Workflow for Pull Requests and Issues

### ISSUE THREAD

**Issue by archanasingh11** [Avdhesh-Varshney/WebMasterLog#861]
## Description

I propose adding a **GitHub auto-label workflow** that automatically assigns relevant labels, such as "gssoc-ext" and "hacktoberfest-accepted," to issues and pull requests related to these events. This will ensure more consistent tracking, better organization, and visibility of contributions linked to these important programs.

### Key Features:
- **Automatic Labeling**: 
  - Automatically apply the "gssoc-ext" and "hacktoberfest-accepted" labels to pull requests and issues related to GSSOC Ext and Hacktoberfest.
  
### Use Case:
- Streamlines the labeling process by automating the assignment of labels for pull requests and issues, especially during events like GSSOC and Hacktoberfest.

### Benefits:
1. **Improved Efficiency**: Reduces manual labeling efforts and ensures consistency.
2. **Better Organization**: Labels are applied systematically, making it easier to track event-specific contributions.
3. **Enhanced Contributor Experience**: Contributors receive immediate feedback through labels, improving their visibility within the project.

### Priority:
High

Please @Avdhesh-Varshney assign me this issue with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level3"

**Comment by Avdhesh-Varshney** [comment]
This can't be possible to add labels for levels, different tech stacks, whether it's invalid or not?
If you're able to do so, mention me again.

**Comment by archanasingh11** [comment]
when anyone will raise a issue then the bot will automatically add lebels to them but assigning part is still in yours assigning labels with the help of bot makes the work easier and smoothier

**Comment by Avdhesh-Varshney** [comment]
Not required.
