### ISSUE TITLE
📃: [Advanced NextJS Project] Quasar

### ISSUE THREAD

**Issue by AnanteshG** [Avdhesh-Varshney/WebMasterLog#870]
:red_circle: **Title** : Quasar Prompts
:red_circle: **Aim** : Quasar is a platform where users can log in and share their AI prompts with others, emphasizing the importance of prompt engineering in maximizing AI model performance.
:red_circle: **Tech Stack Used** : Next.js, TailwindCSS, MongoDB, Shadcn

### Screenshots 📷
![image](https://github.com/user-attachments/assets/be58211d-1b61-4712-9d27-fa03a9ffa118)

Demo Prompts :-
![image](https://github.com/user-attachments/assets/98839045-6d42-42a6-8ad8-2d1ab8c84a85)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Anantesh G
- What is your participant role? : GSSoC, Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AnanteshG** [comment]
@Avdhesh-Varshney I don't understand?

**Comment by Avdhesh-Varshney** [comment]
#108 and https://github.com/Avdhesh-Varshney/WebMasterLog/discussions/819

**Comment by AnanteshG** [comment]
So one project at a time?
