### ISSUE TITLE
📃:Responsive Neumorphic Calculator

### ISSUE THREAD

**Issue by nksmanya** [Avdhesh-Varshney/WebMasterLog#876]
Responsive Neumorphic Calculator
To create a neumorphic-themed calculator 
**Tech Stack Used** :  HTML, CSS and JS

### Screenshots 📷

![image](https://github.com/user-attachments/assets/0d07c0b0-7254-4137-b873-88336b281550)

***********************************************************************
**To be Mentioned while taking the issue :**
- Full name:  Manya .N
- What is your participant role? 
GSSOC, Hackotberfest
***********************************************************************

**Comment by Avdhesh-Varshney** [comment]
#108
