### ISSUE TITLE
📃: Game using Vanilla JS - Monster Hunter 

### ISSUE THREAD

**Issue by ar-rana** [Avdhesh-Varshney/WebMasterLog#878]
:red_circle: **Title** : Monster Hunter
:red_circle: **Aim** : Create a game using vanilla JS and DOM manipulation on HTML canvas.
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots/Videos 📷

https://github.com/user-attachments/assets/289a3003-0970-4933-938f-9871105a6783

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aryan Rana
- What is your participant role? : GSSOC, Hactoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
