### ISSUE TITLE
📃: adding chess 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Avdhesh-Varshney/WebMasterLog#891]
:red_circle: **Title** : chess Game
:red_circle: **Aim** : it is playable chess
:red_circle: **Tech Stack Used** : vanilla JS

### Screenshots 📷
<img width="577" alt="Screenshot 2024-10-13 at 5 09 06 PM" src="https://github.com/user-attachments/assets/53bed2f9-c869-4f70-a748-78116867240d">

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : T Rahul Prabhu
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by T-Rahul-prabhu-38** [comment]
@Avdhesh-Varshney can you assign me this task.

**Comment by Avdhesh-Varshney** [comment]
#108
