### ISSUE TITLE
📃: Tic Tac Toe Game

### ISSUE THREAD

**Issue by itznayan** [Avdhesh-Varshney/WebMasterLog#893]
:red_circle: Tic Tac Toe: 
:red_circle:  A simple yet engaging Tic Tac Toe game built with React, allowing two players to compete against each other in real-time. This project showcases the use of React hooks for state management, component structure, and basic styling for a clean, user-friendly interface. : 
:red_circle: : React

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nayan Mahera
- What is your participant role? GSSoC Extd

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
