### ISSUE TITLE
📃: Add Project Sudoku Solver

### ISSUE THREAD

**Issue by saras-69** [Avdhesh-Varshney/WebMasterLog#896]
:red_circle: Title: Add Project Sudoku Solver
:red_circle: Aim:
Develop a web-based Sudoku Solver that allows users to input a Sudoku puzzle and get the solution instantly. This tool will assist in solving Sudoku puzzles of varying difficulty levels using efficient algorithms.

:red_circle: Tech Stack Used:
HTML
CSS
JavaScript
Screenshots 📷
N/A

:white_check_mark: To be Mentioned while Taking the Issue:
Full name:Saraswati Chandra
What is your participant role?:
 GSSOC, SSOC, JWOC,hacktoberfest etc. -->
Happy Contributing 🚀
All the best! Enjoy your open-source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Already present https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/Vanilla-JS-Projects/Intermediate/Sudoku-Solver
