### ISSUE TITLE
📃: Add BMI calculator

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/WebMasterLog#905]
:red_circle: **Title** :  BMI calculator
:red_circle: **Aim** : A BMI (Body Mass Index) calculator determines a person's body fat based on their weight and height.
:red_circle: **Tech Stack Used** : HTML CSS JS

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi Jain
- What is your participant role?  gssoc ext and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
