### ISSUE TITLE
Design Error 404 page not found

### ISSUE THREAD

**Issue by dev129** [Avdhesh-Varshney/WebMasterLog#919]
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the `GSSOC-ext` and `Hacktoberfest` and `level` labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @dev129 , please add hacktobest and gssoc-ext label

**Comment by dev129** [comment]
Hi @Avdhesh-Varshney , I have finally designed the error 404 page , I am ready to launch the PR. 
![image](https://github.com/user-attachments/assets/463e1339-a5f9-4708-90f3-9665af92cc60)

**Comment by Avdhesh-Varshney** [comment]
LGTM

**Comment by dev129** [comment]
Hi @Avdhesh-Varshney , please review and check my PR.
