### ISSUE TITLE
📃: Memory block game

### ISSUE THREAD

**Issue by RahulScripted** [Avdhesh-Varshney/WebMasterLog#920]
:red_circle: **Title**:  I want to add a memory block game in vanilla JS -> Basic Project
:red_circle: **Aim**:  Memory Block" is a classic memory-matching game where players must flip over pairs of blocks to find matching images, testing their visual recall and concentration. With a grid of seemingly random blocks, the challenge is remembering where each image is hidden and strategically flip pairs to reveal matches, clearing the board as quickly as possible. Whether playing casually or competing for the highest score, Memory Block provides an engaging and brain-boosting experience for all ages!
:red_circle: **Tech Stack Used** :  HTML, CSS, JS

### Screenshots 📷

![Screenshot 2024-10-15 230300](https://github.com/user-attachments/assets/7e74b1e4-cc31-47d4-91bf-6fd482a83164)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :** gssoc-extd, hacktoberfest2024,lebel2
- Full name :  Rahul Goswami
- What is your participant role? 
GSSOC, Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open-source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
