### ISSUE TITLE
🧑‍💻: Loader UI Enhancement

### ISSUE THREAD

**Issue by roushan-code** [Avdhesh-Varshney/WebMasterLog#921]
:red_circle: **Title** :Website Loader UI Enhancement
:red_circle: **Enhancement Aim** : Loading things in website looks more attractive
:red_circle: **Changes** :  I want to change the simple  Loading thing in App.jsx file

### Screenshots 📷
![Load](https://github.com/user-attachments/assets/38216314-fa1a-47fb-ac8e-4415706a687e)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Roushan Singh
- What is your participant role? 
GSSoC ext and Hacktoberfest contributor

***********************************************************************

**Comment by Avdhesh-Varshney** [comment]
#783 Under working
