### ISSUE TITLE
📃: [Intermediate React.js Project]: Task Manager App

### ISSUE THREAD

**Issue by PhantomANaz** [Avdhesh-Varshney/WebMasterLog#922]
:red_circle: **Title** : Task Manager App using React.js
:red_circle: **Aim** : Build a simple task manager app where users can create, edit, and delete tasks. Users can also mark tasks as complete and filter tasks based on their status (all, active, completed).
:red_circle: **Tech Stack Used** : React.js

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ayesha Naznin
- What is your participant role? 
GSSOC 24' Extended Contributor, hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108 and https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/React-JS-Projects/Basic/To-Do-List
