### ISSUE TITLE
📃: Image Search Engine

### ISSUE THREAD

**Issue by roushan-code** [Avdhesh-Varshney/WebMasterLog#923]
:red_circle: **Title** : Image Search Engine
:red_circle: **Aim** : create an Image Search Engine, where users can search any image (like pexels, unsplash, pixabay)
:red_circle: **Tech Stack Used** :  HTML, CSS, JavaScript

### Screenshots 📷
![img search](https://github.com/user-attachments/assets/99a70feb-adac-45fc-9309-70330971e48b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Roushan Singh
- What is your participant role? 
GSSoC ext and Hacktoberfest contributor

***********************************************************************

**Comment by samricoder009** [comment]
@roushan-code  i would like work on this
