### ISSUE TITLE
📃: Add P2P Voice Call Application

### ISSUE THREAD

**Issue by sezallagwal** [Avdhesh-Varshney/WebMasterLog#925]
# 🔴 Title: P2P Voice Call Application

## 🔴 Aim:
The aim of this project is to build a peer-to-peer (P2P) voice call application using Next.js, allowing users to initiate and join voice calls without relying on centralized servers for media streaming. The application will include core features like secure user authentication, voice conferencing, chat functionality, and seamless peer-to-peer communication.

## 🔴 Tech Stack Used:

- **Frontend**: Next.js, ShadCN (UI components)
- **Backend**: Node.js, Express
- **Real-Time Communication**: WebRTC for peer-to-peer voice, Socket.io for signaling
- **Authentication**: Clerk for secure user authentication
- **Database**: MongoDB (for storing user data, call history, etc.)
- **Hosting**: Vercel (frontend), Heroku or AWS (backend)

## 🔴 Screenshots 📷
N/A

## ✅ To be Mentioned while taking the issue:
- **Full Name**: Sezal Lagwal
- **Participant Role**: GSSOC'24 Ext, Hacktoberfest

**Comment by Avdhesh-Varshney** [comment]
#906

**Comment by sezallagwal** [comment]
> #906

its a video call app. i am trying to create a voice call app like discord vcs or whatsapp voice call
can you reconsider labels?

**Comment by amitb0ra** [comment]
> #906

my app is only for p2p video calls between two users. she is trying to make app like whatsapp calls or discord vc

**Comment by Avdhesh-Varshney** [comment]
Sorry for my response. It's just closed by watching similar issues heading and content. I'm not focusing on keyword difference.
Go ahead.
