### ISSUE TITLE
🧑‍💻: Improve the UI of card section by adding hover effect.

### ISSUE THREAD

**Issue by Himanshu-kumar025** [Avdhesh-Varshney/WebMasterLog#926]
:red_circle: **Title** : : Improve the UI of card section by adding hover effect.
:red_circle: **Enhancement Aim** :  To make this card section more engaging
:red_circle: **Changes** : Adding some hover effects

### Screenshots 📷
![webmaster](https://github.com/user-attachments/assets/e4d3d4a3-1d35-4676-8cbb-bced11d5b7cb)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
I raise this issue because hover effect make this card section more engaging.

- Full name : Himanshu Kumar 
- 
- What is your participant role? 
GSSOC'24

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#783 UI under processing
