### ISSUE TITLE
📃: Want to add new Spotify Clone

### ISSUE THREAD

**Issue by Mansi07sharma** [Avdhesh-Varshney/WebMasterLog#938]
:red_circle: **Spotify Clone* : 
:red_circle: **Front-End** : 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/eb9c77e5-99dd-4c2a-a5a8-ff58ded536c5)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mansi Sharma
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
https://github.com/Avdhesh-Varshney/WebMasterLog/tree/main/Front-end-Projects/Intermediate/Spotify-Clone
