### ISSUE TITLE
📃:  Want to add a vanilla JS project that is 'Currency Converter'

### ISSUE THREAD

**Issue by Suvadip-sana** [Avdhesh-Varshney/WebMasterLog#944]
:red_circle: **Title** : Currency Converter
:red_circle: **Aim** : Helps to convert one currency rate to another currency rate(Support more than 150 country) & It has implement all the JS core logic
:red_circle: **Tech Stack Used** :  HTML, CSS, JavaScript

### Screenshots 📷

![currency1](https://github.com/user-attachments/assets/cb81353a-3da9-463c-8c18-cf47ceff224b)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Suvadip Sana
- What is your participant role?  `gssoc-extd`, `hacktoberfest`

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
