### ISSUE TITLE
📃: Want to add Rock-Paper-Scissor game under 'Vanilla JS'

### ISSUE THREAD

**Issue by Suvadip-sana** [Avdhesh-Varshney/WebMasterLog#945]
:red_circle: **Title** : Rock Paper Scissor game
:red_circle: **Aim** :  It implement the core logic of JS
:red_circle: **Tech Stack Used** :  HTML, CSS, JS

### Screenshots 📷

![image](https://github.com/user-attachments/assets/74ee2860-73f3-4622-a39a-f32b0c40689a)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Suvadip Sana
- What is your participant role?  `gssoc-extd`, 'hacktoberfest`

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
