### ISSUE TITLE
📃: Want to add Simon Say game under 'Vanilla JS' project

### ISSUE THREAD

**Issue by Suvadip-sana** [Avdhesh-Varshney/WebMasterLog#946]
:red_circle: **Title** : Simon Say
:red_circle: **Aim** :  It implement all advance core logic of JS
:red_circle: **Tech Stack Used** : HTML, CSS, JS

### Screenshots 📷

https://github.com/user-attachments/assets/14e49fb1-032e-47c9-809b-6b55971ef3ca

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Suvadip Sana
- What is your participant role?  `gssoc-extd`, `hacktoberfest`

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
#108
