### ISSUE TITLE
📃: I want to add amazon clone under 'Frontend'

### ISSUE THREAD

**Issue by Suvadip-sana** [Avdhesh-Varshney/WebMasterLog#947]
:red_circle: **Title** : Amazon clone
:red_circle: **Aim** : Helps to figureout the CSS implementation and also attention to details.
:red_circle: **Tech Stack Used** :  HTML, CSS

### Screenshots 📷

![image](https://github.com/user-attachments/assets/dab650e6-0315-4d8b-9f23-4e5efbad0c80)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Suvadip Sana
- What is your participant role?  `gssoc-extd`, 'hacktoberfest`

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Suvadip-sana** [comment]
@Avdhesh-Varshney 

In which folder I add this project?   Low, Intermediate or High?

**Comment by Avdhesh-Varshney** [comment]
`level1` -> Basic

**Comment by Suvadip-sana** [comment]
@Avdhesh-Varshney   Is this Basic with `label-1` or Intermediate with `label-2`?   Because I saw in your repo that every website clone is in Intermediate label.
