### ISSUE TITLE
🧑‍💻: Add icons for email and password and also the onclick functionality for password icon in LoginSignUpForm (Front-end project)

### ISSUE THREAD

**Issue by LNischala** [Avdhesh-Varshney/WebMasterLog#955]
:red_circle: **Title** : Icons for email and password and onclick password toggle
:red_circle: **Enhancement Aim**  : To make the UI more intuitive for the user I want to add icons for email and password. The password icon when clicked toggles between showing the password and hiding it
:red_circle: **Changes** : Password visibility toggle addition

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : L.Nischala
- What is your participant role? 
        GSSoC Extd 2024 contributer

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by haseebzaki-07** [comment]
hey @LNischala please assign me this task

**Comment by Ayushkumarsinha08** [comment]
hello please assign me this task
