### ISSUE TITLE
📃: TextUtils project

### ISSUE THREAD

**Issue by LNischala** [Avdhesh-Varshney/WebMasterLog#958]
:red_circle: **Title** : TextUtils
:red_circle: **Aim** : TextUtils is an application that helps manipulate the text (converting to uppercase or lowercase, copying the text to the clipboard, removing extra spaces, etc.)
:red_circle: **Tech Stack Used** : React.js, Bootstrap

### Screenshots 📷

![textutils](https://github.com/user-attachments/assets/7407c611-3603-465d-ba1a-0e39d1ba5abc)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Lakkaraju Nischala
- What is your participant role?  GSSoC Extd 2024 Contributer

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Deejai007** [comment]
Hello @LNischala ,
I am interested in contributing to the TextUtils project and have worked on a similar project in React.js before. Could you please assign this issue to me?
Name : Deepak Jain
Role : Contributer
