### ISSUE TITLE
HangMan Game using Vanilla JS

### ISSUE THREAD

**Issue by SohanRC** [Avdhesh-Varshney/WebMasterLog#96]
### WebMasterLog Repository (Proposing new issue)
:red_circle: **Project Title** : HangMan Game 
:red_circle: **Aim** : Develop a hangman game where user needs to guess the correct word for the given hint or else the game ends.
:red_circle: **Category** :  Vanilla JS
:red_circle: **Contribute** :  JWOC 2024.

### Screenshots 📷

![Screenshot 2024-02-16 123825](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124901633/0e4b418a-8a11-4272-a4e6-bd7aed06ddaa)

***********************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be all the main components.
   * **Cover image** of the application, if project will be deployed in future, with the name of the folder in Kebab-Case (hypen-separated).
   * Main files in formatted state so that code will be readable.
   * Other Images - In seprate folder named `Images` used to form the application.
* Inside the `Project` folder, the `README.md` file must be filled up properly, with proper visualizations and descriptions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Sohan RoyChowdhury
- GitHub Profile Link : https://github.com/SohanRC
- What is your participant role? - JWOC 2024

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@SohanRC Games are not allowed in this repository.
