### ISSUE TITLE
📃: Para-generator

### ISSUE THREAD

**Issue by roushan-code** [Avdhesh-Varshney/WebMasterLog#963]
:red_circle: **Title** : Para-Generator
:red_circle: **Aim** : It a para-generator web application. In this users only have to enter Number of words. It will automatically generate para with that number of words
:red_circle: **Tech Stack Used** :  HTML, CSS, JavaScript

### Screenshots 📷
![para-generator](https://github.com/user-attachments/assets/c56627d8-01b3-4804-8d4e-384093f95a14)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Roushan Singh
- What is your participant role? 
GSSoC ext and Hacktoberfest contributor

***********************************************************************

**Comment by SKG24** [comment]
Title : Para-Generator
Aim : It a para-generator web application. In this users only have to enter Number of words. It will automatically generate para with that number of words
Tech Stack Used : HTML, CSS, JavaScript

Name Sanat Kumar Gupta
Participation : gssoc'24 ext, hackoctober

I have implemented this project on my local device. I would like you to assign this to me.
![Screenshot 2024-10-21 at 3 00 52 PM](https://github.com/user-attachments/assets/360ff2d4-e084-45b6-9f34-8628e36b9ac1)


If there is any change required do let me know.

Thank you!
