### ISSUE TITLE
feature enhancement

### ISSUE THREAD

**Issue by Aasthaa10** [Avdhesh-Varshney/WebMasterLog#965]
![image](https://github.com/user-attachments/assets/fb4b45ca-d9fa-4179-9314-d0bd4e65c21e)
here we can add register or sign in option for the new user or already having an account at this web site
link: https://web-master-log.vercel.app/  @Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
No signup or login required. It's open for all.
