### ISSUE TITLE
🐛: video space is very much

### ISSUE THREAD

**Issue by Aasthaa10** [Avdhesh-Varshney/WebMasterLog#966]
:red_circle: **Bug** :video space is taking the whole site displaying space
:red_circle: **Changes** :  
we can reduce the length and breadth of the video as it is taking very much space which looks not good at all.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/6b789473-d784-4dbf-a617-6924a78401bd)

- Full name : Aastha kumari
- What is your participant role? 
GSSOC24-extented
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Make it responsive with different devices

**Comment by SSameer20** [comment]
> Make it responsive with different devices

/assign this to me.
Already opened an issue related to it #988
