### ISSUE TITLE
🧑‍💻: Contributor Section New Features

### ISSUE THREAD

**Issue by KAmaL-senpai** [Avdhesh-Varshney/WebMasterLog#967]
:red_circle: **Title** :  Contributor Section
:red_circle: **Enhancement Aim** : We can add button to the contributor profile picture in the contributor section so when any user clicked to the user profile they will be redirected to the contributor github profile.
:red_circle: **Changes** : 

### Screenshots 📷
![Screenshot (264)](https://github.com/user-attachments/assets/0a551028-bb8a-43fb-af05-dd9491372d30)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Kamal Sing Bhumij
- What is your participant role? GSSOC 2024, Hacktoberfest 2024

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Already present
