### ISSUE TITLE
🧑‍💻: Enhancing the Functioning of Intro Video 

### ISSUE THREAD

**Issue by Dyfintie** [Avdhesh-Varshney/WebMasterLog#982]
:red_circle: **Title** :  Enhancing the Functioning of Intro Video 
:red_circle: **Enhancement Aim** : To make the UX better by auto playing the video 
:red_circle: **Changes** :  Autoplaying the video as soon as the user lands on the home page

### Screenshots 📷

![image](https://github.com/user-attachments/assets/0b8b5955-0937-4985-845b-6b27c3920c32)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Varun Pandey
- What is your participant role?  GSSOC Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required
