### ISSUE TITLE
🧑‍💻: Footer 

### ISSUE THREAD

**Issue by Bhum-ika** [Avdhesh-Varshney/WebMasterLog#983]
:red_circle: **Title** : Footer Improvement
:red_circle: **Enhancement Aim** : Make it more appealing , aligned and better
:red_circle: **Changes** : There should be two columns and two rows. one column  have the summary of your website and which is larger the second one has connect with me and then second row should have those two lines 
t© 2024 All Rights Reserved
Made By Avdhesh Varshney 👦 
at the last. 
Those icons can have border around them  full rounded 

### Screenshots 📷
![Screenshot 2024-10-22 104321](https://github.com/user-attachments/assets/8bd5e01e-97c4-4782-8c04-da05f8977374)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bhumika SHarma
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
PR will be merged on good look

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?

**Comment by ambrishgoswami** [comment]
please assign this issue
