### ISSUE TITLE
🧑‍💻: Added Stargazers and Forkers section in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Siddhart2004** [Avdhesh-Varshney/WebMasterLog#986]
:red_circle: **Title** :Added Stargazers and Forkers section in CONTRIBUTING.md

### Screenshots 📷
![image](https://github.com/user-attachments/assets/bd48310f-7c4a-4d69-8f1d-4f73614ab544)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Siddharth A
- What is your participant role? 
GSSOC-ext,Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required.
