### ISSUE TITLE
📃: Add a AI Movie Recommender

### ISSUE THREAD

**Issue by amitb0ra** [Avdhesh-Varshney/WebMasterLog#989]
:red_circle: Title : Add a AI Movie Recommender

:red_circle: Aim :
The goal of this issue is to integrate a movie recommendation feature into the existing application using the Gemini API for AI-powered recommendations. The system should dynamically recommend movies based on user preferences or watch history. It should be user-friendly, responsive, and seamlessly integrated with the current app structure.

:red_circle: Tech Stack Used :

Next.js for building the frontend.
Gemini API for movie recommendation algorithms.
ShadCN for UI components.
TypeScript for type safety.
MongoDB (optional) for storing user preferences/watch history.
Vercel for deployment.

Screenshots 📷
N/A

:white_check_mark: To be Mentioned while taking the issue :

Full name : Amit Singh Bora
What is your participant role? Hacktoberfest,  GSSOC
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by jiyabansal123** [comment]
@amitb0ra can you assign this to me

**Comment by amitb0ra** [comment]
@Avdhesh-Varshney can you add level 3 ?
