### ISSUE TITLE
📃: Add a to-do-list project in 'Frontend' with HTML, CSS & JS 

### ISSUE THREAD

**Issue by Edasgh** [Avdhesh-Varshney/WebMasterLog#997]
🔴 **Title** : A simple to do list app
🔴 **Tech Stack Used** : HTML, CSS , JS

##Description
A simple and intuitive To-Do List app that allows users to manage their tasks. Users can add, edit, and delete tasks, with options for setting priority (High, Medium & Low) and tracking the progress (Not Started, In Progress, Done) of each task. Tasks are organized into two categories: "School/Work" and "Personal." This app uses local storage to persist tasks, so they remain even after the page is refreshed.

I have a similar work done here : https://a-minimal-todo-using-vanilla-js.netlify.app/

##Screenshots
![desktop-design](https://github.com/user-attachments/assets/abe29773-7804-4acf-8d03-f4563af46e23)
![Screenshot 2024-10-25 144851](https://github.com/user-attachments/assets/37aaa7f0-b1d5-4bdd-9acb-9affcd66908a)

##✅ To be Mentioned while taking the issue :

- Full name : Eshita Das
- What is your participant role? gssoc-extd, hacktoberfest

Please assign me this issue under gssoc-extd, hacktoberfest labels and a relevant level label

**Comment by jiyabansal123** [comment]
i want to do this ,please add hacktober fest label and assign this to me

**Comment by jiyabansal123** [comment]
@Edasgh assign this to me and add hacktober fest label

**Comment by Edasgh** [comment]
> @Edasgh assign this to me and add hacktober fest label

I'm not the project admin bro...I'm requesting here for issue assignment

**Comment by jiyabansal123** [comment]
@Avdhesh-Varshney pls assign me this project, and add hacktober fest label  on this

**Comment by Edasgh** [comment]
@Avdhesh-Varshney I created the issue so please assign me

**Comment by Avdhesh-Varshney** [comment]
Not required.

**Comment by Avdhesh-Varshney** [comment]
You can do enhancement, if wants.
